### ISSUE TITLE
Problem: Perform policy checks on originals job breaks on a Disk image transfer when packages are deleted after extraction

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1007]
**Expected behaviour**

A `Disk image` transfer type using the [`SampleTransfers/ISODiskImage`](https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/ISODiskImage) sample transfer works with the following settings in the processing configuration:

```
Perform file format identification (Transfer): Yes
Extract packages: Yes
Delete packages after extraction: Yes
Perform policy checks on originals: Yes
```

**Current behaviour**

In the UI the `Policy checks for originals` job gets active and it never ends and the workflow doesn't continue and the MCPServer logs this:

```
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-11-26 23:54:33 local:run:29:  Running Determine if Dataverse METS XML needs to be parsed (package ad44d0a0-bcf8-45e6-99d7-0c993ac552ef)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-11-26 23:54:33 base:mark_complete:102:  GetUnitVarLinkJob aa6f0571-caf0-44f9-b48d-9da4f725a600 done with exit code 0
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-11-26 23:54:33 decisions:run:51:  Running Perform policy checks on originals? (package ad44d0a0-bcf8-45e6-99d7-0c993ac552ef)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-11-26 23:54:33 decisions:decide:129:  Using user selected chain c611a6ff-dfdb-46d1-b390-f366a6ea6f66 for link 70fc7040-d4fb-4d19-a0e6-792387ca1006
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-11-26 23:54:33 base:mark_complete:102:  NextChainDecisionJob f4b23e6b-df0d-4dd3-863f-47a973f9150d done with exit code 0
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-11-26 23:54:33 chain:__init__:101:  Creating JobChain c611a6ff-dfdb-46d1-b390-f366a6ea6f66 for package ad44d0a0-bcf8-45e6-99d7-0c993ac552ef (initial link 6c147aeb-20c5-47ce-9f40-7f22683cea1f)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-11-26 23:54:33 client:run:113:  Running Policy checks for originals (package ad44d0a0-bcf8-45e6-99d7-0c993ac552ef)
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2019-11-26 23:54:33 _base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7fac471c5a90 state=finished raised AttributeError>
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
archivematica-mcp-server_1       |     callback(self)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/queues.py", line 233, in _job_completed_callback
archivematica-mcp-server_1       |     next_job = future.result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
archivematica-mcp-server_1       |     return self.__get_result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
archivematica-mcp-server_1       |     result = self.fn(*self.args, **self.kwargs)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 126, in run
archivematica-mcp-server_1       |     self.submit_tasks()
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 232, in submit_tasks
archivematica-mcp-server_1       |     filter_subdir=self.filter_subdir,
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 640, in files
archivematica-mcp-server_1       |     yield get_file_replacement_mapping(file_obj, self.current_path)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 485, in get_file_replacement_mapping
archivematica-mcp-server_1       |     dirname = os.path.dirname(file_obj.currentlocation)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/posixpath.py", line 122, in dirname
archivematica-mcp-server_1       |     i = p.rfind('/') + 1
archivematica-mcp-server_1       | AttributeError: 'NoneType' object has no attribute 'rfind'
```

I tested in http://am110bionic.qa.archivematica.net using the same settings and the job works and the workflow continues.

**Steps to reproduce**

1. Set the following settings in your processing configuration:

```
Perform file format identification (Transfer): Yes
Extract packages: Yes
Delete packages after extraction: Yes
Perform policy checks on originals: Yes
```

2. Start a `Disk image` transfer type using the [`SampleTransfers/ISODiskImage`](https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/ISODiskImage) sample transfer

3. The workflow will get stuck in the `Policy checks for originals` job.

**Your environment (version of Archivematica, operating system, other relevant details)**

qa/1.x (https://github.com/artefactual/archivematica/commit/c302f4149b83c0a348f36d36cf611bbfd7fa0150) in the docker-compose environment

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
I'm struggling to think of a real life use case for checking policies on a disk image :thinking:

**Comment by replaceafill** [comment]
Just for the record I got a similar error (under similar processing configuration settings) with a `Dspace` type of transfer using [`SampleTransfers/DSpaceExport`](https://github.com/artefactual/archivematica-sampledata/tree/6e299d0c43e3ccc19f6eb1132a7b04b70e300866/SampleTransfers/DSpaceExport):

```
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-12-19 15:58:47 local:run:29:  Running Determine if Dataverse METS XML needs to be parsed (package cf9c184f-a04b-4a42-a572-fe1c6f3bcc17)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-12-19 15:58:47 base:mark_complete:102:  GetUnitVarLinkJob 8ce913b7-f6f0-463c-aaf9-1447b4c1579e done with exit code 0
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-12-19 15:58:47 decisions:run:51:  Running Perform policy checks on originals? (package cf9c184f-a04b-4a42-a572-fe1c6f3bcc17)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-12-19 15:58:47 decisions:decide:126:  Using user selected chain c611a6ff-dfdb-46d1-b390-f366a6ea6f66 for link 70fc7040-d4fb-4d19-a0e6-792387ca1006
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-12-19 15:58:47 base:mark_complete:102:  NextChainDecisionJob fbe23dae-f2aa-4eca-997f-2e99e7e21e19 done with exit code 0
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2019-12-19 15:58:47 chain:__init__:101:  Creating JobChain c611a6ff-dfdb-46d1-b390-f366a6ea6f66 for package cf9c184f-a04b-4a42-a572-fe1c6f3bcc17 (initial link 6c147aeb-20c5-47ce-9f40-7f22683cea1f)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2019-12-19 15:58:47 client:run:113:  Running Policy checks for originals (package cf9c184f-a04b-4a42-a572-fe1c6f3bcc17)
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2019-12-19 15:58:47 _base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f595c0d7a10 state=finished raised AttributeError>
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
archivematica-mcp-server_1       |     callback(self)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/queues.py", line 233, in _job_completed_callback
archivematica-mcp-server_1       |     next_job = future.result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
archivematica-mcp-server_1       |     return self.__get_result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
archivematica-mcp-server_1       |     result = self.fn(*self.args, **self.kwargs)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 126, in run
archivematica-mcp-server_1       |     self.submit_tasks()
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 232, in submit_tasks
archivematica-mcp-server_1       |     filter_subdir=self.filter_subdir,
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 640, in files
archivematica-mcp-server_1       |     yield get_file_replacement_mapping(file_obj, self.current_path)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 485, in get_file_replacement_mapping
archivematica-mcp-server_1       |     dirname = os.path.dirname(file_obj.currentlocation)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/posixpath.py", line 122, in dirname
archivematica-mcp-server_1       |     i = p.rfind('/') + 1
archivematica-mcp-server_1       | AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by sromkey** [comment]
You could conceivably want to check policies on the extracted contents of a disk image or a DSpace transfer but it's still a pretty edgy use case.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
