### ISSUE TITLE
Problem: Processing fails for large transfer names

### ISSUE THREAD

**Issue by jorikvankemenade** [archivematica/Issues#1027]
**Expected behaviour**
If a transfer is accepted and *structurally* correct ingestion should finish without problems. If there is a problem with the transfer, i.e. the transfer name is too long, the transfer should be rejected and this should be communicated with the user.

**Current behaviour**
If I start a transfer with a very long name, e.g. 120 characters, processing will fail at the `Check if AIP is a file or directory` job:

![image](https://user-images.githubusercontent.com/7934339/70628660-d79ece80-1c28-11ea-832a-85c53406500b.png)

This is logged in the MCP server logs:

```
INFO      2019-12-11 14:05:09  archivematica.mcp.server.packages:packages:get_or_create_from_db_by_path:762:  Updating SIP 6840b93b-da85-4f72-8497-6c7378b68f14 path: %sharedPath%watchedDirectories/workFlowDecisions/compressionAIPDecisions/basic-transfer-1576058106-L2hvbWUvdXNlci9waWN0dXJlcy9BNF9QeXJhbWlkcy0xNTAzOTk1NTY3LXdhdGVybWFya2VkLTc2OC1Wb2xtZXVyLmpwZw__.tar-6840b93b-da85-4f72-8497-6c7378b68f14/
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs.chain:chain:__init__:101:  Creating JobChain 27cf6ca9-11b4-41ac-9014-f8018bcbad5e for package 6840b93b-da85-4f72-8497-6c7378b68f14 (initial link 01d64f58-8295-4b7b-9cab-8f1b153a504f)
INFO      2019-12-11 14:05:09  archivematica.mcp.server.jobs.decisions:decisions:run:213:  Running Select compression algorithm (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs.decisions:decisions:run:229:  Job f4e11cde-ea72-49a2-9b00-e45c1be95afb got preconfigured context {u'%AIPCompressionAlgorithm%': u'7z-bzip2'}
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs:base:mark_complete:102:  UpdateContextDecisionJob f4e11cde-ea72-49a2-9b00-e45c1be95afb done with exit code 0
INFO      2019-12-11 14:05:09  archivematica.mcp.server.jobs.decisions:decisions:run:213:  Running Select compression level (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs.decisions:decisions:run:229:  Job 0056fd7d-7d94-4a7d-b252-116aa73000a6 got preconfigured context {u'%AIPCompressionLevel%': u'5'}
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs:base:mark_complete:102:  UpdateContextDecisionJob 0056fd7d-7d94-4a7d-b252-116aa73000a6 done with exit code 0
INFO      2019-12-11 14:05:09  archivematica.mcp.server.jobs.client:client:run:113:  Running Compress AIP (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:221:  Submitted gearman job e47f0ffe-8750-4987-b960-14f96716ef4c (compressaip_v0.0)
DEBUG     2019-12-11 14:05:09  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:265:  Task e1eaa7b1-6584-4b70-8d35-c1fc25e6673e finished! Result COMPLETE - 0
INFO      2019-12-11 14:05:10  archivematica.mcp.server.jobs.client:client:run:113:  Running Copy submission documentation (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:221:  Submitted gearman job ce9b93f1-64ad-4227-a84f-1bdca654749e (copysubmissiondocs_v0.0)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:265:  Task de14824a-4fb3-4370-9262-0958f30472d9 finished! Result COMPLETE - 0
INFO      2019-12-11 14:05:10  archivematica.mcp.server.jobs.client:client:run:113:  Running Set bag file permissions (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:221:  Submitted gearman job 2e0855a5-0a4e-4674-8662-479c1eabe5ff (setfilepermission_v0.0)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:265:  Task bf750088-72ca-45b9-bbe8-4c11de363627 finished! Result COMPLETE - 0
INFO      2019-12-11 14:05:10  archivematica.mcp.server.jobs.client:client:run:113:  Running Check if AIP is a file or directory (package 6840b93b-da85-4f72-8497-6c7378b68f14)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:221:  Submitted gearman job a3bf02a4-802e-4806-a032-c858703a4c31 (test_v0.0)
DEBUG     2019-12-11 14:05:10  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:265:  Task 987d356f-c85d-4ee4-839a-3a8f81f3dc0d finished! Result COMPLETE - 1
INFO      2019-12-11 14:05:10  archivematica.mcp.server.jobs.client:client:run:113:  Running Removed bagged files (package 6840b93b-da85-4f72-8497-6c7378b68f14)
ERROR     2019-12-11 14:05:10  concurrent.futures:_base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f82a2756f50 state=finished raised DataError>
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/usr/lib/archivematica/MCPServer/server/queues.py", line 233, in _job_completed_callback
    next_job = future.result()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
    _reraise(*exc)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
    result = f(*args, **kw)
  File "/usr/lib/archivematica/MCPServer/server/jobs/client.py", line 128, in run
    self.wait_for_task_results()
  File "/usr/lib/archivematica/MCPServer/server/jobs/client.py", line 149, in wait_for_task_results
    for task in self.task_backend.wait_for_results(self):
  File "/usr/lib/archivematica/MCPServer/server/tasks/backends/gearman_backend.py", line 99, in wait_for_results
    self._submit_batch(job, current_task_batch)
  File "/usr/lib/archivematica/MCPServer/server/tasks/backends/gearman_backend.py", line 156, in _submit_batch
    task_batch.submit(self.client, job)
  File "/usr/lib/archivematica/MCPServer/server/tasks/backends/gearman_backend.py", line 204, in submit
    Task.bulk_log(self.tasks, job)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
    _reraise(*exc)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
    result = f(*args, **kw)
  File "/usr/lib/archivematica/MCPServer/server/tasks/task.py", line 73, in bulk_log
    models.Task.objects.bulk_create(model_objects)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/query.py", line 389, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
DataError: (1406, "Data too long for column 'arguments' at row 1")
```

The `arguments` column in the `Task` model has a [maximum length of 1000 characters](https://github.com/artefactual/archivematica/blob/997e047b8ad204549abc7d1744c30cac9d0b8312/src/dashboard/src/main/models.py#L801). Apparently, the arguments for this job with a filename of that length exceeds this limit. I see two options here, and I would very much like to know what you guys think is the best option:

1. Increase the maximum length of the `arguments` column in the `Task` model. The main question here would be, what is reasonable and when will we run into this problem again?
2. When accepting a transfer check the length of the transfer name, and possibly some other lengths, and fail the transfer if they are too long.

I think implementing `2` would be something that is important regardless of our opinion on `1`. But this brings us to the question: what lengths should be checked and what are reasonable limits. I think this depends on what can end up in the `arguments` column of a task. Does anyone have some sort of idea or list for this?

**Steps to reproduce**
Start a transfer with a very long name.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.11 (latest qa/1.x). CentOS 7.7 and MySQL 5.7 for both the SS and MCP databases.
---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Thanks @jorikvankemenade, and for the related issue. 

For this one, there might be a certain amount of undefined behavior going on depending on one's environment. 

I can't quite confirm what you're seeing in the Ubuntu environment (https://sandbox.archivematica.org/) or CentOS I have available. For either I have the following test transfer names and results.

### 150 chars
```
AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ111122223333444455556666777788889999000000000
```

- transfer completes and AIP is stored.

### 200 chars

```
AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ11112222333344445555666677778888999900000000000000000000000000000000000000000000000000000000000
```

- transfer completes and AIP is stored.

### 250 chars

```
AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ1111222233334444555566667777888899990000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

- Fails at `Job Rename with transfer UUID` (early in the transfer tab).

### 300 chars

```
AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ111122223333444455556666777788889999000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

- transfer doesn't start.

----

So a couple of things to consider there. We do know filenames are tricky! :slightly_smiling_face: . And it also looks like there are strategies to ease situations like this and handling of failures. I'd like to invite you to try the same transfer name you worked with on the sandbox above, and see what happens. More feedback from curious users with the capability to test would be great too.

**Comment by ross-spencer** [comment]
Also, logging these historical notes that Sarah R dug up for us as they look relevant to this:

* https://projects.artefactual.com/issues/9946
* https://projects.artefactual.com/issues/6624

**Comment by jorikvankemenade** [comment]
@ross-spencer thank you for your investigation. I will try your tests in both mine and the sandbox next week to see if I can get to the bottom of this. 

> And it also looks like there are strategies to ease situations like this and handling of failures.

In a previous version of what we were trying I had basically filenames of theoretically unlimited length, which is not the best idea. In our current naming convention, we use a service dependent identifier and a `sha256`. So the transfer names are long, but should comfortably stay within your successful 200 character range.

**Comment by jorikvankemenade** [comment]
Also about this issue: https://projects.artefactual.com/issues/9946

If I look into the [task model](https://github.com/artefactual/archivematica/blob/997e047b8ad204549abc7d1744c30cac9d0b8312/src/dashboard/src/main/models.py#L801):

```
# actually a `varbinary(1000)` in the database
arguments = models.CharField(max_length=1000, blank=True)
```

So it might be me, but it seems that the issues and the code do not match. Or do I have to check a different place?

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/1050

**Comment by hakamine** [comment]
The issue is reproducible in AM 1.13.2/SS 0.19.0 (Ubuntu). For a transfer name of 83 characters, the ingest crashed with the following error in the MCP Server log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/queues.py", line 228, in _job_completed_callback
    next_job = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/jobs/client.py", line 126, in run
    self.wait_for_task_results()
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/jobs/client.py", line 147, in wait_for_task_results
    for task in self.task_backend.wait_for_results(self):
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py",
line 98, in wait_for_results
    self._submit_batch(job, current_task_batch)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py",
line 155, in _submit_batch
    task_batch.submit(self.client, job)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py",
line 202, in submit
    Task.bulk_log(self.tasks, job)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/task.py", line 72, in bulk_log
    models.Task.objects.bulk_create(model_objects)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/model
s/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/model
s/query.py", line 440, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/model
s/query.py", line 1102, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/model
s/query.py", line 1079, in _insert
   return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/model
s/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/backe
nds/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/utils
.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/utils/si
x.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/backe
nds/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/backe
nds/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/MySQLdb/cursors
.py", line 209, in execute
    res = self._query(query)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/MySQLdb/cursors
.py", line 315, in _query
    db.query(q)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/MySQLdb/connect
ions.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'arguments' at row 1")
```
