### ISSUE TITLE
Problem: Partial reingest fails on previously reingested packages where files have been deleted through the re-normalization process (filegrp in METS is recorded as deleted)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1044]
**Expected behaviour**

Scripts in Archivematica which consume data from an AIP during partial or metadata-only reingest work without failure. 

**Current behaviour**

[`parse_mets_to_db.py` ](https://github.com/artefactual/archivematica/blob/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/MCPClient/lib/clientScripts/parse_mets_to_db.py) attempts to access data in a previously-reingested METS file that won't exist for a deleted file, i.e. deleted via being replaced during re-normalization during reingest. 

```
filegrpuse deleted
amdid amdSec_5
file_uuid 8bb0beb3-1950-4a3d-b7f6-cf052a3fdd0f
original_path %SIPDirectory%objects/beihai-8bb0beb3-1950-4a3d-b7f6-cf052a3fdd0f.tif
```

```
'NoneType' object has no attribute 'get'Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 564, in call
    job.set_status(main(job, args.sip_uuid, args.sip_path))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 545, in main
    files = parse_files(job, root)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 77, in parse_files
    current_path = fe.find("mets:FLocat", namespaces=ns.NSMAP).get(
AttributeError: 'NoneType' object has no attribute 'get'
```

[METS.7af411d3-3741-4e85-8e69-241fc204e09a.zip](https://github.com/archivematica/Issues/files/4032508/METS.7af411d3-3741-4e85-8e69-241fc204e09a.zip)

**Steps to reproduce**

1. Start DemoTransferCSV.
2. Normalize for preservation.
3. Observe the UUIDs associated with normalized files.
4. Full- or partial- reingest with normalization still on.
5. Observe the UUIDs associated with normalized files has changed.
6. Run partial-reingest. 
7. Observe the failure described above. 
8. For the UUID of the file causing the failure, the `filegrp` will be recorded as deleted and will not have a `flocat:href` to access.
9. Partial-reingest.
10. The failure above will be recreated and the updated AIP not created.

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica `1.10` and verified on sandbox.archivematica.org. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
@ross-spencer does this result in the failure of AIP reingest or can it still complete successfully?

**Comment by ross-spencer** [comment]
hi @sromkey thanks for the prompt. I have updated the steps list to reflect that it does fail to complete reingest.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
