### ISSUE TITLE
Problem: In qa/0.x, S3 cannot be used as AIP Storage source

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#1048]
**Expected behaviour**
Archivematica users can use S3 as AIP Storage and successfully store AIPs.

**Current behaviour**
Currently there's an issue where the AIP fails to store, and the exception is not appropriately handled within the codebase.

Here is an example error:
```
500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/file/Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 365, in call
    args.sip_type,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 244, in store_aip
    related_package_uuid,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 80, in _create_file
    agents=get_agents_from_db(uuid),
  File "/src/archivematicaCommon/lib/storageService.py", line 357, in create_file
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage-service:8000/api/v2/file/
```

Funnily enough, S3 is working fine as a Transfer Source -- one of the features being added to 1.11.

@replaceafill has an idea about where this issue is arising in the codebase. From him:

the _bucket_name property in this block needs to be updated: https://github.com/artefactual/archivematica-storage-service/blob/d54716cd571ac2a6fedf5c4dba314e9c33192cd1/storage_service/locations/models/s3.py#L120-L126
storage_service/locations/models/s3.py:120-126
```python
            LOGGER.info("Creating S3 bucket '%s'", self._bucket_name())
            # LocationConstraint cannot be specified if it us-east-1 because it is the default, see: https://github.com/boto/boto3/issues/125
            if self.region.lower() == "us-east-1":
                self.client.create_bucket(Bucket=self._bucket_name())
            else:
```

it's called just bucket_name now: https://github.com/artefactual/archivematica-storage-service/blob/d54716cd571ac2a6fedf5c4dba314e9c33192cd1/storage_service/locations/models/s3.py#L130-L132
```python
storage_service/locations/models/s3.py:130-132
    @property
    def bucket_name(self):
        return self.bucket or self.space_id
```

**Steps to reproduce**
1. Set up S3 as a Space and create an associated Location according to current documentation
2. Run through a transfer and store the AIP
3. You should get an error like above!

Maybe related:
https://github.com/archivematica/Issues/issues/975
https://github.com/archivematica/Issues/issues/558
...and many others

**Your environment (version of Archivematica, operating system, other relevant details)**
qa/1.x

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I got curious why the current tests didn't caught this and found an interesting situation which I think it's worth addressing while fixing this:

If you run all the tests for the S3 model in a docker-compose environment, all of them pass successfully (like they do in Travis):

```bash
replaceafill@eluk:~/dev/archivematica/am/compose$ docker-compose run --workdir /src --rm --no-deps --entrypoint py.test -e "DJANGO_SETTINGS_MODULE=storage_service.settings.test" archivematica-storage-service -v storage_service/locations/tests/test_s3.py
=============================================================================== test session starts ================================================================================
platform linux2 -- Python 2.7.17, pytest-3.8.0, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
Django settings: storage_service.settings.test (from environment variable)
rootdir: /src/storage_service, inifile: pytest.ini
plugins: mock-1.13.0, cov-2.4.0, django-3.7.0
collected 7 items                                                                                                                                                                  

storage_service/locations/tests/test_s3.py::TestS3Storage::test_browse PASSED                                                                                                [ 14%]
storage_service/locations/tests/ten (at least for me!): [this `except` block](https://github.com/artefactual/archivematica-storage-service/blob/d54716cd571ac2a6fedf5c4dba314e9c33192cd1/storage_service/locations/models/s3.py#L117-L128) is never reached by neither of the [couple of tests for the `non` happy path](https://github.com/artefactual/archivematica-storage-service/blob/d54716cd571ac2a6fedf5c4dba314e9c33192cd1/storage_service/locations/tests/test_s3.py#L50-L67).

The `StorageException` expected in those tests doesn't come from the `except` block, but from the `boto_exception` decorator.

Also, the 

st_s3.py::TestS3Storage::test_bucket_name PASSED                                                                                           [ 28%]
storage_service/locations/tests/test_s3.py::TestS3Storage::test_bucket_name_falls_back_to_space_id PASSED                                                                    [ 42%]
storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_continues_if_exists PASSED                                                              [ 57%]
storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_creates_bucket PASSED                                                                   [ 71%]
storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_creation_fails PASSED                                                                   [ 85%]
storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_get_location_fails PASSED                                                               [100%]

================================================================================= warnings summary =================================================================================
/usr/local/lib/python2.7/site-packages/_pytest/cacheprovider.py:55: PytestWarning: could not create cache path /src/storage_service/.pytest_cache/v/cache/nodeids
  PytestWarning(fmt.format(**args) if args else fmt), self._config

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================================================================== 7 passed, 1 warnings in 17.65 seconds =======================================================================
```

But, if you run only the `test_ensure_bucket_exists_creates_bucket` test, this issue is caught:

```bash
replaceafill@eluk:~/dev/archivematica/am/compose$ docker-compose run --workdir /src --rm --no-deps --entrypoint py.test -e "DJANGO_SETTINGS_MODULE=storage_service.settings.test" archivematica-storage-service -v storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_creates_bucket
=============================================================================== test session starts ================================================================================
platform linux2 -- Python 2.7.17, pytest-3.8.0, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
Django settings: storage_service.settings.test (from environment variable)
rootdir: /src/storage_service, inifile: pytest.ini
plugins: mock-1.13.0, cov-2.4.0, django-3.7.0
collected 1 item                                                                                                                                                                   

storage_service/locations/tests/test_s3.py::TestS3Storage::test_ensure_bucket_exists_creates_bucket FAILED                                                                   [100%]

===================================================================================== FAILURES =====================================================================================
______________________________________________________________ TestS3Storage.test_ensure_bucket_exists_creates_bucket ______________________________________________________________

self = <locations.tests.test_s3.TestS3Storage testMethod=test_ensure_bucket_exists_creates_bucket>

    def test_ensure_bucket_exists_creates_bucket(self):
        client = boto3.client("s3", region_name="us-east-1")
    
>       self.s3_object._ensure_bucket_exists()

storage_service/locations/tests/test_s3.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
storage_service/locations/models/s3.py:33: in _inner
    return fn(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <S3: S3 object>

    @boto_exception
    def _ensure_bucket_exists(self):
        """Ensure that the bucket exists by asking it something about itself.
            If we cannot retrieve metadata about it, and specifically, we can
            determine the endpoint has returned a `NoSuchBucket' error code then
            we attempt to create the bucket, else, we raise a StorageException.
    
            NB. Boto3 has an API called head_bucket that looks to return 400,
            Bad Request at time of 1.9.174 when the S3 documents suggest 404, or
            more 'specifically':
    
                > Otherwise, the operation might return responses such as 404 Not
                > Found and 403 Forbidden. "
                via-- Amazon AWS: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html
            """
        LOGGER.debug("Test the S3 bucket '%s' exists", self.bucket_name)
        try:
            loc_info = self.resource.meta.client.get_bucket_location(
                Bucket=self.bucket_name
            )
            LOGGER.debug("S3 bucket's response: %s", loc_info)
        except botocore.exceptions.ClientError as err:
            error_code = err.response["Error"]["Code"]
            if error_code != "NoSuchBucket":
                raise StorageException(err)
>           LOGGER.info("Creating S3 bucket '%s'", self._bucket_name())
E           AttributeError: 'S3' object has no attribute '_bucket_name'

storage_service/locations/models/s3.py:120: AttributeError
------------------------------------------------------------------------------ Captured stdout setup -------------------------------------------------------------------------------
Creating test database for alias 'default'...
------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------
DEBUG     2020-01-09 14:19:24  locations.models.s3:s3:_ensure_bucket_exists:110:  Test the S3 bucket 'test-bucket' exists
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
s3.py                      110 DEBUG    Test the S3 bucket 'test-bucket' exists
----------------------------------------------------------------------------- Captured stdout teardown -----------------------------------------------------------------------------
Destroying test database for alias 'default'...
================================================================================= warnings summary =================================================================================
/usr/local/lib/python2.7/site-packages/_pytest/cacheprovider.py:55: PytestWarning: could not create cache path /src/storage_service/.pytest_cache/v/cache/nodeids
  PytestWarning(fmt.format(**args) if args else fmt), self._config
/usr/local/lib/python2.7/site-packages/_pytest/cacheprovider.py:55: PytestWarning: could not create cache path /src/storage_service/.pytest_cache/v/cache/lastfailed
  PytestWarning(fmt.format(**args) if args else fmt), self._config

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================================================================== 1 failed, 2 warnings in 17.68 seconds =======================================================================
```

Maybe somehow the test setup/fixture is "leaking"?

**Comment by replaceafill** [comment]
The two tests that are "leaking" and prevent `test_ensure_bucket_exists_creates_bucket` to reach the `self._bucket_name` problem are:

* `test_ensure_bucket_exists_continues_if_exists`
* `test_browse`

Both of them create a `test-bucket` bucket that seems to persist across test runs. If  `test_ensure_bucket_exists_creates_bucket` runs before any of them it will fail.

If disable those two tests (by renaming them with a `_test...` prefix) I get consistent failures from `test_ensure_bucket_exists_creates_bucket` on multiple randomized runs.

**Comment by ross-spencer** [comment]
This looks done! I created an S3 space on CentOS and an AIP stored it:

![image](https://user-images.githubusercontent.com/1880412/77372026-13bef080-6d3b-11ea-9da9-bff072f3db2d.png)

And if I look at the S3 dashboard I can see that it has stored successfully: 

![image](https://user-images.githubusercontent.com/1880412/77371946-e2462500-6d3a-11ea-8611-279f646f3050.png)

And its contents accessed:

![image](https://user-images.githubusercontent.com/1880412/77372364-f2aacf80-6d3b-11ea-88cd-d0effecffb8b.png)

And I can do the same with a compressed AIP:

![image](https://user-images.githubusercontent.com/1880412/77372652-8381ab00-6d3c-11ea-968f-3288d83a4920.png)

And download and access its contents:

![image](https://user-images.githubusercontent.com/1880412/77372688-9bf1c580-6d3c-11ea-9184-c1ee4db8155e.png)
