### ISSUE TITLE
Problem: "Generate METS.xml document" fails without error catch when CSV column is invalid

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#1074]
**Expected behaviour**
User are able to click on the "cog" icon and understand why "Generate METS.xml document" fails, if they have a typo in their metadata.csv

**Current behaviour**
While this can be deduced through investigation, it would be better if this kind of error was caught and handled by Python instead of expecting users to read tracebacks. Example below:

```
ValueError(u"Invalid tag name u' Identifier'",)
Traceback (most recent call last):
File "/usr/lib/archivematica/MCPClient/clientScripts/create_mets_v2.py", line 1753, in call
includeAmdSec=includeAmdSec,
File "/usr/lib/archivematica/MCPClient/clientScripts/create_mets_v2.py", line 1013, in createFileSec
job, directoryPath.replace(baseDirectoryPath, "", 1), state
File "/usr/lib/archivematica/MCPClient/clientScripts/create_mets_v2.py", line 276, in createDMDIDsFromCSVMetadata
dmdsecs = createDmdSecsFromCSVParsedMetadata(job, metadata, state)
File "/usr/lib/archivematica/MCPClient/clientScripts/create_mets_v2.py", line 331, in createDmdSecsFromCSVParsedMetadata
etree.SubElement(dc, elem_namespace + key).text = v.decode("utf-8")
File "src/lxml/lxml.etree.pyx", line 3112, in lxml.etree.SubElement (src/lxml/lxml.etree.c:81786)
File "src/lxml/apihelpers.pxi", line 183, in lxml.etree._makeSubElement (src/lxml/lxml.etree.c:18126)
File "src/lxml/apihelpers.pxi", line 1626, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:35069)
ValueError: Invalid tag name u' Identifier
```

**Steps to reproduce**
- Create a transfer that includes the `metadata.csv` import workflow
- Intentionally add a typo to the `metadata.csv` columns, like adding a space between `dc.` and the DublinCore parameter (e.g. `dc. Identifier` to trigger the above error message)

**Your environment (version of Archivematica, operating system, other relevant details)**
1.10.1 CentOS

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
