### ISSUE TITLE
Problem: Storage Service and Dashboard not working on new ansible deploys

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1096]
**Expected behaviour**

After deploying with ansible, the SS and dashboard should start.

**Current behaviour**

Services not starting. Errors:

```
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade systemd[1]: Started Archivematica Storage Service.
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: Traceback (most recent call last):
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/gunicorn", line 5, in <module>
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: from gunicorn.app.wsgiapp import run
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: from gunicorn.app.base import Application
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/gunicorn/app/base.py", line 12, in <module>
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: from gunicorn import util
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/gunicorn/util.py", line 12, in <module>
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: import pkg_resources
Feb 11 18:31:44 mamedin-testam1.10-111-upgrade gunicorn[23331]: ImportError: No module named pkg_resources
``` 

```
Feb 11 12:33:30 mamedin-testam1 systemd: Started Archivematica Dashboard.
Feb 11 12:33:30 mamedin-testam1 gunicorn: Traceback (most recent call last):
Feb 11 12:33:30 mamedin-testam1 gunicorn: File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/gunicorn", line 5, in <module>
Feb 11 12:33:30 mamedin-testam1 gunicorn: from gunicorn.app.wsgiapp import run
Feb 11 12:33:30 mamedin-testam1 gunicorn: File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
Feb 11 12:33:30 mamedin-testam1 gunicorn: from gunicorn.app.base import Application
Feb 11 12:33:30 mamedin-testam1 gunicorn: File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/gunicorn/app/base.py", line 12, in <module>
Feb 11 12:33:30 mamedin-testam1 gunicorn: from gunicorn import util
Feb 11 12:33:30 mamedin-testam1 gunicorn: File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/gunicorn/util.py", line 12, in <module>
Feb 11 12:33:30 mamedin-testam1 gunicorn: import pkg_resources
Feb 11 12:33:30 mamedin-testam1 gunicorn: ImportError: No module named pkg_resources
Feb 11 12:33:30 mamedin-testam1 systemd: archivematica-dashboard.service: main process exited, code=exited, status=1/FAILURE
``` 

**Steps to reproduce**

Deploy AM with ansible

**Your environment (version of Archivematica, operating system, other relevant details)**

I tested with AM qa/1.x and stable/1.10.x
OS: Ubuntu Bionic, Ubuntu Xenial and CentOS

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Looks like a pip issue.

**Comment by mamedin** [comment]
Related to new virtualenv version (20.x)

**Comment by mamedin** [comment]
virtualenv has a new release 20.0.2, and it works fine. 

Closing the issue.
