### ISSUE TITLE
Problem: Cannot save Processing config with translated artifacts available

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1109]
**Expected behaviour**

With the Archivematica built with its i18n components e.g. [here](https://github.com/archivematica/Issues/issues/984) I anticipate being able to save a processing configuration. Currently this does not seem possible, e.g. when Archivematica is switched into French. 

**Current behaviour**

Navigate to:

`Administration` -> `Configuration de traitement` -> `Modifier` (default) -> ...

And try to save the config as-is, or change something and try to change it. Both will result in the (English) message `Failed to save processing configuration`. 

In the logs:
```
archivematica-dashboard_1        | ERROR     2020-02-20 15:56:45  archivematica.dashboard:views_processing:_report_error:55:  Failed to save processing configuration. All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/src/dashboard/src/components/administration/views_processing.py", line 73, in edit
archivematica-dashboard_1        |     form.save_config()
archivematica-dashboard_1        |   File "/src/dashboard/src/components/administration/forms.py", line 448, in save_config
archivematica-dashboard_1        |     config.add_choice(choice_uuid, value, comment=fprops["label"])
archivematica-dashboard_1        |   File "/src/dashboard/src/components/administration/forms.py", line 475, in add_choice
archivematica-dashboard_1        |     comment = etree.Comment(" {} ".format(comment))
archivematica-dashboard_1        |   File "src/lxml/lxml.etree.pyx", line 3015, in lxml.etree.Comment (src/lxml/lxml.etree.c:80763)
archivematica-dashboard_1        |   File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32441)
archivematica-dashboard_1        | ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Steps to reproduce**

As above.

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker-compose with the translation artifacts built as described by #984. 

Tested in `stable/1.10.x` and still present in `qa/1.x` -> `1.11RC`.

**Additional context**

Loosely (or less loosely?) related to https://github.com/archivematica/Issues/issues/1104 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
