### ISSUE TITLE
Problem: bucket name is mandatory when creating an S3 space

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1120]
**Expected behaviour**
If no bucket is specified, the uuid of the space is used

**Current behaviour**

When creating an S3 space using the api , the follow error appears in the logs:

```
ERROR     2020-02-27 07:49:00  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/space/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 259, in obj_create
    fields_dict = {key: bundle.data[key] for key in keep_fields}
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 259, in <dictcomp>
    fields_dict = {key: bundle.data[key] for key in keep_fields}
KeyError: 'bucket'
'''
```

**Steps to reproduce**

Create an S3 space following the process from https://wiki.archivematica.org/Storage_Service_API#Create_space 

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica qa/1.x , SS qa/0.x on centos 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Additional testing note, Santi and I are looking at this at the same time, this behavior diverges from the UI where I can happily create a bucket using the correct behavior identified in the name of this ticket:
![image](https://user-images.githubusercontent.com/1880412/75461507-e86dff00-5950-11ea-8b9e-9f124291092f.png)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
