### ISSUE TITLE
Problem: A bag without a bag-info.txt is a valid bag but it results in an invalid METS (creating a phantom AMDsec) which affects processing of the document

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1129]
**Expected behaviour**

1. METS produced by Archivematica is valid.
2. Archivematica can produce valid AIPS given different combinations of Bag format.

**Current behaviour**

Given the zipped bag attached, Archivematica assumes the existence of `bag-info.txt` which would normally contain metadata parsed into the structure: `<mets:mdWrap MDTYPE="OTHER" OTHERMDTYPE="BagIt">`. Search for amdSec_19, and try to locate both components associated with that ID.

In the PIM online toolkit we see the following: http://pim.fcla.edu/validate/results 

* `line 7848, column 13: cvc-id.1: There is no ID/IDREF binding for IDREF 'amdSec_19'.`

[valid_but_broken.zip](https://github.com/archivematica/Issues/files/4285382/valid_but_broken.zip)

The bag comes from our standard corpus, but it has been modified to have `bag-info.txt` removed, which according to Python bagit is valid.

```
python -m bagit --validate valid_but_broken/
2020-03-04 00:38:28,664 - INFO - Verifying checksum for file valid_but_broken/data/artwork/MARBLES.TGA
2020-03-04 00:38:28,682 - INFO - Verifying checksum for file valid_but_broken/data/ocr-image.png
2020-03-04 00:38:28,682 - INFO - Verifying checksum for file valid_but_broken/data/piiTestDataCreditCardNumbers.txt
2020-03-04 00:38:28,682 - INFO - Verifying checksum for file valid_but_broken/manifest-sha256.txt
2020-03-04 00:38:28,682 - INFO - Verifying checksum for file valid_but_broken/data/View_from_lookout_over_Queenstown_towards_the_Remarkables_in_spring.jpg
2020-03-04 00:38:28,711 - INFO - Verifying checksum for file valid_but_broken/manifest-sha512.txt
2020-03-04 00:38:28,711 - INFO - Verifying checksum for file valid_but_broken/bagit.txt
2020-03-04 00:38:28,711 - INFO - Verifying checksum for file valid_but_broken/data/beihai.tif
2020-03-04 00:38:28,763 - INFO - Verifying checksum for file valid_but_broken/data/bird.mp3
2020-03-04 00:38:28,787 - INFO - valid_but_broken/ is valid
```

**Steps to reproduce**

As above.

Additionally, `mets-reader-wriiter` outputs an error for this METS, and we will see that during partial reingest in Archivematica. 
```
AttributeError("'NoneType' object has no attribute 'tag'",)
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/create_mets_v2.py", line 1681, in call
    keep_normative_structmap=keepNormativeStructmap,
  File "/src/MCPClient/lib/clientScripts/archivematicaCreateMETSReingest.py", line 594, in update_mets
    mets = metsrw.METSDocument.fromfile(old_mets_path)
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 570, in fromfile
    return cls.fromtree(etree.parse(path, parser=parser))
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 594, in fromtree
    mets._parse_tree(tree)
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 520, in _parse_tree
    tree, structMap, normative_parent_elem=normative_struct_map
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 364, in _parse_tree_structmap
    tree, elem, normative_parent_elem=normative_elem
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 368, in _parse_tree_structmap
    self._add_amdsecs_to_fs_entry(elem.get("ADMID"), fs_entry, tree)
  File "/usr/local/lib/python2.7/dist-packages/metsrw/mets.py", line 492, in _add_amdsecs_to_fs_entry
    amdsec = metadata.AMDSec.parse(amdsec_elem)
  File "/usr/local/lib/python2.7/dist-packages/metsrw/metadata.py", line 94, in parse
    if root.tag != utils.lxmlns("mets") + "amdSec":
AttributeError: 'NoneType' object has no attribute 'tag'
```
This could be avoided by validating the METS earlier in both Archivematica, or when the file is opened by `mets-reader-writer`. 

For additional context this error means that mets-reader-writer cannot be used at-all for METS that suffer from this particular issue. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica `1.10.1` and `qa/1.x` release candidate. 

Related to https://github.com/archivematica/Issues/issues/153

**Other sample data**

This can also be tested by removing the `bag-info.txt` from the [sample-data bag transfer](https://github.com/artefactual/archivematica-sampledata/tree/8774133b1922f93015d4e40c8ec13bdf06dbd864/SampleTransfers/BagTransfer).

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
It seems after https://github.com/artefactual/archivematica/pull/1787 this problem not only affects reingest but also the `Generate METS.xml document` job in the `Ingest` tab which [parses the METS using `metsrw`](https://github.com/artefactual/archivematica/blob/bade7adeb0ffb4422b6fb289fe13555d0051fca3/src/MCPClient/lib/clientScripts/create_mets_v2.py#L1867-L1868).

**Comment by sromkey** [comment]
I have tested with the zipped bag provided above and it completes successfully both on initial ingest and on reingest.
