### ISSUE TITLE
Problem: Error handling and logging when creating an AIC is limited

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1169]
**Expected behaviour**

When creating an AIC if there are any difficulties retrieving a file from the storage service for whatever reason then that information is handled and information returned to the user-interface for the user to make a decision on.

**Current behaviour**

We currently assume our connection to the storage service [here](https://github.com/artefactual/archivematica/blob/3e52494735ebfeb0cabc477d95d692034f4b3142/src/MCPClient/lib/clientScripts/create_aic_mets.py#L55-L69) will be successful. If we receive an error from the API, e.g. `{"error_message": "Sorry, this request could not be processed. Please try again later."}` then `lxml` will try to parse the JSON resulting in the error: 
```
Start tag expected, '<' not found, line 1, column 1Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/job.py", line 111, in JobContext
    yield
  File "/usr/lib/archivematica/MCPClient/clientScripts/create_aic_mets.py", line 169, in call
    create_aic_mets(args.aic_uuid, args.aic_dir, job)
  File "/usr/lib/archivematica/MCPClient/clientScripts/create_aic_mets.py", line 155, in create_aic_mets
    aips = get_aip_info(aic_dir, job)
  File "/usr/lib/archivematica/MCPClient/clientScripts/create_aic_mets.py", line 57, in get_aip_info
    root = etree.parse(mets_path)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```
Microservice and Job: `Prepare AIC -> Create AIC METS file`

![image](https://user-images.githubusercontent.com/1880412/78804589-52d18080-798e-11ea-8da0-f4e7148bf45a.png)

**Steps to reproduce**

This was a temporary glitch in Archivematica/the storage service that the user was able to correct  by recreating the AIC. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.11 running on CentOS. 

**Additional context**

Seen on a client site. Where `root = etree.parse(mets_path)` assumes that the file we retrieve will be valid XML there are patterns we can adopt here which removes those assumptions, and handles any errors gracefully so that the debug process is made easier.

There may be other small improvements we can make to this microservice. The download of the METS file might be handled using AMClient patterns introduced in https://github.com/archivematica/Issues/issues/644

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
