### ISSUE TITLE
Problem: Partial reingest of an AIP containing a previously normalized file against a newly disabled rule creates an inconsistency in the AIP

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1171]
**Expected behaviour**

Files that appear in the AIP, in this case, a preservation derivative, are accounted for in the `fileSec` of the METS. Vice versa, files listed in the deleted `fileGrp` in the `fileSec` are removed from the physical package. 

**Current behaviour**

Per @gehurley's post [here](https://groups.google.com/d/msg/archivematica/RVXbEP7ksog/WW2sSMhtCgAJ). When a rule is disabled after previously normalizing a file. If that file is then partially re-ingested, it isn't removed from the package, but it's presence is removed from the `fileSec`. This can cause problems further down the line. 

**Steps to reproduce**

1. Using [oakland03.zip](https://github.com/archivematica/Issues/files/4452942/oakland03.zip) from our sample-data collection.
2. Create an AIP. Normalizing for preservation. (This will normalize with our default JP2->TIF rule) (`b98667be-2614-410b-9079-41942dbc3b32`)
3. Disable the rule. 
4. Create a partial re-ingest and inspect the AIP contents and the AIP mets. The preservation normalization will be present physically,and no longer listed in the `fileSec`. Other parts of the METS look okay, in that its original object identifier is listed as deleted. 
5. You can observe one impact of the state of the AIP at this point by then trying something like a full-reingest. This should fail at `Assign file UUIDs to objects` with:

```
assignfileuuids_v0.0: INFO      2020-04-08 21:19:05,478  archivematica.mcp.client.assignFileUUID.get_file_info_from_mets:80  Archivematica AIP: reading METS file /var/archivematica/sharedDirectory/currentlyProcessing/gifs-767fe071-d72b-4b4e-a450-dba1b7d8dcf7/metadata/METS.0afd73a1-f97d-41e1-a322-ea06a592cd1e.xml.
assignfileuuids_v0.0: INFO      2020-04-08 21:19:05,515  archivematica.mcp.client.assignFileUUID.get_file_info_from_mets:98  Archivematica AIP: file UUID has not been found in the METS document: objects/oakland03-d0d0848b-2160-4ad9-9588-7019b22f6d36.tif
assignfileuuids_v0.0: INFO      2020-04-08 21:19:05,515  archivematica.mcp.client.assignFileUUID.main:168  Generated UUID for this file: df8fb0af-6959-498b-a9db-513a44eb483c.
'current_path'Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 235, in call
    job.set_status(main(**(args)))
  File "/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 183, in main
    currentlocation=info["current_path"]
KeyError: 'current_path'
```

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.11. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
This is really strange, giving it further thought- because partial reingest is only used for making a DIP, it shouldn't be touching the fileSec at all! The AIP and the preservation derivatives should remain unchanged.

**Comment by ross-spencer** [comment]
These are loosely connected (#1044 might be a an exaggerated version of this).

* https://github.com/archivematica/Issues/issues/1101
* https://github.com/archivematica/Issues/issues/1044

The workflow here is a little naive. We're pretty much just ask Archivematica to perform all the normalization tasks that it did whether during the regular transfer process as we would re-ingest. We've encoded that business rule for full-reingest in the [acceptance-tests](https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/8339c51ed0dd0c27c2c3bd5752c9651c2604cb1d/features/black_box/reingest-aip.feature) and of course partially in the workflow.

#1011 alludes to the potential to consume more information during the workflow to suggest `don't do x, y, z` during partial-reingest which might be one approach if this isn't an anticipated use-case for partial-reingest as well.

The issue with the logic so-far in this problem seems to be that the deletion and creation of a new preservation derivative is assumed by the workflow and microservices and so the METS is updated but the object-deletion isn't fully-completed. It makes sense this would happen during full-reingest as well, and so I've just tested that and it does seem to be the case. I've updated the ticket name to make it clear that is the case.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
