### ISSUE TITLE
Problem: Assign file UUIDs to objects fails with unicode accession no.

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1183]
**Expected behaviour**

All Unicode input during transfer initiation, i.e. transfer name, accession no. accession system ID is handled, e.g. validated and rejected, or accepted, and microservices pass.

**Current behaviour**

Create a transfer with an ASCII compatible transfer name, and a unicode accession no. It will fail when Assign file UUIDs to objects runs. 

_Transfer name:_ latin-english
_Accession no._ Français

![image](https://user-images.githubusercontent.com/1880412/79904544-cccc2580-83e2-11ea-8230-bdf5621684bf.png)

The stack trace is as follows:
```
assignfileuuids_v0.0: INFO      2020-04-21 19:15:23,978  archivematica.mcp.client.assignFileUUID.main:168  Generated UUID for this file: 06a51a01-2009-43ff-85af-2ec7aacc3f0f.
'ascii' codec can't encode character u'\xe7' in position 4: ordinal not in range(128)Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 235, in call
    job.set_status(main(**(args)))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 176, in main
    sourceType=event_type,
  File "/usr/lib/archivematica/archivematicaCommon/fileOperations.py", line 111, in addFileToTransfer
    addAccessionEvent(fileUUID, transferUUID, date)
  File "/usr/lib/archivematica/archivematicaCommon/fileOperations.py", line 119, in addAccessionEvent
    transfer.accessionid
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 4: ordinal not in range(128)
```
I haven't investigated why accession number is influencing this microservice. 

**Steps to reproduce**

As above.

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.11 sandbox. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
