### ISSUE TITLE
Problem: Tagging a backlog transfer to create a SIP with a non-ASCII Unicode string causes SIP creation to spin without doing anything

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1222]
**Expected behaviour**

Creating tags during SIP arrangement in Archivematica can be done with the arbitrary range of strings it allows in the appraisal tab. Alternatively, more feedback could be given to the user and is more graceful. 

**Current behaviour**

Tagging a backlog transfer to create a SIP with a non-ASCII string causes SIP creation to spin without doing anything. Technical term™ 

In reality for different strings we see different errors in the archivematica-dashboard logs.

For the tag `Français`: 
```
archivematica-dashboard_1        | ERROR     2020-06-02 13:35:01  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /filesystem/create_directory_within_arrange/
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
archivematica-dashboard_1        |     response = get_response(request)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
archivematica-dashboard_1        |     response = self.process_exception_by_middleware(e, request)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
archivematica-dashboard_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 630, in create_directory_within_arrange
archivematica-dashboard_1        |     paths = list(map(b64decode_string, request.POST.getlist("paths[]", [])))
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/archivematicaFunctions.py", line 129, in b64decode_string
archivematica-dashboard_1        |     return base64.b64decode(data.encode("utf8")).decode("utf8")
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
archivematica-dashboard_1        |     return codecs.utf_8_decode(input, errors, True)
archivematica-dashboard_1        | UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 13: invalid continuation byte
```

For another Unicode string: `™`
```
archivematica-dashboard_1        | ERROR     2020-06-02 13:41:19  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /filesystem/copy_from_arrange/
archivematica-dashboard_1        | Traceback (most recent call last):
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
archivematica-dashboard_1        |     response = get_response(request)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
archivematica-dashboard_1        |     response = self.process_exception_by_middleware(e, request)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
archivematica-dashboard_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 483, in copy_from_arrange_to_completed
archivematica-dashboard_1        |     filepath, sip_uuid, sip_name
archivematica-dashboard_1        |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 578, in copy_from_arrange_to_completed_common
archivematica-dashboard_1        |     error = _create_arranged_sip(staging_sip_path, files, sip_uuid)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/filesystem_ajax/views.py", line 459, in _create_arranged_sip
archivematica-dashboard_1        |     f.writelines(log)
archivematica-dashboard_1        | TypeError: writelines() argument must be a sequence of strings
```

**Steps to reproduce**

1. Create a transfer and send it to Backlog.
2. Retrieve a SIP from backlog and proceed to tag it with `Français`.
3. Navigate to arrangement and select tag, and create SIP. 
4. The loading spinner will continue ad infinitum and no SIP will be created. The logging above will be seen in the Dashboard.

![image](https://user-images.githubusercontent.com/1880412/83527363-b15e3b00-a4b5-11ea-98d6-8ef6cfd740fe.png)

Repeat the steps with other valid (but less useful Unicode, e.g.™  and the second error will appear in the logging as well. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica `qa/1.x` 

Possibly/loosely related: https://github.com/archivematica/Issues/issues/337 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
