### ISSUE TITLE
Problem: Downloading package from Storage Service sometimes fails with unhelpful 500 error

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1244]
**Expected behaviour**

Downloading a package from the Storage Service (either via the `/api/v2/file/<UUID>/download/` API endpoint or by clicking "Download" in row describing a package in the Packages tab) works.

**Current behaviour**

Sometimes the Storage Service returns a 500 server error rather than downloading the package.

Here is a sample error message from the Storage Service logs when this happens (reformatted slightly for readability):

```
<response>
<error_message>
Cannot decrypt file at /var/archivematica/storage_service/originals/backlog_big_bois-5afa040b-50e9-4ba3-8c26-d7da5d297ad7; no such file.
</error_message>
<traceback>
Traceback (most recent call last):

File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper response = callback(request, *args, **kwargs)

File "/src/storage_service/locations/api/resources.py", line 139, in wrapper result = func(resource, request, bundle, **kwargs)

File "/src/storage_service/locations/api/resources.py", line 1350, in download_request full_path = package.get_download_path(lockss_au_number)

File "/src/storage_service/locations/models/package.py", line 284, in get_download_path full_path = self.fetch_local_path()

File "/src/storage_service/locations/models/package.py", line 342, in fetch_local_path destination_space=ss_internal.space,

File "/src/storage_service/locations/models/space.py", line 362, in move_to_storage_service source_path, destination_path, destination_space, *args, **kwargs

File "/src/storage_service/locations/models/gpg.py", line 103, in move_to_storage_service _gpg_decrypt(dst_path)

File "/src/storage_service/locations/models/gpg.py", line 377, in _gpg_decrypt raise GPGException(fail_msg) GPGException: Cannot decrypt file at /var/archivematica/storage_service/originals/backlog_big_bois-5afa040b-50e9-4ba3-8c26-d7da5d297ad7; no such file.
</traceback>
</response>
```

The issue seems to happen sometimes when a package is already present in the Storage Service's internal location (`/var/archivematica/storage_service/` by default). I think what's happening is that `self.space.move_rsync` [in the gpg.py model's `move_to_storage_service` method](https://github.com/artefactual/archivematica-storage-service/blob/2ae1a672ee39141581df058848a9cf14015684ca/storage_service/locations/models/gpg.py#L102) sometimes writes a package into itself, probably because the way rsync handles a destination directory that already exists leads it to attempt to write a duplicate copy of a package into itself.

So for example, with the package shown in the error message above, when I look in the filesystem at `/var/archivematica/storage_service/originals`, I see a `backlog_big_bois-5afa040b-50e9-4ba3-8c26-d7da5d297ad7` directory that appears to be a valid bag, except that it also has another `backlog_big_bois-5afa040b-50e9-4ba3-8c26-d7da5d297ad7` directory written just one subdirectory down (at the same level as the `bag-info.txt` file).

My theory is that this happens when a package is requested for download while a current download request is still processing, but I wasn't able to reliably verify that with the time I had. I ran into this issue specifically when downloading Transfers, but it may be an issue with other package types as well.

When this issue does happen, emptying the Storage Service internal location (e.g. with `rm -rf /var/archivematica/storage_service/originals/*`) resolves the issue, at least temporarily.

**Steps to reproduce**

See above - I haven't been able to reliably reproduce this issue, but the first time it happened was when I kicked off a reindexing task that involved downloading packages from the Storage Service while a Storage Service web app download request was still pending.

**Your environment (version of Archivematica, operating system, other relevant details)**

Storage Service `qa/0.x` as of commit https://github.com/artefactual/archivematica-storage-service/commit/2ae1a672ee39141581df058848a9cf14015684ca

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
This appears to be the same bug that occasionally causes 404 response codes when downloading individual files from an AIP, as described in https://github.com/archivematica/Issues/issues/1333.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
