### ISSUE TITLE
Problem: Can't create a SIP in Appraisal tab from transfers in an encrypted Transfer Backlog location.

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1245]
**Expected behaviour**

I can create a SIP from files in transfers stored in an encrypted Transfer Backlog location.

**Current behaviour**

Create SIP doesn't work when files in the SIP come from transfers in an encrypted Transfer Backlog location.

Here is a screenshot from my test:

![image](https://user-images.githubusercontent.com/6758804/86048726-02167480-ba1f-11ea-8d66-8bb9327605d2.png)

Dashboard log:
```
archivematica-dashboard_1        | WARNING   2020-06-29 19:38:31  archivematica.common:storageService:copy_files:267:  Unable to move files with {'files': [{'source': u'originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/Nemastylis_geminiflora_Flower.PNG', 'destination': u'staging/Test SIP/Nemastylis_geminiflora_Flower.PNG', 'uuid': u'fd0bfb89-50bf-4aa3-a39b-aa5fcd01c610'}, {'source': u'originals//images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/logs/.', 'destination': 'tmp/transfer-27263b2d-0093-44c1-b768-bd4f7e49d7cc/logs/.'}, {'source': u'originals//images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/metadata/.', 'destination': 'tmp/transfer-27263b2d-0093-44c1-b768-bd4f7e49d7cc/metadata/.'}, {'source': u'originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/lion.svg', 'destination': u'staging/Test SIP/lion.svg', 'uuid': u'a55d53e4-8184-4332-b879-e87f95fa47b4'}], 'pipeline': u'/api/v2/pipeline/1d5b471a-277f-43c2-9c57-169a0a1c0a93/', 'origin_location': u'/api/v2/location/35c2305f-88ba-433c-b54f-09e33d5eafad/'} because 500 Server Error: Internal Server Error for url: http://archivematica-storage-service:8000/api/v2/location/1150c12a-e2a7-4038-bde1-d5805c28c6b3/
```

Storage Service log:
```
archivematica-storage-service_1  | DEBUG     2020-06-29 12:38:31  locations.models.space:space:move_to_storage_service:344:  TO: src: var/archivematica/sharedDirectory/www/AIPsStore/encryptedTransferBacklog/originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/Nemastylis_geminiflora_Flower.PNG
archivematica-storage-service_1  | DEBUG     2020-06-29 12:38:31  locations.models.space:space:move_to_storage_service:345:  TO: dst: var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG
archivematica-storage-service_1  | DEBUG     2020-06-29 12:38:31  locations.models.space:space:move_to_storage_service:346:  TO: staging: /var/archivematica/storage_service
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.gpg:gpg:move_to_storage_service:94:  GPG ``move_to_storage_service``
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.gpg:gpg:move_to_storage_service:95:  GPG move_to_storage_service encrypted src_path: /var/archivematica/sharedDirectory/www/AIPsStore/encryptedTransferBacklog/originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/Nemastylis_geminiflora_Flower.PNG
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.gpg:gpg:move_to_storage_service:96:  GPG move_to_storage_service encrypted dst_path: /var/archivematica/storage_service/var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.space:space:move_rsync:550:  Moving from /var/archivematica/sharedDirectory/www/AIPsStore/encryptedTransferBacklog/originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/Nemastylis_geminiflora_Flower.PNG to /var/archivematica/storage_service/var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.space:space:move_rsync:592:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/var/archivematica/sharedDirectory/www/AIPsStore/encryptedTransferBacklog/originals/images_test-27263b2d-0093-44c1-b768-bd4f7e49d7cc/data/objects/Nemastylis_geminiflora_Flower.PNG', '/var/archivematica/storage_service/var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG']
archivematica-storage-service_1  | ERROR     2020-06-29 12:38:31  gnupg:gnupg:_copy_data:162:  Error sending data
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/gnupg.py", line 156, in _copy_data
archivematica-storage-service_1  |     outstream.write(data)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 148, in write
archivematica-storage-service_1  |     ret = BufferedWriter.write(self, b)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/gevent/_fileobjectposix.py", line 136, in write
archivematica-storage-service_1  |     return _write(self._fileno, b)
archivematica-storage-service_1  | OSError: [Errno 32] Broken pipe
archivematica-storage-service_1  | INFO      2020-06-29 12:38:31  locations.models.gpg:gpg:_gpg_decrypt:391:  Failed to decrypt /var/archivematica/storage_service/var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG. Reason: no data was provided
archivematica-storage-service_1  | ERROR     2020-06-29 12:38:31  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/location/1150c12a-e2a7-4038-bde1-d5805c28c6b3/
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
archivematica-storage-service_1  |     response = callback(request, *args, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 476, in dispatch_detail
archivematica-storage-service_1  |     return self.dispatch('detail', request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
archivematica-storage-service_1  |     response = method(request, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 618, in post_detail
archivematica-storage-service_1  |     return self._handle_location_file_move(move_files, request, *args, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 565, in _handle_location_file_move
archivematica-storage-service_1  |     return move_files_fn(data["files"], origin_location, destination_location)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 612, in move_files
archivematica-storage-service_1  |     files, origin_location, destination_location
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 492, in _move_files_between_locations
archivematica-storage-service_1  |     destination_space=destination_space,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/space.py", line 362, in move_to_storage_service
archivematica-storage-service_1  |     source_path, destination_path, destination_space, *args, **kwargs
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/gpg.py", line 105, in move_to_storage_service
archivematica-storage-service_1  |     _gpg_decrypt(dst_path)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/gpg.py", line 392, in _gpg_decrypt
archivematica-storage-service_1  |     raise GPGException(fail_msg)
archivematica-storage-service_1  | GPGException: Failed to decrypt /var/archivematica/storage_service/var/archivematica/sharedDirectory/staging/Test SIP/Nemastylis_geminiflora_Flower.PNG. Reason: no data was provided

```

**Steps to reproduce**

* Setup an encrypted Transfer Backlog location
* Create a transfer and store it in the encrypted Transfer Backlog location
* Attempt to create a SIP from files in that transfer

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica `qa/1.x` / Storage Service `qa/0.x`

Based on [this comment from a related issue](https://github.com/archivematica/issues/issues/734#issuecomment-502832051), I think this has been an outstanding issue in Archivematica for a while

**Additional context**

Related issues:
* https://github.com/archivematica/issues/issues/734
* 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
