### ISSUE TITLE
Problem: Cannot rebuild elasticsearch AIP index for large AIPs

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#127]
**Expected behaviour**

Rebuild AIP index from files.

**Current behaviour**

First I got an Out Of Memory issue on python script, but I could fix adding a 32GB swap file. On syslog:

```
Aug 28 21:49:12 localhost kernel: [1765952.672440] Killed process 24766 (python) total-vm:7193716kB, anon-rss:7011228kB, file-rss:2804kB
Aug 28 21:49:12 localhost kernel: [1765952.672397] Out of memory: Kill process 24766 (python) score 761 or sacrifice child
```
The Elasticsearch needed to set `ES_HEAP_SIZE=6g`, but I can see high memory usage on `elasticsearch.log` when processing the large AIP while running `./am rebuild-elasticsearch-aip-index-from-files --delete-all -v3 /storage/aip`:
```
[2018-08-29 12:44:49,518][WARN ][monitor.jvm              ] [Tomazooma] [gc][old][3778][21] duration [13.1s], collections [1]/[13.2s], total [13.1s]/[1.1m], memory [5.8gb]->[4gb]/[5.9gb], all_pools {[young] [2.6mb]->[18.6mb]/[133.1mb]}{[survivor] [16.6mb]->[0b]/[16.6mb]}{[old] [5.8gb]->[4gb]/[5.8gb]}
[2018-08-29 12:47:32,470][WARN ][monitor.jvm              ] [Tomazooma] [gc][old][3927][25] duration [13s], collections [1]/[14s], total [13s]/[1.3m], memory [5.2gb]->[4gb]/[5.9gb], all_pools {[young] [2.1kb]->[5.3mb]/[133.1mb]}{[survivor] [16.6mb]->[0b]/[16.6mb]}{[old] [5.2gb]->[4gb]/[5.8gb]}
[2018-08-29 12:50:30,836][WARN ][monitor.jvm              ] [Tomazooma] [gc][old][4090][29] duration [14.9s], collections [1]/[15.4s], total [14.9s]/[1.5m], memory [5.5gb]->[4gb]/[5.9gb], all_pools {[young] [2.6mb]->[5.3mb]/[133.1mb]}{[survivor] [16.6mb]->[0b]/[16.6mb]}{[old] [5.5gb]->[4gb]/[5.8gb]}
[2018-08-29 12:53:31,765][WARN ][monitor.jvm              ] [Tomazooma] [gc][old][4254][33] duration [16.4s], collections [1]/[17.3s], total [16.4s]/[1.8m], memory [5.3gb]->[4gb]/[5.9gb], all_pools {[young] [2.6mb]->[5.3mb]/[133.1mb]}{[survivor] [16.6mb]->[0b]/[16.6mb]}{[old] [5.3gb]->[4gb]/[5.8gb]}
[2018-08-29 12:56:14,824][WARN ][monitor.jvm              ] [Tomazooma] [gc][old][4404][37] duration [13.1s], collections [1]/[13.1s], total [13.1s]/[2m], memory [5.8gb]->[4.1gb]/[5.9gb], all_pools {[young] [2.6mb]->[7.9mb]/[133.1mb]}{[survivor] [16.6mb]->[0b]/[16.6mb]}{[old] [5.8gb]->[4.1gb]/[5.8gb]}
```

`./am rebuild-elasticsearch-aip-index-from-files --delete-all -v3 /storage/aip` output:

```
No handlers could be found for logger "elasticsearch.trace"
/storage/aip/8dc2/3339/981d/4bcc/9897/6010/e843/bc82/69267893-8dc23339-981d-4bcc-9897-6010e843bc82.7z: 7-Zip
  69267893-8dc23339-981d-4bcc-9897-6010e843bc82/data/METS.8dc23339-981d-4bcc-9897-6010e843bc82.xml  (84978 B)... OK.
Successfully extracted to "/tmp/tmpl9eOo6/69267893-8dc23339-981d-4bcc-9897-6010e843bc82".
/storage/aip/3c12/9b45/976b/43bf/b5ba/1ede/4798/3f19/65576089-3c129b45-976b-43bf-b5ba-1ede47983f19.7z: 7-Zip
  65576089-3c129b45-976b-43bf-b5ba-1ede47983f19/data/METS.3c129b45-976b-43bf-b5ba-1ede47983f19.xml  (2294159 B)... OK.
Successfully extracted to "/tmp/tmpl9eOo6/65576089-3c129b45-976b-43bf-b5ba-1ede47983f19".
/storage/aip/283a/dfe4/afe5/4fbc/a4f2/c9fb/b976/c8f1/64138923-283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1.7z: 7-Zip
  64138923-283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1/data/METS.283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1.xml  (963822 B)... OK.
Successfully extracted to "/tmp/tmpl9eOo6/64138923-283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1".
/storage/aip/49ba/d261/cbdc/413a/aa79/749b/d0c0/08d4/64898680-49bad261-cbdc-413a-aa79-749bd0c008d4.7z: 7-Zip
  64898680-49bad261-cbdc-413a-aa79-749bd0c008d4/data/METS.49bad261-cbdc-413a-aa79-749bd0c008d4.xml  (382973848 B)... OK.
Successfully extracted to "/tmp/tmpl9eOo6/64898680-49bad261-cbdc-413a-aa79-749bd0c008d4".
Rebuilding AIPS index from AIPS in /storage/aip
Processing AIP 8dc23339-981d-4bcc-9897-6010e843bc82
Deleting AIP 8dc23339-981d-4bcc-9897-6010e843bc82 from aips/aip and aips/aipfile.
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpl9eOo6', '/storage/aip/8dc2/3339/981d/4bcc/9897/6010/e843/bc82/69267893-8dc23339-981d-4bcc-9897-6010e843bc82.7z', '69267893-8dc23339-981d-4bcc-9897-6010e843bc82/data/METS.8dc23339-981d-4bcc-9897-6010e843bc82.xml']
Removed FITS output from METS.
Removed FITS output from METS.
Indexed AIP files and corresponding METS XML.
Processing AIP 3c129b45-976b-43bf-b5ba-1ede47983f19
Deleting AIP 3c129b45-976b-43bf-b5ba-1ede47983f19 from aips/aip and aips/aipfile.
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpl9eOo6', '/storage/aip/3c12/9b45/976b/43bf/b5ba/1ede/4798/3f19/65576089-3c129b45-976b-43bf-b5ba-1ede47983f19.7z', '65576089-3c129b45-976b-43bf-b5ba-1ede47983f19/data/METS.3c129b45-976b-43bf-b5ba-1ede47983f19.xml']
Removed FITS output from METS.
Removed FITS output from METS.
Indexed AIP files and corresponding METS XML.
Processing AIP 283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1
Deleting AIP 283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1 from aips/aip and aips/aipfile.
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpl9eOo6', '/storage/aip/283a/dfe4/afe5/4fbc/a4f2/c9fb/b976/c8f1/64138923-283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1.7z', '64138923-283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1/data/METS.283adfe4-afe5-4fbc-a4f2-c9fbb976c8f1.xml']
Removed FITS output from METS.
Removed FITS output from METS.
Indexed AIP files and corresponding METS XML.
Processing AIP 49bad261-cbdc-413a-aa79-749bd0c008d4
Deleting AIP 49bad261-cbdc-413a-aa79-749bd0c008d4 from aips/aip and aips/aipfile.
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpl9eOo6', '/storage/aip/49ba/d261/cbdc/413a/aa79/749b/d0c0/08d4/64898680-49bad261-cbdc-413a-aa79-749bd0c008d4.7z', '64898680-49bad261-cbdc-413a-aa79-749bd0c008d4/data/METS.49bad261-cbdc-413a-aa79-749bd0c008d4.xml']
Removed FITS output from METS.
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
ERROR: error trying to index.
ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 295, in handle
    delete_existing_data=options['delete'],
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 169, in processAIPThenDeleteMETSFile
    size=aip_info[0]['size'],
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 452, in index_aip
    try_to_index(client, aipData, 'aips', 'aip')
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 460, in try_to_index
    return client.index(body=data, index=index, doc_type=doc_type)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 263, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10.0))
```
It failed processing a 17 GBytes AIP with 370 MBytes METS file (UUID 49bad261-cbdc-413a-aa79-749bd0c008d4)

I tried again exporting `ELASTICSEARCH_TIMEOUT=200`, but I got the same timeout error (10s).

**Steps to reproduce**

Rebuilding AIP index from filesystem with large AIPS (17GB), running:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py \
        rebuild_elasticsearch_aip_index_from_files \
            --delete-all -v3 /storage/aips
";
```

(See https://github.com/artefactual/archivematica-docs/blob/1.7/admin-manual/installation-setup/upgrading/upgrading.rst#upgrade-search-indices)

It works fine when indexing small individual AIPs, for example running:

````
./manage.py rebuild_elasticsearch_aip_index_from_files -u bb6228ae-5c9d-4b20-8118-41a17780b538 /storage/aip 
./manage.py rebuild_elasticsearch_aip_index_from_files -u 0eff0172-82eb-46d1-b1e1-9697beed8208 /storage/aip 
./manage.py rebuild_elasticsearch_aip_index_from_files -u 909f20d0-e797-4c91-bc3f-ec8de73eb041 /storage/aip
```

**Your environment (version of Archivematica, OS version, etc)**

AM stable/1.7.x (1de1105c3f74b48f243eb891553ed530536d9e15)
SS stable/0.11.x
OS Ubuntu 14.04.4 LTS
Linux kernel 3.19.0-80-generic
JAVA: java 8 oracle, build 1.8.0_91-b14
RAM: 8 GB
SWAP: 33 GB
Elasticsearch settings: ES_HEAP_SIZE: 6GB , http.max_content_length: 2000mb

**Comment by mamedin** [comment]
I forgot to say that CPU load was 100% for the `Elasticsearch` process, and system was very very slow when rebuilding AIP index.

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/1064

**Comment by sevein** [comment]
This is fixed.
