### ISSUE TITLE
Problem: Store AIP fails with gzipped tar or parallel bzip2 compression in GPG-encrypted AIP Store locations

### ISSUE THREAD

**Issue by tw4l** [archivematica/Issues#1293]
**Expected behaviour**

AIPs are stored succesfully in encrypted AIP Store locations regardless of the type of compression employed.

**Current behaviour**

Gzipped tars and parallel bzip2-compressed AIPs fail at Store AIP when attempting to store in an encrypted AIP storage location (this does not happen with 7z options or uncompressed AIPs, or with any compression type when storing the AIP in an unencrypted location).

Task stderr from the Ingest tab:

```
500 Server Error: Internal Server Error for url: http://archivematica-storage-service:8000/api/v2/file/Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 365, in call
    args.sip_type,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 244, in store_aip
    related_package_uuid,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 80, in _create_file
    agents=get_agents_from_db(uuid),
  File "/src/archivematicaCommon/lib/storageService.py", line 414, in create_file
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://archivematica-storage-service:8000/api/v2/file/
```

Storage Service log output:

```
archivematica-storage-service_1  | ERROR     2020-08-27 09:04:27  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
archivematica-storage-service_1  |     response = callback(request, *args, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
archivematica-storage-service_1  |     return self.dispatch('list', request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
archivematica-storage-service_1  |     response = method(request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1408, in post_list
archivematica-storage-service_1  |     updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 1062, in obj_create
archivematica-storage-service_1  |     self._store_bundle(bundle)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 997, in _store_bundle
archivematica-storage-service_1  |     aip_subtype=aip_subtype,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 822, in store_aip
archivematica-storage-service_1  |     pointer_file, storage_effects
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1295, in create_new_pointer_file_given_storage_effects
archivematica-storage-service_1  |     package_subtype = old_fsentry.mets_div_type
archivematica-storage-service_1  | AttributeError: 'NoneType' object has no attribute 'mets_div_type'
```

**Steps to reproduce**

* Set up an encrypted AIP Store location
* Attempt to store an AIP in the encrypted location with gzipped tar or parallel bzip2 compression options.

**Your environment (version of Archivematica, operating system, other relevant details)**

`qa/1.x` / `qa/0.x` pre-1.12 release

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by tw4l** [comment]
Testing shows identical behaviour and error messages in the Storage Service logs for Archivematica 1.11.2 / Storage Service 0.16.

**Comment by tw4l** [comment]
Possibly related to https://github.com/archivematica/Issues/issues/772?

**Comment by ross-spencer** [comment]
@tw4l after the triage meeting the other day I hoped that i'd have a chance to look at this, and a side-effect of some of my testing today means indeed - i have! 

I am fairly sure the root cause of this is the same as https://github.com/archivematica/Issues/issues/1338 and so I hope resolving one of these issues will resolve the other. 

```diff
diff --git a/pointer-test.xml b/pointer-test-works.xml
index b971918..0014160 100644
--- a/pointer-test.xml
+++ b/pointer-test-works.xml
@@ -166,18 +166,18 @@ Written by Jean-loup Gailly.
   </mets:amdSec>
   <mets:fileSec>
     <mets:fileGrp USE="Archival Information Package">
-      <mets:file ID="file-san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d.tar" GROUPID="Group-fcc955b1-f0ce-4e49-8895-f16946cf029d" ADMID="amdSec_1">
-        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStoreEncrypted/fcc9/55b1/f0ce/4e49/8895/f169/46cf/029d/san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d.tar.gz" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
+      <mets:file ID="file-san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d" GROUPID="Group-fcc955b1-f0ce-4e49-8895-f16946cf029d" ADMID="amdSec_1">
+        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStoreEncrypted/fcc9/55b1/f0ce/4e49/8895/f169/46cf/029d/san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
         <mets:transformFile TRANSFORMTYPE="decompression" TRANSFORMORDER="1" TRANSFORMALGORITHM="tar.gzip"/>
       </mets:file>
     </mets:fileGrp>
   </mets:fileSec>
   <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
-    <mets:div TYPE="Archival Information Package" LABEL="san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d.tar.gz">
-      <mets:fptr FILEID="file-san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d.tar"/>
+    <mets:div TYPE="Archival Information Package" LABEL="san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d">
+      <mets:fptr FILEID="file-san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d"/>
     </mets:div>
   </mets:structMap>
   <mets:structMap ID="structMap_2" LABEL="Normative Directory Structure" TYPE="logical">
-    <mets:div TYPE="Archival Information Package" LABEL="san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d.tar.gz"/>
+    <mets:div TYPE="Archival Information Package" LABEL="san07_7-fcc955b1-f0ce-4e49-8895-f16946cf029d"/>
   </mets:structMap>
 </mets:mets>
```

Test files:

[pointer-tests.zip](https://github.com/archivematica/Issues/files/6072426/pointer-tests.zip)

Test script I largely keep around for `metsrw` testing `python <script-name>.py pointer-works.py`. (`use_mets()` is going to call the first function that the Storage Service wants [prior to the error](https://github.com/artefactual/archivematica-storage-service/blob/63f74d3314e29bd34d2844567047ecd248a5471c/storage_service/locations/models/package.py#L1294)):

Hard-coded to look for `fcc955b1-f0ce-4e49-8895-f16946cf029d` in the test files. 

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function
import argparse
import sys

import lxml

import metsrw


OFFLINE_ERR = (
    "The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not "
    "resolve to a(n) attribute group definition."
)


def validate_mets(mets):
    try:
        is_valid, report = metsrw.xsd_validate(mets.serialize())
        if is_valid is not True:
            print("Validation result. {}".format(is_valid))
            print("Reason: {}".format(report))
        else:
            print("Schema validation via XSD is valid.")
    except lxml.etree.XMLSchemaParseError as err:
        if (OFFLINE_ERR) in str(err):
            print("We're likely offline, so ignoring validation", file=sys.stderr)
        else:
            print(err, file=sys.stderr)


def load_mets(filename):
    try:
        mets = metsrw.METSDocument.fromfile(filename)  # Reads a file
        return mets
    except lxml.etree.XMLSyntaxError as err:
        print("METS {}".format(err), file=sys.stderr)
        sys.exit(1)
    except IOError as err:
        print("File does not exist {}".format(err), file=sys.stderr)
        sys.exit(1)


def use_mets(filename):
    try:
        mets = load_mets(filename[0])
    except IndexError:
        return
    found_file = mets.get_file(file_uuid="fcc955b1-f0ce-4e49-8895-f16946cf029d")
    print(found_file)


def main():
    parser = argparse.ArgumentParser(description="metsrw client to test validation")
    parser.add_argument(
        "mets", metavar="M", type=str, nargs=1, help="a mets file to parse"
    )

    args = parser.parse_args()

    use_mets(args.mets)


if __name__ == "__main__":
    main()
```

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
