### ISSUE TITLE
Problem: awesome-font error in dashboard rpm packages (AM1.12)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1300]
**Expected behaviour**

The `archivematica-dashboard` rpm package should install dashboard without errors

**Current behaviour**

This is the error when creating the static content:

```
Copying '/usr/share/archivematica/dashboard/media/vendor/font-awesome'
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 363, in copy_file
    with source_storage.open(path) as source_file:
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/usr/share/archivematica/dashboard/media/vendor/font-awesome'
``` 

And dashboard GUI returns 500 error.

**Steps to reproduce**

Installing AM1.12 with rpm packages.

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.12 from rpm, CentOS 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
:tada: Issue #1300!! :tada:

**Comment by jens-st** [comment]
I am getting the same error during dashboard package install via apt / apt-get on 18.04 (bionic beaver), it's not just RHEL7.
Apt reports the package to be installed successfully.

**Comment by mamedin** [comment]
Thanks @jens-st , I can confirm it happens when upgrading bionic:

```
Traceback (most recent call last):
  File "/usr/share/archivematica/dashboard/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 363, in copy_file
    with source_storage.open(path) as source_file:
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/usr/share/archivematica/dashboard/media/vendor/font-awesome'
Successfully updated /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python
Successfully updated /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python2
Successfully updated /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python2.7
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
```

Broken symlink: 

```
root@mamedin-am112-deb:~# ls -lh /usr/share/archivematica/dashboard/media/vendor/font-awesome
lrwxrwxrwx 1 root root 43 Dec  9 08:40 /usr/share/archivematica/dashboard/media/vendor/font-awesome -> ../../../frontend/node_modules/font-awesome
```
