### ISSUE TITLE
Problem: AIPs larger than 1 GB cannot be stored in Duracloud

### ISSUE THREAD

**Issue by dcraze** [archivematica/Issues#1314]
**Expected behaviour**
An AIP larger than 1GB is ingested.  At the Store AIP step the SS chunks the AIP into 1GB sections for transfer and storage in Duracloud. The AIP is successfully stored in Duracloud.

**Current behaviour**
For an AIP larger than 1 GB the transfer fails at the Store AIP step and the AIP is not stored

**Steps to reproduce**
Start a transfer with a file greater than 1 GB.  At the Store AIP decision choose the Duracloud AIP Store.  The transfer will fail and give this error detail:

```
500 Server Error: Internal Server Error for url: http://ns560326.ip-54-39-106.net:8000/api/v2/file/Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 365, in call
    args.sip_type,
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 244, in store_aip
    related_package_uuid,
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 80, in _create_file
    agents=get_agents_from_db(uuid),
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 414, in create_file
    response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://ns560326.ip-54-39-106.net:8000/api/v2/file/
```

**Your environment (version of Archivematica, operating system, other relevant details)**
Reproduced in 1.11 and 1.12 on bionic.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Have tested with a 1GB+ AIP and confirmed that 1. it is in fact chunked in Duracloud and 2. can be downloaded in tact via the dashboard.
