### ISSUE TITLE
Deletions for file-type packages (7z, ZIP, tar.bz) do not work with pipeline local filesystem (rsync) 

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1337]
**Expected behaviour**

Deletions should work for all package types. Error messages should be clear and firendly. 

**Current behaviour**

We see the following message when trying to delete an AIP that has been packed in one of the "compression" formats, e.g. 7z, zip.

![image](https://user-images.githubusercontent.com/1880412/103422649-897ca600-4b70-11eb-829d-0631b7a7ab18.png)

On `am111bigserver.qa` I added the SSH key to my own vm and then created a remote pipeline. (NB. not using an rsync daemon). I then successfully stored a 7z package. 

I can see the package successfully stored:
```
[artefactual@analyst-ross-vm AIPstore]$ tree
.
└── ac55
    └── 43a9
        └── f01e
            └── 43a7
                └── 9f0d
                    └── 9796
                        └── ab05
                            └── 88fc
                                └── demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z
```

Trying to delete it gave the html page above. With the stack trace: 
```
INFO      2020-12-31 10:44:51  locations.models.pipeline_local:pipeline_local:delete_path:116:  rsync delete command: ['rsync', '-vv', '--itemize-changes', '--protect-args', '--delete', '--dirs', '/tmp/tmp_dLgSu/', 'artefactual@xx.xx.xx.xx:/home/artefactual/docker-test/AIPstore/ac55/43a9/f01e/43a7/9f0d/9796/ab05/88fc/demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z/']
WARNING   2020-12-31 10:44:53  locations.models.pipeline_local:pipeline_local:delete_path:120:  rsync delete failed: ['rsync', '-vv', '--itemize-changes', '--protect-args', '--delete', '--dirs', '/tmp/tmp_dLgSu/', 'artefactual@xx.xx.xx.xx:/home/artefactual/docker-test/AIPstore/ac55/43a9/f01e/43a7/9f0d/9796/ab05/88fc/demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z/']
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/models/pipeline_local.py", line 118, in delete_path
    subprocess.check_call(command)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/gevent/subprocess.py", line 277, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['rsync', '-vv', '--itemize-changes', '--protect-args', '--delete', '--dirs', '/tmp/tmp_dLgSu/', 'artefactual@xx.xx.xx.xx:/home/artefactual/docker-test/AIPstore/ac55/43a9/f01e/43a7/9f0d/9796/ab05/88fc/demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z/']' returned non-zero exit status 3
ERROR     2020-12-31 10:44:53  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /packages/package_delete_request/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/archivematica/storage-service/locations/views.py", line 215, in package_delete_request
    return _handle_package_request(request, config, "locations:package_delete_request")
  File "/usr/lib/archivematica/storage-service/locations/views.py", line 248, in _handle_package_request
    success, err_msg = config.execution_logic(event.package)
  File "/usr/lib/archivematica/storage-service/locations/views.py", line 205, in execution_logic
    return package.delete_from_storage()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 2019, in delete_from_storage
    space.delete_path(self.full_path)
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 296, in delete_path
    return self.get_child_space().delete_path(delete_path, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/models/pipeline_local.py", line 118, in delete_path
    subprocess.check_call(command)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/gevent/subprocess.py", line 277, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['rsync', '-vv', '--itemize-changes', '--protect-args', '--delete', '--dirs', '/tmp/tmp_dLgSu/', 'artefactual@xx.xx.xx.xx:/home/artefactual/docker-test/AIPstore/ac55/43a9/f01e/43a7/9f0d/9796/ab05/88fc/demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z/']' returned non-zero exit status 3
```

First thing to notice is we terminate the AIP path with a slash which might be a clue as to what we're not doing here. 

The issue becomes clearer when we run the command outside of Archivematica using rsync locally and we see the method we're using is not valid for overwriting files (note this was for a different package):
```
rsync -vv --itemize-changes --protect-args --delete --dirs /tmp/empty artefactual@xx.xx.xx.xx:/home/artefactual/docker-test/AIPstore/7934/8c0b/c12e/44cc/88cd/d202/b331/f8ad/rsync3-79348c0b-c12e-44cc-88cd-d202b331f8ad.7z
opening connection using: ssh -l artefactual xx.xx.xx.xx rsync --server -svvde.LsfxC  (7 args)
protected args: --no-r "--log-format=%i" --delete . /home/artefactual/docker-test/AIPstore/7934/8c0b/c12e/44cc/88cd/d202/b331/f8ad/rsync3-79348c0b-c12e-44cc-88cd-d202b331f8ad.7z  (5 args)
building file list ... done
ERROR: cannot overwrite non-directory with a directory
rsync error: errors selecting input/output files, dirs (code 3) at main.c(629) [Receiver=3.1.2]
```

Specifically: `ERROR: cannot overwrite non-directory with a directory` 

**Steps to reproduce**

As above. 

Trying the same for unpacked bag types works and you can see the remnants of the directory structure next to the 7z which wasn't deleted:
```
[artefactual@analyst-ross-vm AIPstore]$ tree
.
├── ac55
│   └── 43a9
│       └── f01e
│           └── 43a7
│               └── 9f0d
│                   └── 9796
│                       └── ab05
│                           └── 88fc
│                               └── demo_csv-ac5543a9-f01e-43a7-9f0d-9796ab0588fc.7z
└── fa6a
    └── d9e2
        └── 8917
            └── 4cef
                └── abd1
                    └── 9ee2
                        └── 87a9
                            └── fd78
                                └── demo_csv_dir-fa6ad9e2-8917-4cef-abd1-9ee287a9fd78
```

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica 1.12 on Docker, and CentOS. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
