### ISSUE TITLE
Problem: Replication and storage failure for tar.gz or tar.bz packages because pointer file is written "incorrectly" meaning it can't be read correctly by mets-reader-writer (metsrw)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1338]
**Expected behaviour**

Replication works for all Archivematica package types. 

**Current behaviour**

Replication will fail for `tar.gz` or `tar.bz` because the pointer file is written incorrectly meaning it can't be read correctly for the data needed to then create a replica. 

That is:

1. Pointer file for the primary object is written.
2. Storage service then tries to read the source pointer for some information and it receives a `Nonetype` object: `master_ptr_aip_fsentry = master_ptr.get_file(file_uuid=self.uuid)`. At which point, an `AttributeError` in the logs will throw off the rest of the transfer process and part of the storage process. 

The trickle down effects of the failure are also as follows:

 * Package is uploaded to storage service with status `UPLOADED` but is not indexed by Elasticsearch. 
 * Replicas remain staged. I don't believe there's a way to trigger a `staging -> location` action? 

**Steps to reproduce**

1. Create a replica location in the storage service and enable it for a location. I was testing with S3. 
2. Switch your package types to one of `tar.gz` or `tar.bz`.
3. Create a new transfer and it should fail at the end of the ingest phase. 
4. You can inspect the storage service logs for fun and you should see:
```log
archivematica-storage-service_1  | ERROR     2021-01-04 22:26:20  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
archivematica-storage-service_1  |     response = callback(request, *args, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
archivematica-storage-service_1  |     return self.dispatch('list', request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
archivematica-storage-service_1  |     response = method(request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1408, in post_list
archivematica-storage-service_1  |     updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 1062, in obj_create
archivematica-storage-service_1  |     self._store_bundle(bundle)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 997, in _store_bundle
archivematica-storage-service_1  |     aip_subtype=aip_subtype,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 833, in store_aip
archivematica-storage-service_1  |     self.create_replicas()
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1483, in create_replicas
archivematica-storage-service_1  |     self.replicate(replicator_loc)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 654, in replicate
archivematica-storage-service_1  |     master_premis_object = master_ptr_aip_fsentry.get_premis_objects()[0]
archivematica-storage-service_1  | AttributeError: 'NoneType' object has no attribute 'get_premis_objects'
```

**Your environment (version of Archivematica, operating system, other relevant details)**

Docker running AM `qa/1.x` and storage service `qa/1.12` roughly around the same spec as AM `1.12.1`. 

**Additional context**

I was able to correct the behavior against a standalone pointer file and mets-reader-writer, and the diff is as follows (good pointer in the green):

![pointer](https://i.pinimg.com/originals/73/0d/d8/730dd8a5455767cb09560286f2522899.gif)

```diff
diff --git a/incorrect b/correct
index 9a96c11..f71c04b 100644
--- a/incorrect
+++ b/correct
@@ -1,10 +1,10 @@
   <mets:fileSec>
     <mets:fileGrp USE="Archival Information Package">
-      <mets:file ID="file-gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1.tar"
+      <mets:file ID="file-gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1"
         GROUPID="Group-d4b94845-47fd-4d5f-b678-6dd88f0caea1"
         ADMID="amdSec_1"
       >
-        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStore/d4b9/4845/47fd/4d5f/b678/6dd8/8f0c/aea1/gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1.tar.gz"
+        <mets:FLocat xlink:href="/var/archivematica/sharedDirectory/www/AIPsStore/d4b9/4845/47fd/4d5f/b678/6dd8/8f0c/aea1/gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1"
           LOCTYPE="OTHER"
           OTHERLOCTYPE="SYSTEM"
         />
@@ -14,7 +14,7 @@
   </mets:fileSec>
   <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
     <mets:div TYPE="Archival Information Package" LABEL="gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1.tar.gz">
-      <mets:fptr FILEID="file-gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1.tar"/>
+      <mets:fptr FILEID="file-gztar-d4b94845-47fd-4d5f-b678-6dd88f0caea1"/>
     </mets:div>
   </mets:structMap>
   <mets:structMap ID="structMap_2" LABEL="Normative Directory Structure" TYPE="logical">
```

So that looks like something to do with file-extension handling during creation in the storage service. It's not clear on first look whether or not `mets-reader-writer` could just be more [robust](https://en.wikipedia.org/wiki/Robustness_principle) here too. If replication were handled in a separate microservice too, it wouldn't need to fail the storage of the primary AIP and replicas could be created later via management command. NB. Users might want to try reindexing the actually stored package, but there may be API effects around the transfer itself which may cause problems with users managing Archivematica automatically, e.g. via automation tools or similar. 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/1293

**Comment by tw4l** [comment]
A user on the Google Group user forum reports hitting this issue in the wild with replicated AIPs compressed with Gzipped tar compression: https://groups.google.com/g/archivematica/c/v47PwUyK_PQ

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
