### ISSUE TITLE
Problem: Python Queue.py "raise Full" during ingest in AM 1.11.2

### ISSUE THREAD

**Issue by arthytrip** [archivematica/Issues#1428]
**Expected behaviour**
Since Archivematica is able to process several packages at the same time, the totally sequential way of using the API, eg.
package + transfer/status (until "complete") + ingest/status (until "complete") => (next) package ...
it should be avoidable by proper management of the queues by Archivematica.

For example, you should be able to feed Archivematica using the "Package" API and be able to launch a new Transfer each time the "transfer/status" API returns the "COMPLETE" value for the previous Transfer (therefore without waiting for the declaration "COMPLETE" by the corresponding "ingest/status").
Since the Transfers may involve sets of files of very different sizes, Archivematica is expected to manage subsequent Ingest queues correctly, managing any accumulations in the Ingest queue and, if necessary, also managing any "queue full" situations.

**Current behaviour**
If you use the example described above (not using "ingest/status" before to start a new Transfer), Archivematica crashes in a pseudo-random way, depending on the combination of launch frequency vs size, number and types of files in the packages.
The MCP Server stop can be partially overcome by relaunching the MCP Server service but there is no guarantee of recovery of all processes already queued.
In any case the error is always the same and concerns the failure to handle an error generated by the Python library "Queue.py", almost always during the job "Check if AIP is a file or directory", this is an example...

```
ERROR     2021-02-19 09:21:52  concurrent.futures:_base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f7d66d40590 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/usr/lib/archivematica/MCPServer/server/queues.py", line 216, in _package_completed_callback
    self.queue_next_job()
  File "/usr/lib/archivematica/MCPServer/server/queues.py", line 316, in queue_next_job
    self.job_queue.put_nowait(job)
  File "/usr/lib64/python2.7/Queue.py", line 148, in put_nowait
    return self.put(item, False)
  File "/usr/lib64/python2.7/Queue.py", line 123, in put
    raise Full
Full
INFO      2021-02-19 09:21:52  archivematica.mcp.server.jobs.client:client:run:113:  Running Check if AIP is a file or directory (package {omissis})
DEBUG     2021-02-19 09:21:52  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:221:  Submitted gearman job 93b29cf9-21b3-4846-a4be-bf6b4b8b4f6d (test_v0.0)
DEBUG     2021-02-19 09:21:52  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:265:  Task {omissis} finished! Result COMPLETE - 0
```

**Steps to reproduce**
To reproduce the error:
1. Prepare about twenty Transfer packages with variable dimensions (it depends a lot on the sizing and performance of the system).
2. Use the API "package", or "transfer/start_transfer", and sequentially launch the Transfers before the corresponding Ingests are finished.
3. MCP Server will hang with the error shown above and raised by the Python Queue.py library.

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.11.2
RHEL 7 or CentOS 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sevein** [comment]
@arthytrip, have you been able to reproduce this issue in Archivematica 1.12 or 1.13? There have been no major changes in the queue manager, but 1.12 included a fix for https://github.com/archivematica/Issues/issues/1306 that could be related.
