### ISSUE TITLE
Problem: GPG encrypted uncompressed packages are failing reingest

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#1431]
**Expected behaviour**

Reingest works for all package types. 

**Current behaviour**

GPG uncompressed packages cannot be reingested. They are failing at `Store AIP` with the following error seen in the storage service logs:

```log
archivematica-storage-service_1  | ERROR: destination must be a directory when copying more than 1 file
archivematica-storage-service_1  | rsync error: errors selecting input/output files, dirs (code 3) at main.c(641) [Receiver=3.1.2]
archivematica-storage-service_1  | 
archivematica-storage-service_1  | ERROR     2021-03-08 06:29:54  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/5f24ca7e-a598-4056-b8ea-a68b5c80a545/
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
archivematica-storage-service_1  |     response = callback(request, *args, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 476, in dispatch_detail
archivematica-storage-service_1  |     return self.dispatch('detail', request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
archivematica-storage-service_1  |     response = method(request, **kwargs)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1500, in put_detail
archivematica-storage-service_1  |     updated_bundle = self.obj_update(bundle=bundle, **self.remove_api_resource_names(kwargs))
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 1088, in obj_update
archivematica-storage-service_1  |     bundle = self.obj_update_hook(bundle, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 1136, in obj_update_hook
archivematica-storage-service_1  |     aip_subtype=aip_subtype,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 2529, in finish_reingest
archivematica-storage-service_1  |     old_aip_internal_path,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 2740, in _move_rein_updated_to_final_dest
archivematica-storage-service_1  |     package=self,
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/space.py", line 430, in move_from_storage_service
archivematica-storage-service_1  |     source_path, destination_path, *args, **kwargs
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/gpg.py", line 152, in move_from_storage_service
archivematica-storage-service_1  |     self.space.move_rsync(src_path, dst_path, try_mv_local=True)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/space.py", line 601, in move_rsync
archivematica-storage-service_1  |     raise StorageException(s)
archivematica-storage-service_1  | StorageException: Rsync failed with status 3: sending incremental file list
archivematica-storage-service_1  | ERROR: destination must be a directory when copying more than 1 file
archivematica-storage-service_1  | rsync error: errors selecting input/output files, dirs (code 3) at main.c(641) [Receiver=3.1.2]
```

**Steps to reproduce**

Setup a GPG encrypted space. Create an uncompressed AIP and store it in a GPG encrypted location. 

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica `1.x` (`4e339e`) and Storage Service `0.x` (`1726937`) - leading up to 1.13. On Docker-Compose.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
