### ISSUE TITLE
Problem: rebuild_transfer_backlog management command fails (local variable 'modification_date' referenced before assignment)

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#1457]
**Expected behaviour**
rebuild_transfer_backlog management command should complete without errors

**Current behaviour**
rebuild_transfer_backlog fails

**Steps to reproduce**
Ran the management command as explained in the docs:

```
$ sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_transfer_backlog --from-storage-service
";
...
+ cd /usr/share/archivematica/dashboard
+ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_transfer_backlog --from-storage-service
...
Rebuilding "transfers" index from packages in Storage Service.
Connected to Elasticsearch node HlERbyV (v6.5.4).
Deleting all transfers and transfer files in the "transfers" and "transferfiles" indexes...
Creating indexes...
...
Importing transfer ac7192a3-d6b8-4db9-95a8-e4a6ce2be898 from temporarily downloaded copy.
Importing transfer 357497e6-4eaa-4689-9e30-dfbaae391a6a from temporarily downloaded copy.
Importing transfer 7e0fb6a6-29b6-40ef-bc2f-e5b83c94783b from temporarily downloaded copy.
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 141, in handle
    self.populate_data_from_storage_service(es_client, pipeline_uuid)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 267, in populate_data_from_storage_service
    transfer["size"],
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 472, in _import_self_describing_transfer
    printfn=_elasticsearch_noop_printfn,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 750, in index_transfer_and_files
    printfn=printfn,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 851, in _index_transfer_files
    "modification_date": modification_date,
UnboundLocalError: local variable 'modification_date' referenced before assignment
```

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.12

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by hakamine** [comment]
I think the relevant part of the code may be this conditional in https://github.com/artefactual/archivematica/blob/stable/1.12.x/src/archivematicaCommon/lib/elasticSearchFunctions.py#L822-L823 

```
if f.modificationtime is not None:
    modification_date = f.modificationtime.strftime("%Y-%m-%d")
```
Hopefully assigning modification_date to an empty string when the condition is not met will prevent the exception to occur. I will try this and will create a PR in case this works
