### ISSUE TITLE
Problem: Store AIP microservice fails when the SIP has dots in its name if a Write-Only Replica Staging replicator is enabled

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1461]
**Expected behaviour**

The sip is stored without problems

**Current behaviour**

The "store sip" microservice fails, and the log shows

```
ERROR     2021-06-17 16:44:48  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 499, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 1408, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1062, in obj_create
    self._store_bundle(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 997, in _store_bundle
    aip_subtype=aip_subtype,
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 843, in store_aip
    self.create_replicas()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1496, in create_replicas
    self.replicate(replicator_loc)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 708, in replicate
    package=replica_package,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 432, in move_from_storage_service
    source_path, destination_path, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/replica_staging.py", line 61, in move_from_storage_service
    return self._store_tar_replica(src_path, dest_path, package)
  File "/usr/lib/archivematica/storage-service/locations/models/replica_staging.py", line 97, in _store_tar_replica
    os.rmdir(dest_path)
OSError: [Errno 2] No such file or directory: '/aip-002/a.b-55aa6454-84f7-404c-9ecf-79ac802659e0'
```

**Steps to reproduce**

Run a transfer with a tranfer name with dots 

**Your environment (version of Archivematica, operating system, other relevant details)**

SS branch: /dev/offline-replica-client-qa
---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment]
This is happening after enabling and configuring the writeonly replication space

**Comment by sromkey** [comment]
Tested by ensuring a replication space existed then storing an AIP with dots in the name.
