### ISSUE TITLE
Problem: Calculating disk usage produces internal server error

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1468]
**Expected behaviour**
Disk usage should be calculated via Administration/Processing Storage Usage. Click "Calculate disk usage."

**Current behaviour**
Produces an internal server error.

```
ERROR     2021-06-25 17:52:11  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /administration/usage/
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/dashboard/src/components/administration/views.py", line 383, in _usage_get_directory_used_bytes
    ["du", "--one-file-system", "--bytes", "--summarize", path]
  File "/usr/share/archivematica/virtualenvs/archivematica/lib64/python3.6/site-packages/gevent/subprocess.py", line 349, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['du', '--one-file-system', '--bytes', '--summarize', '/']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/administration/views.py", line 255, in usage
    "used": _usage_get_directory_used_bytes(root_path),
  File "/opt/archivematica/archivematica/src/dashboard/src/components/administration/views.py", line 397, in _usage_get_directory_used_bytes
    byte_count = int(err.output.split("\t")[0])
TypeError: a bytes-like object is required, not 'str'
```

**Steps to reproduce**
See above

**Your environment (version of Archivematica, operating system, other relevant details)**
Tested on Centos and Ubuntu during 1.13 release testing 

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Fixed!
