### ISSUE TITLE
Problem: AIC creation failing

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#1469]
**Expected behaviour**
After searching for AIPs and clicking "Create AIC," the AIC should be successfully created.

**Current behaviour**
It gets as far as the Ingest tab and fails at Create AIC METS file with

```
write() argument must be str, not bytesTraceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 113, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/create_aic_mets.py", line 169, in call
    create_aic_mets(args.aic_uuid, args.aic_dir, job)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/create_aic_mets.py", line 157, in create_aic_mets
    create_mets_file(aic, aips, job)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/create_aic_mets.py", line 129, in create_mets_file
    mets, pretty_print=True, xml_declaration=True, encoding="utf-8"
TypeError: write() argument must be str, not bytes
```

**Steps to reproduce**
- perform a search in the Archival Storage tab
- Click on Create AIC
- Fill out a few things in the metadata entry form including the title
- Save and watch for the error in Ingest.

**Your environment (version of Archivematica, operating system, other relevant details)**
Tested on Centos during 1.13 release testing

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Re-tested, fixed now, thanks!
