### ISSUE TITLE
Problem: TestTransfers/files_with_various_encodings fails

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1471]
**Expected behaviour**

Transfer should finish successfully.

**Current behaviour**

When the `TestTransfers/files_with_various_encodings` is used, the MCPServer raises the following error and the transfer seems stuck in the dashboard UI:

```
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.packages:packages:_start_package_transfer_with_auto_approval:433:  Package efa13338-e187-4ffa-84f7-c51b2e561f5c: copying chosen contents from transfer sources (from=3469d243-0d6c-4d79-9cf8-7c882ccfbb3f:/home/artefactual/archivematica-sampledata/TestTransfers/files_with_various_encodings/., to=tmp/tmp82oshwa3/jas-14.2)
DEBUG     2021-06-25 18:07:16  archivematica.common:storageService:get_location:200:  Storage locations returned: [{'description': None, 'enabled': True, 'path': '/var/archivematica/sharedDirectory', 'pipeline': ['/api/v2/pipeline/a55a9f9d-c405-4871-8850-d3ea848f3bbc/'], 'purpose': 'CP', 'quota': None, 'relative_path': 'var/archivematica/sharedDirectory/', 'resource_uri': '/api/v2/location/0dc50e53-ab7f-4217-a0aa-bdee2e1c988e/', 'space': '/api/v2/space/10f3b7b7-5390-49fd-a8a4-cf0d6e388892/', 'used': 0, 'uuid': '0dc50e53-ab7f-4217-a0aa-bdee2e1c988e'}]
DEBUG     2021-06-25 18:07:16  archivematica.common:storageService:get_location:200:  Storage locations returned: [{'description': 'Default transfer source', 'enabled': True, 'path': '/home', 'pipeline': ['/api/v2/pipeline/a55a9f9d-c405-4871-8850-d3ea848f3bbc/'], 'purpose': 'TS', 'quota': None, 'relative_path': 'home', 'resource_uri': '/api/v2/location/3469d243-0d6c-4d79-9cf8-7c882ccfbb3f/', 'space': '/api/v2/space/10f3b7b7-5390-49fd-a8a4-cf0d6e388892/', 'used': 0, 'uuid': '3469d243-0d6c-4d79-9cf8-7c882ccfbb3f'}]
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.packages:packages:_copy_from_transfer_sources:256:  source: artefactual/archivematica-sampledata/TestTransfers/files_with_various_encodings/., destination: /var/archivematica/sharedDirectory/tmp/tmp82oshwa3/jas-14.2/.
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.packages:packages:_start_package_transfer_with_auto_approval:437:  Package efa13338-e187-4ffa-84f7-c51b2e561f5c: moving package to processing directory
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.packages:packages:_start_package_transfer_with_auto_approval:442:  Package efa13338-e187-4ffa-84f7-c51b2e561f5c: starting workflow processing
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.jobs.chain:chain:__init__:101:  Creating JobChain 6953950b-c101-4f4c-a0c3-0cd0684afe5e for package efa13338-e187-4ffa-84f7-c51b2e561f5c (initial link 045c43ae-d6cf-44f7-97d6-c8a602748565)
INFO      2021-06-25 18:07:16  archivematica.mcp.server.jobs.client:client:run:111:  Running Set transfer type: Standard (package efa13338-e187-4ffa-84f7-c51b2e561f5c)
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:219:  Submitted gearman job b9b524de-ea1c-4565-8ea9-7342b8d652e5 (archivematicasettransfertype_v0.0)
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:263:  Task 4538cf68-de33-4f9d-8b08-ebff1595b330 finished! Result COMPLETE - 0
INFO      2021-06-25 18:07:16  archivematica.mcp.server.jobs.client:client:run:111:  Running Remove hidden files and directories (package efa13338-e187-4ffa-84f7-c51b2e561f5c)
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.jobs.tasks:gearman_backend:submit:219:  Submitted gearman job f06e65fa-f8d8-4af4-9151-829aa1472058 (removehiddenfilesanddirectories_v0.0)
DEBUG     2021-06-25 18:07:16  archivematica.mcp.server.jobs.tasks:gearman_backend:update_task_results:263:  Task f9c0512a-05fa-4d0b-9e88-1585b7960e87 finished! Result COMPLETE - 0
INFO      2021-06-25 18:07:16  archivematica.mcp.server.jobs.client:client:run:111:  Running Remove unneeded files (package efa13338-e187-4ffa-84f7-c51b2e561f5c)
ERROR     2021-06-25 18:07:16  concurrent.futures:_base:_invoke_callbacks:326:  exception calling callback for <Future at 0x7f1e375904e0 state=finished raised UnicodeEncodeError>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/queues.py", line 228, in _job_completed_callback
    next_job = future.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/jobs/client.py", line 126, in run
    self.wait_for_task_results()
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/jobs/client.py", line 147, in wait_for_task_results
    for task in self.task_backend.wait_for_results(self):
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py", line 98, in wait_for_results
    self._submit_batch(job, current_task_batch)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py", line 155, in _submit_batch
    task_batch.submit(self.client, job)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/backends/gearman_backend.py", line 202, in submit
    Task.bulk_log(self.tasks, job)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/server/tasks/task.py", line 72, in bulk_log
    models.Task.objects.bulk_create(model_objects)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/models/query.py", line 440, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 202, in execute
    args = tuple(map(db.literal, args))
  File "/usr/share/archivematica/virtualenvs/archivematica/lib64/python3.6/site-packages/MySQLdb/connections.py", line 260, in literal
    s = self.string_literal(o.encode(self.encoding))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbc' in position 0: surrogates not allowed
```

**Steps to reproduce**

1. Run a transfer using `TestTransfers/files_with_various_encodings` from the `archivematica-sampledata` repository.
2. The transfer will get stuck in the `Microservice: Verify transfer compliance`
3. Look for the traceback above in the logs of the MCPServer 

**Your environment (version of Archivematica, operating system, other relevant details)**

CentOS and Ubuntu 1.13 QA VMs.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
It seems AM 1.12 cannot handle the `TestTransfers/files_with_various_encodings` transfer either. I got the same symptom of the transfer getting stuck in the dashboard UI, but a different traceback in the MCPServer (I named the transfer `mytest`):

```
archivematica-mcp-server_1       | DEBUG    RPCServer-1 2021-06-28 15:07:40 packages:create_package:357:  Transfer object created: 267ec68f-85dc-4f06-9e88-9c88570e5cd2
archivematica-mcp-server_1       | DEBUG    RPCServer-1 2021-06-28 15:07:40 packages:create_package:363:  Package 267ec68f-85dc-4f06-9e88-9c88570e5cd2: starting transfer ((u'mytest', u'standard', u'1f7b6816-2009-4bf2-8f65-bb15fb5a8719:/home/archivematica/archivematica-sampledata/TestTransfers/files_with_various_encodings', u'/var/archivematica/sharedDirectory/tmp/tmpcTvt59'))
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 packages:_start_package_transfer_with_auto_approval:425:  Package 267ec68f-85dc-4f06-9e88-9c88570e5cd2: determined vars transfer_rel=tmp/tmpcTvt59/mytest, filepath=/var/archivematica/sharedDirectory/tmp/tmpcTvt59/mytest, path=1f7b6816-2009-4bf2-8f65-bb15fb5a8719:/home/archivematica/archivematica-sampledata/TestTransfers/files_with_various_encodings/.
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 packages:_start_package_transfer_with_auto_approval:432:  Package 267ec68f-85dc-4f06-9e88-9c88570e5cd2: copying chosen contents from transfer sources (from=1f7b6816-2009-4bf2-8f65-bb15fb5a8719:/home/archivematica/archivematica-sampledata/TestTransfers/files_with_various_encodings/., to=tmp/tmpcTvt59/mytest)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 storageService:get_location:199:  Storage locations returned: [{u'uuid': u'88a90f24-5dbd-4b91-81e8-31be647221fa', u'pipeline': [u'/api/v2/pipeline/16c0fcfc-99cd-4bd2-a063-22a85a1401bc/'], u'used': 0, u'description': None, u'space': u'/api/v2/space/47e4b519-b267-46fa-abf4-d2e65c1bb640/', u'enabled': True, u'quota': None, u'relative_path': u'var/archivematica/sharedDirectory/', u'purpose': u'CP', u'path': u'/var/archivematica/sharedDirectory', u'resource_uri': u'/api/v2/location/88a90f24-5dbd-4b91-81e8-31be647221fa/'}]
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 storageService:get_location:199:  Storage locations returned: [{u'uuid': u'1f7b6816-2009-4bf2-8f65-bb15fb5a8719', u'pipeline': [u'/api/v2/pipeline/16c0fcfc-99cd-4bd2-a063-22a85a1401bc/'], u'used': 0, u'description': u'', u'space': u'/api/v2/space/47e4b519-b267-46fa-abf4-d2e65c1bb640/', u'enabled': True, u'quota': None, u'relative_path': u'home', u'purpose': u'TS', u'path': u'/home', u'resource_uri': u'/api/v2/location/1f7b6816-2009-4bf2-8f65-bb15fb5a8719/'}]
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 packages:_copy_from_transfer_sources:255:  source: archivematica/archivematica-sampledata/TestTransfers/files_with_various_encodings/., destination: /var/archivematica/sharedDirectory/tmp/tmpcTvt59/mytest/.
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 packages:_start_package_transfer_with_auto_approval:436:  Package 267ec68f-85dc-4f06-9e88-9c88570e5cd2: moving package to processing directory
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 packages:_start_package_transfer_with_auto_approval:441:  Package 267ec68f-85dc-4f06-9e88-9c88570e5cd2: starting workflow processing
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:40 chain:__init__:101:  Creating JobChain 6953950b-c101-4f4c-a0c3-0cd0684afe5e for package 267ec68f-85dc-4f06-9e88-9c88570e5cd2 (initial link 045c43ae-d6cf-44f7-97d6-c8a602748565)
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2021-06-28 15:07:41 client:run:113:  Running Set transfer type: Standard (package 267ec68f-85dc-4f06-9e88-9c88570e5cd2)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:41 gearman_backend:submit:221:  Submitted gearman job 135dd06d-3b05-47f0-901b-d35f9b00d54f (archivematicasettransfertype_v0.0)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:41 gearman_backend:update_task_results:265:  Task 56bb79ee-2c4c-46f0-81dc-98aee4816b03 finished! Result COMPLETE - 0
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2021-06-28 15:07:41 client:run:113:  Running Remove hidden files and directories (package 267ec68f-85dc-4f06-9e88-9c88570e5cd2)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:41 gearman_backend:submit:221:  Submitted gearman job df9bd52d-4e94-4906-98fd-ade532df89ff (removehiddenfilesanddirectories_v0.0)
archivematica-mcp-server_1       | DEBUG    ThreadPoolExecutor-0_0 2021-06-28 15:07:41 gearman_backend:update_task_results:265:  Task 241902ca-bb28-4058-b6dd-eecacd29c06d finished! Result COMPLETE - 0
archivematica-mcp-server_1       | INFO     ThreadPoolExecutor-0_0 2021-06-28 15:07:41 client:run:113:  Running Remove unneeded files (package 267ec68f-85dc-4f06-9e88-9c88570e5cd2)
archivematica-mcp-server_1       | ERROR    ThreadPoolExecutor-0_0 2021-06-28 15:07:41 _base:_invoke_callbacks:333:  exception calling callback for <Future at 0x7f75c4648350 state=finished raised UnicodeDecodeError>
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
archivematica-mcp-server_1       |     callback(self)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/queues.py", line 226, in _job_completed_callback
archivematica-mcp-server_1       |     next_job = future.result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
archivematica-mcp-server_1       |     return self.__get_result()
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
archivematica-mcp-server_1       |     result = self.fn(*self.args, **self.kwargs)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
archivematica-mcp-server_1       |     _reraise(*exc)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
archivematica-mcp-server_1       |     result = f(*args, **kw)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 126, in run
archivematica-mcp-server_1       |     self.submit_tasks()
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/jobs/client.py", line 232, in submit_tasks
archivematica-mcp-server_1       |     filter_subdir=self.filter_subdir,
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/server/packages.py", line 660, in files
archivematica-mcp-server_1       |     for basedir, subdirs, files in scandir.walk(start_path):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/scandir.py", line 676, in _walk
archivematica-mcp-server_1       |     for entry in walk(new_path, topdown, onerror, followlinks):
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/site-packages/scandir.py", line 625, in _walk
archivematica-mcp-server_1       |     entry = next(scandir_it)
archivematica-mcp-server_1       |   File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
archivematica-mcp-server_1       |     return codecs.utf_8_decode(input, errors, True)
archivematica-mcp-server_1       | UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 71: invalid start byte
```

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
