### ISSUE TITLE
Problem: transfers can't start when Storage Service is deployed on a separate VM

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#1472]
**Expected behaviour**
Space `pipeline_local` should be able to transfer files successfully.

**Current behaviour**
The `pipeline_local` space raises errors on Python 3 because paths seem to be constructed improperly. E.g.: `archivematica@am113dashboard.qa.archivematica.net:b'/'` instead of `archivematica@am113dashboard.qa.archivematica.net:/`.

```
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 432, in move_from_storage_service
    source_path, destination_path, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/pipeline_local.py", line 162, in move_from_storage_service
    destination_path, self.remote_user, self.remote_name
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 681, in create_rsync_directory
    subprocess.check_call(cmd)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib64/python3.6/site-packages/gevent/subprocess.py", line 277, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rsync', '-vv', '--protect-args', '--chmod=ug=rwx,o=rx', '--recursive', '/tmp/tmpwlbtcd44/', "archivematica@am113dashboard.qa.archivematica.net:b'/'"]' returned non-zero exit status 3.
INFO      2021-06-29 01:16:28  locations.models.space:space:move_rsync:552:  Moving from b'/home/archivematica-sampledata/SampleTransfers/Images/pictures/.' to b'/var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpqljlzg7s/kk2/.'
INFO      2021-06-29 01:16:28  locations.models.space:space:move_rsync:594:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', b'/home/archivematica-sampledata/SampleTransfers/Images/pictures/.', b'/var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpqljlzg7s/kk2/.']
INFO      2021-06-29 01:16:28  locations.models.space:space:create_rsync_directory:679:  rsync path creation command: ['rsync', '-vv', '--protect-args', '--chmod=ug=rwx,o=rx', '--recursive', '/tmp/tmpkp601v8c/', "archivematica@am113dashboard.qa.archivematica.net:b'/'"]
WARNING   2021-06-29 01:16:28  locations.models.space:space:create_rsync_directory:684:  rsync path creation failed: Command '['rsync', '-vv', '--protect-args', '--chmod=ug=rwx,o=rx', '--recursive', '/tmp/tmpkp601v8c/', "archivematica@am113dashboard.qa.archivematica.net:b'/'"]' returned non-zero exit status 3.
ERROR     2021-06-29 01:16:28  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/location/588737f2-3731-4b72-a697-ffca57d4f4ee/
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 509, in _move_files_between_locations
    raise PosixMoveUnsupportedError
locations.models.space.PosixMoveUnsupportedError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 476, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 499, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 646, in post_detail
    return self._handle_location_file_move(move_files, request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 593, in _handle_location_file_move
    return move_files_fn(data["files"], origin_location, destination_location)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 640, in move_files
    files, origin_location, destination_location
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 526, in _move_files_between_locations
    package=None,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 432, in move_from_storage_service
    source_path, destination_path, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/pipeline_local.py", line 162, in move_from_storage_service
    destination_path, self.remote_user, self.remote_name
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 681, in create_rsync_directory
    subprocess.check_call(cmd)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib64/python3.6/site-packages/gevent/subprocess.py", line 277, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rsync', '-vv', '--protect-args', '--chmod=ug=rwx,o=rx', '--recursive', '/tmp/tmpkp601v8c/', "archivematica@am113dashboard.qa.archivematica.net:b'/'"]' returned non-zero exit status 3.
```

Also:

```
Jun 29 08:11:47 am112ss.qa gunicorn[17651]: opening connection using: ssh -l archivematica am113dashboard.qa.archivematica.net rsync --server -svvre.iLsfxC  (7 args)
Jun 29 08:11:47 am112ss.qa gunicorn[17651]: protected args: . "b'/'"  (2 args)
Jun 29 08:11:48 am112ss.qa gunicorn[17651]: sending incremental file list
Jun 29 08:11:48 am112ss.qa gunicorn[17651]: rsync: change_dir#3 "/var/lib/archivematica//b'" failed: No such file or directory (2)
Jun 29 08:11:48 am112ss.qa gunicorn[17651]: rsync error: errors selecting input/output files, dirs (code 3) at main.c(695) [Receiver=3.1.2]
Jun 29 08:16:28 am112ss.qa gunicorn[17651]: opening connection using: ssh -l archivematica am113dashboard.qa.archivematica.net rsync --server -svvre.iLsfxC  (7 args)
Jun 29 08:16:28 am112ss.qa gunicorn[17651]: protected args: . "b'/'"  (2 args)
Jun 29 08:16:28 am112ss.qa gunicorn[17651]: sending incremental file list
Jun 29 08:16:28 am112ss.qa gunicorn[17651]: rsync: change_dir#3 "/var/lib/archivematica//b'" failed: No such file or directory (2)
Jun 29 08:16:28 am112ss.qa gunicorn[17651]: rsync error: errors selecting input/output files, dirs (code 3) at main.c(695) [Receiver=3.1.2]
```
And:

```
WARNING   2021-06-29 02:53:45  locations.models.space:space:move_rsync:602:  Rsync failed with status 11: b'opening connection using: ssh -l archivematica am113dashboard.qa.archivematica.net rsync --server -svvOtre.iLsfxC  (7 args)\nprotected args: . "b\'/var/archivematica/sharedDirectory/tmp/tmpjiqa7jar/juyjujujujuju/.\'"  (2 args)\nsending incremental file list\nrsync: mkdir "/var/lib/archivematica/b\'/var/archivematica/sharedDirectory/tmp/tmpjiqa7jar/juyjujujujuju/.\'" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]\n'
ERROR     2021-06-29 02:53:45  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/location/588737f2-3731-4b72-a697-ffca57d4f4ee/
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 509, in _move_files_between_locations
    raise PosixMoveUnsupportedError
locations.models.space.PosixMoveUnsupportedError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 476, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 499, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 646, in post_detail
    return self._handle_location_file_move(move_files, request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 593, in _handle_location_file_move
    return move_files_fn(data["files"], origin_location, destination_location)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 640, in move_files
    files, origin_location, destination_location
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 526, in _move_files_between_locations
    package=None,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 432, in move_from_storage_service
    source_path, destination_path, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/pipeline_local.py", line 173, in move_from_storage_service
    rsync_password=self.rsync_password,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 603, in move_rsync
    raise StorageException(s)
locations.models.StorageException: Rsync failed with status 11: b'opening connection using: ssh -l archivematica am113dashboard.qa.archivematica.net rsync --server -svvOtre.iLsfxC  (7 args)\nprotected args: . "b\'/var/archivematica/sharedDirectory/tmp/tmpjiqa7jar/juyjujujujuju/.\'"  (2 args)\nsending incremental file list\nrsync: mkdir "/var/lib/archivematica/b\'/var/archivematica/sharedDirectory/tmp/tmpjiqa7jar/juyjujujujuju/.\'" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]\n'
```

**Steps to reproduce**
1. Deploy Archivematica and Storage Service on separate VMs
2. Start a new transfer
3. Check the logs

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica v1.13.0-rc.3

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
This seems to be resolved now.
