### ISSUE TITLE
Problem: Packages stored in Duracloud cannot be downloaded

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1473]
**Expected behaviour**

Users can download packages stored in Duracloud from Archival Storage in the dashboard or the Packages tab of the Storage Service.

**Current behaviour**

The Storage Service produces  this traceback saying that the request is unauthorized:

```
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:346:  TO: src: AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:347:  TO: dst: ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:348:  TO: staging: /var/archivematica/storage_service
DEBUG     2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:237:  URL: https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:240:  Response: <Response [401]>
WARNING   2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:277:  Response: <Response [401]> when fetching https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
WARNING   2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:278:  Response text: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Full authentication is required to access this resource</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.60</h3></body></html>
DEBUG     2021-06-30 08:11:52  locations.models.package:package:compress_package:1669:  in package.py::compress_package
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:346:  TO: src: AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:347:  TO: dst: ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.space:space:move_to_storage_service:348:  TO: staging: /var/archivematica/storage_service
DEBUG     2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:237:  URL: https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
DEBUG     2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:240:  Response: <Response [401]>
WARNING   2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:277:  Response: <Response [401]> when fetching https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
WARNING   2021-06-30 08:11:52  locations.models.duracloud:duracloud:_download_file:278:  Response text: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Full authentication is required to access this resource</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.60</h3></body></html>
ERROR     2021-06-30 08:11:52  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/ce9dbdf0-3ec5-4c98-998d-02e2da46322c/download/
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1378, in download_request
    full_path = package.get_download_path(lockss_au_number)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 297, in get_download_path
    full_path = self.fetch_local_path()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 361, in fetch_local_path
    destination_space=ss_internal.space,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 364, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/duracloud.py", line 317, in move_to_storage_service
    success = self._download_file(url, dest_path)
  File "/usr/lib/archivematica/storage-service/locations/models/duracloud.py", line 279, in _download_file
    raise StorageException("Unable to fetch %s" % url)
locations.models.StorageException: Unable to fetch https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 169, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1380, in download_request
    full_path, temp_dir = package.compress_package(utils.COMPRESSION_TAR)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1680, in compress_package
    full_path = self.fetch_local_path()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 361, in fetch_local_path
    destination_space=ss_internal.space,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 364, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
  File "/usr/lib/archivematica/storage-service/locations/models/duracloud.py", line 317, in move_to_storage_service
    success = self._download_file(url, dest_path)
  File "/usr/lib/archivematica/storage-service/locations/models/duracloud.py", line 279, in _download_file
    raise StorageException("Unable to fetch %s" % url)
locations.models.StorageException: Unable to fetch https://example.com/aips//AIPstore/ce9d/bdf0/3ec5/4c98/998d/02e2/da46/322c/douglas_large_zip_transfer-ce9dbdf0-3ec5-4c98-998d-02e2da46322c.7z
```

**Steps to reproduce**

1. Store an AIP in Duracloud
2. Download the package from the Archival Storage tab in the dashboard or the Packages tab in the storage service
3. Check the SS logs for the traceback above

**Your environment (version of Archivematica, operating system, other relevant details)**

AM https://github.com/artefactual/archivematica/commit/fef98993552f8d62f576a30be16306b4f49f49fb
SS https://github.com/artefactual/archivematica-storage-service/commit/9bd6a4768bd8253606f3ad9c3ebf006e0b0c6bb4

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Working now, thanks!
