### ISSUE TITLE
Problem: size = 0 not valid option for NFS spaces

### ISSUE THREAD

**Issue by jens-st** [archivematica/Issues#1489]
**Version of the documentation**
Archivematica Storage Service 0.18.0

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/storage-service-0.18/administrators/#nfs

**Description of the issue**
"0" does not represent unlimited allowed space, only a blank value. Using "0" results in a mysterious internal server error on the dashboard job "Store the AIP"
```
500 Server Error: Internal Server Error for url: http://192.168.222.14:8000/api/v2/file/Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/job.py", line 113, in JobContext
    yield
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 369, in call
    args.sip_type,
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 244, in store_aip
    related_package_uuid,
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 80, in _create_file
    agents=get_agents_from_db(uuid),
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 415, in create_file
    response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.222.14:8000/api/v2/file/

```
and a "Not enough space for AIP on storage device" exception in the storage service:
```
ERROR     2021-08-17 06:29:40  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 467, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 499, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 1408, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1114, in obj_create
    self._store_bundle(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1049, in _store_bundle
    aip_subtype=aip_subtype,
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 849, in store_aip
    v = self._store_aip_to_pending(origin_location, origin_path)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 901, in _store_aip_to_pending
    self._check_quotas(dest_space, self.current_location)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 458, in _check_quotas
    "aip_size": self.size,
locations.models.StorageException: Not enough space for AIP on storage device 65280d69-f0a0-4622-b0a1-8d326e5cde53: /mnt/permanent-02 (NFS; Used: 0; Size: 0; AIP size: 2534875
```

**Suggested fix**
* Remove "0" from documentation.
* Make free space error visible for dashboard users

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
This has been fixed in https://github.com/artefactual/archivematica-storage-service-docs/commit/51d54d7124bb2233be5e0421300553839d30d418
