### ISSUE TITLE
Problem: Storage Service 0.18.x doesn't follow symlinks

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1515]
**Expected behaviour**
When the transfer source is a symbolic link, the storage service follows it and serve it's content. This was the case in ss/0.17.x

**Current behaviour**
 Dashboard fails to show contents of transfer sources that point to symbolic links with:

```
ERROR     2021-12-30 08:52:42  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /filesystem/children/location/a420512d-7ddd-4eae-8447-348264a94a34/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/filesystem_ajax/views.py", line 125, in directory_children_proxy_to_storage_server
    response = storage_service.browse_location(location_uuid, path)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 276, in browse_location
    browse = response.json()
  File "/usr/share/archivematica/virtualenvs/archivematica/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Steps to reproduce**

 - Create a symbolic link to be used as transfer source:
```
sudo ln -s /home/archivematica-sampledata /transfer-source
```
 - Configure a transfer source in the SS pointing to /transfer-source

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica SS stable/0.18.x, on Ubuntu 18.04 and Centos 7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment]
As a workaround, the symbolic link can be changed into a bind mount with:

```
rm /transfer_source
mkdir /transfer_source
mount -o bind /home/archivematica-sampledata /transfer_source
````

**Comment by duprel** [comment]
We are seeing the same issue with a transfer directory that is in AWS S3.
