### ISSUE TITLE
Problem: SS fails when importing compressed AIPs

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1516]
**Expected behaviour**

The import_aip command should work

**Current behaviour**

It fails when using the `--compression-algorithm '7z with bzip'` option:

```
Attempting to import the AIP at /mnt/sto_CUSTOMER_processing/transfer/migration/aipstore/PUB-050_Issues_Events_1969-00399e09-11d7-4ea3-8797-377284404202.7z.
Location: dd042c75-95b8-46c5-a84c-d69d0b92f346 (FS).
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica-storage-service/storage_service/common/management/commands/import_aip.py", line 153, in handle
    options["tmp_dir"],
  File "/opt/archivematica/archivematica-storage-service/storage_service/common/management/commands/import_aip.py", line 448, in import_aip
    aip_model_inst, compression_algorithm
  File "/opt/archivematica/archivematica-storage-service/storage_service/common/management/commands/import_aip.py", line 391, in compress
    ) = aip_model_inst.compress_package(compression_algorithm, detailed_output=True)
  File "/opt/archivematica/archivematica-storage-service/storage_service/locations/models/package.py", line 1699, in compress_package
    os.write(file_, tool_info_command)
TypeError: a bytes-like object is required, not 'str'
Error when importing PUB-050_Issues_Events_1969-00399e09-11d7-4ea3-8797-377284404202.7z file: Aborting! - Thu Dec 30 12:38:45 UTC 2021
``` 

**Steps to reproduce**

Try to import an AIP with:

```
        sudo -u archivematica bash -c " \
                set -a -e
                source ${AM_CONFIG_DIR}/archivematica-storage-service
                cd /usr/lib/archivematica/storage-service
                /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py \
                import_aip --decompress-source --compression-algorithm '7z with bzip' --force --pipeline \
                ${PIPELINE_UUID} --aip-storage-location ${AIP_STORE_LOCATION_UUID} --tmp-dir ${AIP_TMP_DIR} \
                ${AIP_DIR}/${aip_7z_file}
        ";
```

**Your environment (version of Archivematica, operating system, other relevant details)**

SS v0.18.1

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Workround: (Thanks @replaceafill )

```
root@am-CUSTOMER-2:/opt/archivematica/archivematica-storage-service# git diff
diff --git a/storage_service/locations/models/package.py b/storage_service/locations/models/package.py
index 9d76bd9..bf6cec6 100644
--- a/storage_service/locations/models/package.py
+++ b/storage_service/locations/models/package.py
@@ -1696,7 +1696,7 @@ class Package(models.Model):

             script_path = "/tmp/{}".format(str(uuid4()))
             file_ = os.open(script_path, os.O_WRONLY | os.O_CREAT, 0o770)
-            os.write(file_, tool_info_command)
+            os.write(file_, tool_info_command.encode("utf-8"))
             os.close(file_)
             tic_cmd = [script_path]
             p = subprocess.Popen(
@@ -1709,9 +1709,9 @@ class Package(models.Model):
             LOGGER.debug(tic_stdout)
             LOGGER.debug(tic_stderr)
             details = {
-                "event_detail": tic_stdout,
+                "event_detail": tic_stdout.decode("utf-8"),
                 "event_outcome_detail_note": 'Standard Output="{}"; Standard Error="{}"'.format(
-                    stdout, stderr
+                    stdout.decode("utf-8"), stderr.decode("utf-8")
                 ),
             }
             return (compressed_filename, extract_path, details)
```

**Comment by mamedin** [comment]
Same error on SS v0.19.0 and workaround is still working.

**Comment by replaceafill** [comment]
Verified this by running the `import_aip` management command in a QA server passing the `--compression-algorithm` flag:

```bash
   sudo -u archivematica bash -c " \
	    set -a -e -x
	    source /etc/default/archivematica-storage-service || \
	        source /etc/sysconfig/archivematica-storage-service \
	            || (echo 'Environment file not found'; exit 1)
	    cd /usr/lib/archivematica/storage-service
	    /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py import_aip --decompress-source --compression-algorithm tar /tmp/test-long-names-cc411259-f3d1-443a-961b-9acd5c7d07f0.7z
  ";
```

The AIP was successfully imported and stored as a `tar` file.
