### ISSUE TITLE
Problem: A valid transfer mets_structmap.xml fails compliance in some instances

### ISSUE THREAD

**Issue by djjuhasz** [archivematica/Issues#1536]
**Expected behaviour**

A [mets_structmap.xml](https://www.archivematica.org/en/docs/archivematica-1.13/user-manual/transfer/import-metadata/#structmap-xml) can be included in an Archivematica transfer to provide information about the hierarchical or logical structure of the transfer files.  The `mets_structmap.xml` metadata should be incorporated into the [AIP METS file](https://www.archivematica.org/en/docs/archivematica-1.13/user-manual/archival-storage/aip-structure/#aip-mets-file) to record the context of the AIP files.

**Current behaviour**

In some Archivematica instances any transfer that includes a `mets_structmap.xml` will cause the _Microservice: Verify transfer compliance_ > _Job Verify mets_structmap.xml compliance_ to fail with the error: 

```
Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 760Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/verify_mets.py", line 34, in call
    xmlschema = etree.XMLSchema(etree.parse(mets_xsd))
  File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:204467)
XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 760
```

Attempts to manually download the Library of Congress xlink schema also fail with a *403 (Forbidden)* error:

```
$ curl -v http://www.loc.gov/standards/xlink/xlink.xsd
*   Trying 104.16.55.16...
* TCP_NODELAY set
* Connected to www.loc.gov (104.16.55.16) port 80 (#0)
> GET /standards/xlink/xlink.xsd HTTP/1.1
> Host: www.loc.gov
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Date: Thu, 24 Feb 2022 21:28:34 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: close
...
```

And the HTML response includes a ReCAPTCHA request:

```
<div class="cf-column">
    <h2 data-translate="why_captcha_headline">
        Why do I have to complete a CAPTCHA?
    </h2>
    <p data-translate="why_captcha_detail">
        Completing the CAPTCHA proves you are a human and gives you temporary
        access to the web property.
    </p>
</div>
<div class="cf-column">
    <h2 data-translate="resolve_captcha_headline">
        What can I do to prevent this in the future?
    </h2>
    <p data-translate="resolve_captcha_antivirus">
        If you are on a personal connection, like at home, you can run an
        anti-virus scan on your device to make sure it is not infected with
        malware.
    </p>
    <p data-translate="resolve_captcha_network">
        If you are at an office or shared network, you can ask the network
        administrator to run a scan across the network looking for misconfigured
        or infected devices.
    </p>
</div>
```

**Steps to reproduce**

This can be reproduced at https://sandbox.archivematica.org/

1. Create an Archivematica standard transfer that includes a well-formed [mets_structmap.xml](https://www.archivematica.org/en/docs/archivematica-1.13/user-manual/transfer/import-metadata/#structmap-xml) file.
2. On the Archivmatica transfer tab select the transfer with the `mets_structmap.xml` file, and click "Start transfer"

OR

1. On the Archivematica Transfer tab select the [Archivematica sampledata](https://github.com/artefactual/archivematica-sampledata) > _SampleTransfers_ > _StructMapTransferSamples_ > _MinimalStructMapExample_ transfer and click "Start transfer"

**Your environment (version of Archivematica, operating system, other relevant details)**

Server: https://sandbox.archivematica.org/transfer/ (and others)
Archivematica versions: 1.12.1 and 1.13.0

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
I noticed the 403 problem also shows with Jhove in the `Characterize and extract metadata on submission documentation` job of the `Process submission documentation` microservice when the transfer METS included in the `objects/submissionDocumentation` is characterized. The job doesn't fail in the default configuration but it logs a lot of repeated `message` elements:

```
  ..
  <fileinfo>
    <size toolname="Jhove" toolversion="1.16">676939</size>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/pictures-45afa7be-bde9-4c89-a881-49418b7e4561/objects/submissionDocumentation/METS.45afa7be-bde9-4c89-a881-49418b7e4561.xml</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">METS.45afa7be-bde9-4c89-a881-49418b7e4561.xml</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">d96f0da1b33cf3f4a503391325c16d49</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1646322333000</fslastmodified>
  </fileinfo>
  <filestatus>
    <well-formed toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">true</well-formed>
    <valid toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">false</valid>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">cvc-elt.1: Cannot find the declaration of element 'mets:mets'. Line = 2, Column = 248</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">cvc-elt.4.2: Cannot resolve 'premis:intellectualEntity' to a type definition for element 'premis:object'. Line = 7, Column = 219</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/premis/v3/premis.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    <message toolname="Jhove" toolversion="1.16" status="SINGLE_RESULT">schema_reference.4: Failed to read schema document 'http://www.loc.gov/standards/mets/version1121/mets.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;.</message>
    ...
```
