### ISSUE TITLE
Problem: Lint jobs fail in CI because of pre-commit depedencies

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#1558]
**Expected behaviour**

Linting jobs execute successfully in GitHub CI workflows.

**Current behaviour**

The `linting` tox environments that are run in Python 3.7+ fail in GitHub actions because `pre-commit` sets `black` with an incompatible and unpinned version of `click` which causes this error:

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/work/archivematica/archivematica/.tox/.tmp/user/.cache/pre-commit/repok21z573g/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/work/archivematica/archivematica/.tox/.tmp/user/.cache/pre-commit/repok21z573g/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/runner/work/archivematica/archivematica/.tox/.tmp/user/.cache/pre-commit/repok21z573g/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/archivematica/archivematica/.tox/.tmp/user/.cache/pre-commit/repok21z573g/py_env-python3/lib/python3.7/site-packages/click/__init__.py)
```

**Steps to reproduce**

Trigger a GitHub CI workflow run with a lint job that runs on Python 3.7+.

**Your environment (version of Archivematica, operating system, other relevant details)**

A few recent workflow runs show this problem:

* [amclient](https://github.com/artefactual-labs/amclient/runs/6697800016?check_suite_focus=true)
* [archivematica](https://github.com/artefactual/archivematica/runs/6710555802?check_suite_focus=true)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
A related problem seen in https://github.com/artefactual/archivematica/actions/runs/3586406209/jobs/6035558828 is the change of the `flake8` repository from gitlab to github:

```
Run tox -e linting
linting create: /home/runner/work/archivematica/archivematica/.tox/linting
linting installdeps: pre-commit
linting installed: cfgv==3.3.1,distlib==0.3.6,filelock==3.8.0,identify==2.5.9,importlib-metadata==5.1.0,nodeenv==1.7.0,platformdirs==2.5.4,pre-commit==2.20.0,PyYAML==6.0,toml==0.10.2,typing_extensions==4.4.0,virtualenv==20.17.0,zipp==3.11.0
linting run-test-pre: PYTHONHASHSEED='2496086213'
linting run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/ambv/black.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com/': No such device or address
    
Check the log at /home/runner/work/archivematica/archivematica/.tox/.tmp/user/.cache/pre-commit/pre-commit.log
ERROR: InvocationError for command /home/runner/work/archivematica/archivematica/.tox/linting/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 3)
___________________________________ summary ____________________________________
ERROR:   linting: commands failed
Error: Process completed with exit code 1.
```

**Comment by replaceafill** [comment]
While updating the pre-commit configuration in [mets-retriever](https://github.com/artefactual-labs/mets-retriever) I noticed a [new release of poetry broke isort](https://github.com/PyCQA/isort/issues/2077) when the linting jobs run on Python 3.7+:

```
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repos1eajzhi/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /root/.cache/pre-commit/repos1eajzhi
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/root/.cache/pre-commit/repos1eajzhi/py_env-python3/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/root/.cache/pre-commit/repos1eajzhi/py_env-python3/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/root/.cache/pre-commit/repos1eajzhi/py_env-python3/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-xhxi1k8h/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-xhxi1k8h/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by replaceafill** [comment]
Verified that the `pre-commit` configuration file of the repositories in the `artefactual` and `artefactual-labs` organizations have been updated to address this problem. Also the GitHub CI workflows have been updated to run jobs on Ubuntu 20.04 or above.
