### ISSUE TITLE
Problem: unable to use pipeline local filesystem space with Mac OS 11.3

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1564]
**Expected behaviour**

When configuring a pipeline local filesystem, it works

**Current behaviour**
When the remote is Mac OS 11.3 (at least), rsync fails with exit status 12:

```
DEBUG     2022-07-05 02:34:38  locations.models.space:space:browse_rsync:739:  "rsync" "--protect-args" "--list-only" "--exclude" ".*" "--rsh" "ssh -i /var/lib/archivematica/.ssh/id_rsa" "XXXX@X.X.X.X:/Volumes/XXXX/collections storage/"
WARNING   2022-07-05 02:34:39  locations.models.space:space:browse_rsync:746:  rsync list failed: Command '['rsync', '--protect-args', '--list-only', '--exclude', '.*', '--rsh', 'ssh -i /var/lib/archivematica/.ssh/id_rsa', 'XXXX@X.X.X.X:/Volumes/XXXXX/collections storage/']' returned non-zero exit status 12.
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 744, in browse_rsync
    output = subprocess.check_output(command, env=env)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib64/python3.6/site-packages/gevent/subprocess.py", line 404, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['rsync', '--protect-args', '--list-only', '--exclude', '.*', '--rsh', 'ssh -i /var/lib/archivematica/.ssh/id_rsa', 'XXXX@X.X.X.X:/Volumes/XXXX/collections storage/']' returned non-zero exit status 12.
```

**Steps to reproduce**
Configure a pipeline local filesystem against a Mac

**Your environment (version of Archivematica, operating system, other relevant details)**
Archivematica 1.13/ SS 1.19. It was working with Archivematica 1.8 and an unknown version of Mac OS.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment]
The output of the standalone rsync command is as follows:
```
rsync --protect-args  --list-only --exclude '.*'  --rsh 'ssh -i /var/lib/archivematica/.ssh/id_rsa' -v 'XXXX@X.X.X.X:/Volumes/XXXXX/collections storage/'
rsync: on remote machine: -svde.LsfxC: unknown option
rsync error: syntax or usage error (code 1) at /System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(1337) [server=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.2]
```

And it works if you remove the '--protect-args' switch:

```
rsync  --list-only --exclude '.*'  --rsh 'ssh -i /var/lib/archivematica/.ssh/id_rsa' -v 'XXXX@X.X.X.X:/Volumes/XXXXX/collections storage/'               
receiving file list ... done
drwxrwxrwx        262,144 2022/06/28 15:41:51 .
(...)

```


The Mac version of rsync is

```
XXXXX@XXXXXX collections storage % rsync --version
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, no prealloc, file-flags
```

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
