### ISSUE TITLE
Problem: Access tab shows "Internal Server Error" in some cases

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#1572]
**Expected behaviour**

Access tab in the Archivematica Dashboard (https://archivematica.org/en/docs/archivematica-1.12/user-manual/access/access/#access-tab) should show a list of DIPs uploaded to AtoM (from the Accesses table of the MCP database)

**Current behaviour**

In some cases (despite all the other Dashboard tabs showing properly), the Access tab shows a message "Internal server error. Sorry Something wrong happened. Please, contact with your administrator" 

**Additional Information**

dashboard log:

```
ERROR     2022-09-16 17:38:38  django.request:exception:handle_uncaught_exception:135:  Internal Server Error: /access
/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/views.py", line 119, in access_list
    return render(request, "main/access.html", locals())
…
…
 File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/template/base.py", line 911, in _resolve_lookup
    current = current()
  File "/opt/archivematica/archivematica/src/dashboard/src/main/models.py", line 224, in get_title
    return Job.objects.filter(sipuuid=self.sipuuid).get_directory_name()
  File "/opt/archivematica/archivematica/src/dashboard/src/main/models.py", line 803, in get_directory_name
    return job.get_directory_name()
AttributeError: 'NoneType' object has no attribute 'get_directory_name'
```

- To obtain the data for the Access tab view, for each DIP listed in the Accesses table, the get_title() function is called to obtain the AIP "title", which executes a query on the MCP database Jobs table for entries with the same SIP UUID as the DIP.

- models.Access.get_title() calls models.JobQuerySet.get_directory_name() . When the query on the Jobs table is empty (no entry in the Jobs table with the same SIP UUID as the DIP in Accesses table), an unhandled exception occurs (because the queryset is empty, models.JobQuerySet.get_directory_name() is attempting to call get_directory_name() on a None object instead of a Job object)

- There seems to be a typo/bug in the try: statement of models.JobQuerySet.get_directory_name() which prevents the except IndexError: clause to trigger when the queryset is empty, thi\us causing the unhandled exception error (internal server error)

**Your environment (version of Archivematica, operating system, other relevant details)**

AM 1.12.x (same problem exists in stable/1.13.x and qa/1.x)

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
Tested in production and dev environments
