### ISSUE TITLE
Problem: Move AIP call does not work when using uncompressed AIPs

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1587]
**Expected behaviour**

Making a Move AIP call to the API moves the AIP.

**Current behaviour**

When using uncompressed AIPs we got the following error:

```
ERROR     2023-01-10 08:06:41  locations.models.async_manager:async_manager:wrapper:142:  Task threw an error: cannot parse from 'NoneType'
Caller's traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/gevent/[baseserver.py](http://baseserver.py/)", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/gunicorn/workers/[ggevent.py](http://ggevent.py/)", line 155, in handle
    super(GeventWorker, self).handle(listener, client, addr)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/gunicorn/workers/base_[async.py](http://async.py/)", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/gunicorn/workers/[ggevent.py](http://ggevent.py/)", line 160, in handle_request
    addr)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/gunicorn/workers/base_[async.py](http://async.py/)", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[wsgi.py](http://wsgi.py/)", line 157, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[base.py](http://base.py/)", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/whitenoise/[middleware.py](http://middleware.py/)", line 25, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/utils/[deprecation.py](http://deprecation.py/)", line 140, in __call__
    response = self.get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[exception.py](http://exception.py/)", line 41, in inner
    response = get_response(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/core/handlers/[base.py](http://base.py/)", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/django/views/decorators/[csrf.py](http://csrf.py/)", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/[resources.py](http://resources.py/)", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/[resources.py](http://resources.py/)", line 183, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/[resources.py](http://resources.py/)", line 1698, in move_request
    async_task = [AsyncManager.run](http://asyncmanager.run/)_task(task)
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/models/async_[manager.py](http://manager.py/)", line 139, in wrapper
    value = task_fn(*args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/[resources.py](http://resources.py/)", line 1693, in task
    package.move(location)
  File "/usr/lib/archivematica/storage-service/locations/models/[package.py](http://package.py/)", line 526, in move
    self._update_existing_ptr_loc_info()
  File "/usr/lib/archivematica/storage-service/locations/models/[package.py](http://package.py/)", line 1123, in _update_existing_ptr_loc_info
    root = etree.parse(pointer_absolute_path)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1882, in lxml.etree._parseDocument
TypeError: cannot parse from 'NoneType'
```

**Steps to reproduce**

Make a call to the Move API.

**Your environment (version of Archivematica, operating system, other relevant details)**

Storage Service 0.18.0 on RHEL 7 and CentOS7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by Dhwaniartefact** [comment]
verified this issue in dev environment by moving uncompressed AIP from new AIPStore location to default AIPStore by using below command.

```
curl -H "Authorization: ApiKey test:test" -d "location_uuid=55633556-3ddb-4735-b049-c9d823ea88c0" "http://127.0.0.1:62081/api/v2/file/90f71c91-073a-423b-8c00-28013de43d82/move/"
```
