### ISSUE TITLE
Problem: Transfer names with pattern matching notation can fail if the pattern is not valid after expansion (for instance: `Transfer[001-001]`)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1594]
**Expected behaviour**

The transfer should finish without errors

**Current behaviour**

When using a transfer name like `Transfer[001-001]` it fails because the `glob` module on [archivematicaFunctions.py](https://github.com/artefactual/archivematica/blob/fbda1a91d6dff086e7124fa1d7a3c7953d8755bb/src/archivematicaCommon/lib/archivematicaFunctions.py#L280) detects that [001-001] is a bad range and fails.

Error on `Job Assign file UUIDs to objects` microservice:

```
bad character range 1-0 at position 38Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 113, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 280, in call
    mets_file = find_mets_file(kwargs["sip_directory"])
  File "/usr/lib/archivematica/archivematicaCommon/archivematicaFunctions.py", line 280, in find_mets_file
    mets_paths = glob.glob(os.path.join(src, "METS.*.xml"))
  File "/usr/lib64/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib64/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib64/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib64/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/lib64/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib64/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/usr/lib64/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib64/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range 1-0 at position 38
```
But when using `Transfer[000-001]` as name, it works fine because `[000-001]` is a valid range for the `glob` module. And the transfer name in the `Transfer`, `Ingest` and `Archival Storage` tabs has been changed to `Transfer_000-001_`

**Steps to reproduce**

Start any transfer with the name `NAME[001-001]` or any other invalid range.

**Your environment (version of Archivematica, operating system, other relevant details)**

OS: Tested on Ubuntu 18.04 and RHEL7
AM version: 1.13.2

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
