### ISSUE TITLE
Problem: Fixity ends prematurely when getting an error from SS and doesn't update SS database

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1595]
**Expected behaviour**

When a fixity scan fails, it must print the error and update the Storage Service database.

**Current behaviour**

Fixity fails scanning a replica AIP that doesn't have a main AIP (it has been deleted and the replica is still on SS!), and storage service fails when validating the AIP because it cannot find the pointer. 

SS error:

```
  ERROR     2023-05-16 10:58:03  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/7a1f714a-638c-41a7-b3ed-79da74979c75/check_fixity/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 183, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1434, in check_fixity_request
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 2008, in get_fixity_check_report_send_signals
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1962, in check_fixity
    path, temp_dir = self.extract_file()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1621, in extract_file
    compression = utils.get_compression(self.full_pointer_file_path)
  File "/usr/lib/archivematica/storage-service/common/utils.py", line 311, in get_compression
    doc = etree.parse(pointer_path)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/var/archivematica/storage_service/583b/76b1/bb2f/4526/b25d/0426/aad0/2f19/pointer.583b76b1-bb2f-4526-b25d-0426aad02f19.xml': failed to load external entity "/var/archivematica/storage_service/583b/76b1/bb2f/4526/b25d/0426/aad0/2f19/pointer.583b76b1-bb2f-4526-b25d-0426aad02f19.xml"
```

Fixity is ending and database is not updated with:

```
[archivematica@XXXXXXXX ~]$ /usr/local/bin/fixity scan 173a1476-1cbb-48ab-b718-e6f9b0cab9fb
'StorageServiceError' object has no attribute 'message'
```

**Steps to reproduce**

Rename the pointer file of a main AIP and run fixity on replica

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.13.2, SS1.19.0, RHEL7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
It is a python2 -> python3 upgrade bug. Fixed when using `str(e)` instead of `e.message`.

Thanks to @danloveg for troubleshooting and fix :)
