### ISSUE TITLE
Problem: Fixity is returning exit status 0 on SS crash, and SS is not updating fixity table

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1596]
**Expected behaviour**

a) Fixity command should return a non-zero exit status when SS cannot scan the AIP
b) Storage Service should update fixity table with an error on SS crash

**Current behaviour**

a) Fixity command is returning 0:

```
[archivematica@XXXXXXXXXX ~]$ /usr/local/bin/fixity scan 7a1f714a-638c-41a7-b3ed-79da74979c75
Storage service at "http://YYYYYYYY:ZZZZ" encountered an internal error while scanning AIP 7a1f714a-638c-41a7-b3ed-79da74979c75
[archivematica@XXXXXXXXXX ~]$ echo $?
0
```

b) SS is not adding any record to the fixity table after the crash

**Steps to reproduce**

The SS crash that reproduces the issue is a bit difficult to be reproduced. It has been obtained scanning a replica AIP whose main AIP has been deleted (I wonder how it could be done, because it was done with SS GUI, I could see the deletion request).

SS log:

```
ERROR     2023-05-17 09:46:32  django.request.tastypie:resources:_handle_500:321:  Internal Server Error: /api/v2/file/7a1f714a-638c-41a7-b3ed-79da74979c75/check_fixity/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python3.6/site-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 183, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1434, in check_fixity_request
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 2008, in get_fixity_check_report_send_signals
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1962, in check_fixity
    path, temp_dir = self.extract_file()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1621, in extract_file
    compression = utils.get_compression(self.full_pointer_file_path)
  File "/usr/lib/archivematica/storage-service/common/utils.py", line 311, in get_compression
    doc = etree.parse(pointer_path)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/var/archivematica/storage_service/583b/76b1/bb2f/4526/b25d/0426/aad0/2f19/pointer.583b76b1-bb2f-4526-b25d-0426aad02f19.xml': failed to load external entity "/var/archivematica/storage_service/583b/76b1/bb2f/4526/b25d/0426/aad0/2f19/pointer.583b76b1-bb2f-4526-b25d-0426aad02f19.xml"
```

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.13.2
SS 0.18
RHEL7

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment]
Using SS v0.19.0 writes the error to the fixity table.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
