### ISSUE TITLE
Problem: xlink fields in metsrw are not url encoded

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#187]
**Expected behaviour**

Related to archivematica/issues#131 the filename `30_CFLQ_271_13-3-13_1524[1].pdf` needs to be urlencoded to pass validation.

**Current behaviour**

This portion of code is responsible for writing that particular filename out at present: https://github.com/artefactual/archivematica/blob/16e0f04ff3510c0abc1425c33da58da91fda80a1/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py#L378-L385 but when written to the METS three entries are created, including an xlink (this one is urlencoded): `<mets:FLocat xlink:href="30_CFLQ_271_13-3-13_1524[1].pdf" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>`

When urlencoded, the rest of the path entries are also impacted which results in those paths being incorrect unless later on in the workflow our tools know how to decode those values.

Joel D notes a possible addition to `metsrw`:

```
import urllib
import urlparse


def urlencode(url):
    parsed = urlparse.urlparse(url)
    for attr in ('path', 'params', 'query', 'fragment'):
        parsed = parsed._replace(**{attr: urllib.quote_plus(getattr(parsed, attr), safe='/')})
    return urlparse.urlunparse(parsed)
```
Further, he notes that there are only a handful of places in metsrw where xlink:href appears to be touched, so running adding a function like the above shouldn't be much problem:
```
$ ack --type=python href ./metsrw
metsrw/metadata.py
250:        target = root.get(utils.lxmlns('xlink') + 'href')
252:            raise exceptions.ParseError('mdRef must have an xlink:href.')
279:            el.attrib[utils.lxmlns('xlink') + 'href'] = self.target

metsrw/fsentry.py
52:        populate FLocat @xlink:href
339:            flocat.set(utils.lxmlns('xlink') + 'href', self.path)

metsrw/mets.py
388:                    utils.lxmlns('xlink') + 'href')```
```
**Steps to reproduce**

Transfer the dataset `Canadian Relocation Cases: Heading Towards Guidelines, 2011 [test] ` using the Dataverse transfer type at time of writing.

**Additional context**

DOI of dataset is: https://doi.org/10.5072/FK2/QYH45Z

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by ross-spencer** [comment]
METS when the path is urlencoded when the FSEntry is written:
```
<?xml version='1.0' encoding='utf-8'?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd">
  <mets:metsHdr CREATEDATE="2018-09-20T16:40:16"/>
  <mets:dmdSec ID="dmdSec_196225" CREATED="2018-09-20T16:40:16" STATUS="original">
    <mets:mdRef LABEL="dataset.json" xlink:href="metadata/dataset.json" MDTYPE="OTHER" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
  </mets:dmdSec>
  <mets:dmdSec ID="dmdSec_736206" CREATED="2018-09-20T16:40:16" STATUS="original">
    <mets:mdWrap MDTYPE="DDI">
      <mets:xmlData>
        <ddi:codebook xmlns:ddi="http://www.icpsr.umich.edu/DDI" version="2.5" xsi:schemaLocation="http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd">
          <ddi:stdyDscr>
            <ddi:citation>
              <ddi:titlStmt>
                <ddi:titl>Canadian Relocation Cases: Heading Towards Guidelines, 2011 [test]</ddi:titl>
                <ddi:IDNo agency="doi">https://doi.org/10.5072/FK2/QYH45Z</ddi:IDNo>
              </ddi:titlStmt>
              <ddi:rspStmt>
                <ddi:AuthEnty>Nicholas Bala</ddi:AuthEnty>
              </ddi:rspStmt>
              <ddi:distStmt>
                <ddi:distrbtr>Root Dataverse</ddi:distrbtr>
              </ddi:distStmt>
              <ddi:verStmt>
                <ddi:version date="2018-05-16T17:53:38Z" type="RELEASED">1.0</ddi:version>
              </ddi:verStmt>
            </ddi:citation>
            <ddi:dataAccs>
              <ddi:useStmt>
                <ddi:restrctn>CC0 Waiver</ddi:restrctn>
              </ddi:useStmt>
            </ddi:dataAccs>
          </ddi:stdyDscr>
        </ddi:codebook>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:dmdSec ID="dmdSec_84990" CREATED="2018-09-20T16:40:16" STATUS="original">
    <mets:mdRef LABEL="relocation2011-ddi.xml" xlink:href="relocation2011/relocation2011-ddi.xml" MDTYPE="DDI" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
  </mets:dmdSec>
  <mets:dmdSec ID="dmdSec_950486" CREATED="2018-09-20T16:40:16" STATUS="original">
    <mets:mdRef LABEL="RELOCATION_FINAL_CANADA_738TOTAL-ddi.xml" xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTAL-ddi.xml" MDTYPE="DDI" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
  </mets:dmdSec>
  <mets:fileSec>
    <mets:fileGrp USE="metadata">
      <mets:file ID="file-9182bfce-af41-4b22-a744-8dfee7d7f4b4" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350">
        <mets:FLocat xlink:href="relocation2011/relocation2011-ddi.xml" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-00d53397-00d1-48d6-828a-7bef80816abd" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350">
        <mets:FLocat xlink:href="relocation2011/relocation2011citation-endnote.xml" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-4245ef11-46aa-4cc0-9819-3506a4058699" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350">
        <mets:FLocat xlink:href="relocation2011/relocation2011citation-ris.ris" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-08e571ef-76bb-4b77-b252-0c3485e8211b" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTAL-ddi.xml" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-0b3b94b3-bfd7-493b-b0fd-ef8a819c2900" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTALcitation-ris.ris" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-18332edc-b62c-4a92-9109-f7e7b3c2dba1" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTALcitation-endnote.xml" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-03b67e7d-42e2-457a-a7b6-e2827445edfc" GROUPID="Group-03b67e7d-42e2-457a-a7b6-e2827445edfc">
        <mets:FLocat xlink:href="metadata/dataset.json" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
    <mets:fileGrp USE="derivative">
      <mets:file ID="file-ca77e051-9210-4f6e-a6be-3a0b705334fc" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTAL.tab" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-4f1e1937-81bf-4018-8146-ece7b53287dc" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTAL.RData" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-3b2154fe-e873-4f18-9231-0b97b94f7fd3" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350">
        <mets:FLocat xlink:href="relocation2011/relocation2011.RData" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-97fe8de7-5cf6-45ac-8a45-f530252402c4" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350">
        <mets:FLocat xlink:href="relocation2011/relocation2011.tab" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
    <mets:fileGrp USE="original">
      <mets:file ID="file-a3cc2aba-7dcc-4f37-9b01-acf745b279e8" GROUPID="Group-a3cc2aba-7dcc-4f37-9b01-acf745b279e8" CHECKSUM="235c918a8eaff0f65a8044e81a5c1ca8" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL/RELOCATION_FINAL_CANADA_738TOTAL.csv" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-c629b185-ebf4-4a01-aaa0-a9de6e43d667" GROUPID="Group-c629b185-ebf4-4a01-aaa0-a9de6e43d667" CHECKSUM="249fe0b2a4f60446543cfa07a33187df" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="relocation2011.dat" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-bdbcd686-9b07-44be-8876-cc4ba2ceb104" GROUPID="Group-bdbcd686-9b07-44be-8876-cc4ba2ceb104" CHECKSUM="fbfd3e8d1122106e3c0f8ee09afcd6fc" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="relocation2011.sps" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-854fb85f-ae45-4ee5-9815-c86ee70f8350" GROUPID="Group-854fb85f-ae45-4ee5-9815-c86ee70f8350" CHECKSUM="187999778dfe955ca8856276e7fd64a0" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="relocation2011/relocation2011.tab" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-1d1a0625-5807-470b-a952-7d49a37fde69" GROUPID="Group-1d1a0625-5807-470b-a952-7d49a37fde69" CHECKSUM="f759178d0481e04c5f8da7cab5392826" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="30_CFLQ_271_13-3-13_1524%5B1%5D.pdf" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-4e78bbf8-ae0d-43ed-a935-814d85cc531d" GROUPID="Group-4e78bbf8-ae0d-43ed-a935-814d85cc531d" CHECKSUM="0b62956fe7244a59c4f2358494b71da2" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="RELOCATION_FINAL_CANADA_738TOTAL.xls" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-31537993-cab6-47a8-871b-037bd545b841" GROUPID="Group-31537993-cab6-47a8-871b-037bd545b841" CHECKSUM="ed3bc550febecd2cbd90e056223c92c3" CHECKSUMTYPE="MD5">
        <mets:FLocat xlink:href="relocation-user-guide.pdf" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
    <mets:div TYPE="Directory" LABEL="Canadian Relocation Cases: Heading Towards Guidelines, 2011 [test]" DMDID="dmdSec_736206 dmdSec_196225">
      <mets:div TYPE="Item" LABEL="30_CFLQ_271_13-3-13_1524%5B1%5D.pdf">
        <mets:fptr FILEID="file-1d1a0625-5807-470b-a952-7d49a37fde69"/>
      </mets:div>
      <mets:div TYPE="Item" LABEL="relocation2011.dat">
        <mets:fptr FILEID="file-c629b185-ebf4-4a01-aaa0-a9de6e43d667"/>
      </mets:div>
      <mets:div TYPE="Item" LABEL="relocation2011.sps">
        <mets:fptr FILEID="file-bdbcd686-9b07-44be-8876-cc4ba2ceb104"/>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="relocation2011">
        <mets:div TYPE="Item" LABEL="relocation2011.tab">
          <mets:fptr FILEID="file-854fb85f-ae45-4ee5-9815-c86ee70f8350"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="relocation2011.RData">
          <mets:fptr FILEID="file-3b2154fe-e873-4f18-9231-0b97b94f7fd3"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="relocation2011.tab" DMDID="dmdSec_84990">
          <mets:fptr FILEID="file-97fe8de7-5cf6-45ac-8a45-f530252402c4"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="relocation2011-ddi.xml">
          <mets:fptr FILEID="file-9182bfce-af41-4b22-a744-8dfee7d7f4b4"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="relocation2011citation-endnote.xml">
          <mets:fptr FILEID="file-00d53397-00d1-48d6-828a-7bef80816abd"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="relocation2011citation-ris.ris">
          <mets:fptr FILEID="file-4245ef11-46aa-4cc0-9819-3506a4058699"/>
        </mets:div>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="RELOCATION_FINAL_CANADA_738TOTAL">
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.csv">
          <mets:fptr FILEID="file-a3cc2aba-7dcc-4f37-9b01-acf745b279e8"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.RData">
          <mets:fptr FILEID="file-4f1e1937-81bf-4018-8146-ece7b53287dc"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.tab" DMDID="dmdSec_950486">
          <mets:fptr FILEID="file-ca77e051-9210-4f6e-a6be-3a0b705334fc"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL-ddi.xml">
          <mets:fptr FILEID="file-08e571ef-76bb-4b77-b252-0c3485e8211b"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTALcitation-endnote.xml">
          <mets:fptr FILEID="file-18332edc-b62c-4a92-9109-f7e7b3c2dba1"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTALcitation-ris.ris">
          <mets:fptr FILEID="file-0b3b94b3-bfd7-493b-b0fd-ef8a819c2900"/>
        </mets:div>
      </mets:div>
      <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.xls">
        <mets:fptr FILEID="file-4e78bbf8-ae0d-43ed-a935-814d85cc531d"/>
      </mets:div>
      <mets:div TYPE="Item" LABEL="relocation-user-guide.pdf">
        <mets:fptr FILEID="file-31537993-cab6-47a8-871b-037bd545b841"/>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="metadata">
        <mets:div TYPE="Item" LABEL="dataset.json">
          <mets:fptr FILEID="file-03b67e7d-42e2-457a-a7b6-e2827445edfc"/>
        </mets:div>
      </mets:div>
    </mets:div>
  </mets:structMap>
  <mets:structMap ID="structMap_2" LABEL="Normative Directory Structure" TYPE="logical">
    <mets:div TYPE="Directory" LABEL="Canadian Relocation Cases: Heading Towards Guidelines, 2011 [test]">
      <mets:div TYPE="Item" LABEL="30_CFLQ_271_13-3-13_1524%5B1%5D.pdf"/>
      <mets:div TYPE="Item" LABEL="relocation2011.dat"/>
      <mets:div TYPE="Item" LABEL="relocation2011.sps"/>
      <mets:div TYPE="Directory" LABEL="relocation2011">
        <mets:div TYPE="Item" LABEL="relocation2011.tab"/>
        <mets:div TYPE="Item" LABEL="relocation2011.RData"/>
        <mets:div TYPE="Item" LABEL="relocation2011.tab"/>
        <mets:div TYPE="Item" LABEL="relocation2011-ddi.xml"/>
        <mets:div TYPE="Item" LABEL="relocation2011citation-endnote.xml"/>
        <mets:div TYPE="Item" LABEL="relocation2011citation-ris.ris"/>
      </mets:div>
      <mets:div TYPE="Directory" LABEL="RELOCATION_FINAL_CANADA_738TOTAL">
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.csv"/>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.RData"/>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.tab"/>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL-ddi.xml"/>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTALcitation-endnote.xml"/>
        <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTALcitation-ris.ris"/>
      </mets:div>
      <mets:div TYPE="Item" LABEL="RELOCATION_FINAL_CANADA_738TOTAL.xls"/>
      <mets:div TYPE="Item" LABEL="relocation-user-guide.pdf"/>
      <mets:div TYPE="Directory" LABEL="metadata">
        <mets:div TYPE="Item" LABEL="dataset.json"/>
      </mets:div>
    </mets:div>
  </mets:structMap>
</mets:mets>
```
Look for: `30_CFLQ_271_13-3-13_1524%5B1%5D.pdf`

**Comment by ross-spencer** [comment]
Archivematica requirements need to be updated to metsrw 0.2.2 to make sure that this fix is included.

**Comment by ablwr** [comment]
AM was updated, but I am still not able to parse the Dataverse data when a filename contains brackets. Testing on qa/1.8 Bionic.

**Comment by ross-spencer** [comment]
Hi @ablwr, to help others recreate this, providing the name of the dataset will be useful. Also, if it is failing in Archivematica and you look up the `failed` directory for the transfer's metadata folder, and access `dataset.json` you'll find a doi field under a persistent identifiers field: `    "persistentUrl": "https://doi.org/10.5072/FK2/WZTJWN",`. We can just link this back to specific failing datasets.

**Comment by ross-spencer** [comment]
Hmm, @ablwr I think if it is this one: http://am18bionic.qa.archivematica.org/tasks/180952d1-8ca2-44c9-9f3c-ec302eb2f7ec/ it is a different issue: https://github.com/archivematica/Issues/issues/211 

:\ 

The last lines of the logs are:

```
parsedataverse_v0.0: ERROR     2018-10-09 02:33:58,491  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:86  Could not find file type: 'Item' in the database: relocation2011.RData. Checksum: 'None'
parsedataverse_v0.0: ERROR     2018-10-09 02:33:58,491  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:247  Exiting. Returning the database objects for our Dataverse files has failed.
Exiting. Returning the database objects for our Dataverse files has failed.Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 277, in call
    job.set_status(init_parse_dataverse_mets(job))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 264, in init_parse_dataverse_mets
    return parse_dataverse_mets(job, transfer_dir, transfer_uuid)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 248, in parse_dataverse_mets
    raise ParseDataverseError(no_map)
ParseDataverseError: Exiting. Returning the database objects for our Dataverse files has failed.
```

But if you inspect the failed SIP, it's because the file with the extension called `rdata` isn't there, but we're not entirely sure why, other than it seems to be an issue with the Dataverse config. 

One way we test this might be a new dataset in the demodv here: https://demodv.scholarsportal.info/dataverse/archivematica - I'll get our details into LastPass for you :+1:

**Comment by ablwr** [comment]
Oh, I should have emphasized I was using the same test object as you, above.

**Comment by ross-spencer** [comment]
@ablwr no problem. I should have written better guidance for those testing.

Given that we're not expecting this to pass, then you can create your own transfer pretty easily, but also, you can modify the storage service parameters, or create a new Dataverse location.

In there, we have other sets with square brackets in:

![image](https://user-images.githubusercontent.com/1880412/46676017-4a379880-cba5-11e8-90b9-f7bd11be38ec.png)

The Storage Service will look like:

![image](https://user-images.githubusercontent.com/1880412/46676101-72bf9280-cba5-11e8-82cf-d1acab8f4a6b.png)

For that location. 

Any of those datasets *should* go through... but it depends. We know we're still getting failures for some, e.g. when in a Draft state, or some with strange restrictions. There should be tickets open for most permutations of error we've seen so far.

**Comment by ablwr** [comment]
Good news! Brackets become `_`!
