### ISSUE TITLE
Problem: acceptance-tests are not working on qa/1.x

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#193]
**Expected behaviour**
Acceptance tests should pass on qa/1.x

**Current behaviour**
The tests start, but they always fail

**Steps to reproduce**
Run automated tests against a qa/1.x deployment

**Your environment (version of Archivematica, OS version, etc)**
AM qa/1.x SS qa/0.x
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by scollazo** [comment]
I think that the new "Auto approve" checkbox broke the tests

**Comment by sromkey** [comment]
Labeling as high serverity because this will become a blocker for regression testing.

**Comment by ross-spencer** [comment]
In case it is useful, following my PR for #131, I do see a few other different behaviors. Using the Makefile default with Docker-compose, I get the following message:

```
docker-compose -f docker-compose.yml -f docker-compose.acceptance-tests.yml  run --rm -e HEADLESS=1 --no-deps archivematica-acceptance-tests /usr/local/bin/behave --tags=mo-aip-reingest --no-skipped -v --stop -D driver_name=Firefox -D ssh_accessible=no -D am_url=http://nginx/ -D am_username=test -D am_password=test -D am_api_key=test -D am_version=1.7 -D ss_url=http://nginx:8000/ -D ss_username=test -D ss_password=test -D ss_api_key=test -D transfer_source_path=archivematica/archivematica-sampledata/TestTransfers/acceptance-tests -D home=archivematica
Loading config defaults from "./tox.ini"
Loading config defaults from "./behave.ini"
Using defaults:
          color True
  show_snippets True
   show_skipped True
        dry_run False
    show_source True
   show_timings True
 stdout_capture False
 stderr_capture False
    log_capture True
 logging_format %(levelname)s:%(name)s:%(message)s
  logging_level 20
  steps_catalog False
        summary True
          junit False
          stage None
       userdata {}
 default_format pretty
   default_tags 
scenario_outline_annotation_schema {name} -- @{row.id} {examples.name}
more_formatters {}
Using default path "./features"
Trying base directory: /home/artefactual/acceptance-tests/features
@mo-aip-reingest
Feature: Metadata-only AIP re-ingest # features/core/metadata-only-aip-reingest.feature:19
  Users want to be able to take an existing AIP and perform a metadata-only
  re-ingest on it so that they can add metadata to it and confirm that those
  metadata are in the re-ingested AIP's METS file.
  Scenario: Isla creates an AIP, and then performs a metadata-only re-ingest on it, adds metadata to it, and confirms that her newly added metadata are in the modified METS file.   # features/core/metadata-only-aip-reingest.feature:24
    Given that the user has ensured that the default processing config is in its default state                                                                                       # features/steps/steps.py:43 4.637s
      Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 46, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 469, in ensure_default_processing_config_in_default_state
          choice_value='None')
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 377, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 120, in select_by_visible_text
          self._setSelected(opt)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 212, in _setSelected
          option.click()
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
          self._execute(Command.CLICK_ELEMENT)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
          return self._parent.execute(command, params)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
          self.error_handler.check_response(response)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.ElementClickInterceptedException: Message: Element <select id="id_70fc7040-d4fb-4d19-a0e6-792387ca1006" class="form-control" name="70fc7040-d4fb-4d19-a0e6-792387ca1006"> is not clickable at point (1112.9500274658203,15.199996948242188) because another element <div class="container-fluid"> obscures it

    And the reminder to add metadata is enabled                                                                                                                                      # None
```

Running that same test from the acceptance-tests repository:

```
@mo-aip-reingest
Feature: Metadata-only AIP re-ingest # features/core/metadata-only-aip-reingest.feature:19
  Users want to be able to take an existing AIP and perform a metadata-only
  re-ingest on it so that they can add metadata to it and confirm that those
  metadata are in the re-ingested AIP's METS file.
  Scenario: Isla creates an AIP, and then performs a metadata-only re-ingest on it, adds metadata to it, and confirms that her newly added metadata are in the modified METS file.   # features/core/metadata-only-aip-reingest.feature:24
    Given that the user has ensured that the default processing config is in its default state                                                                                       # features/steps/steps.py:43
    And the reminder to add metadata is enabled                                                                                                                                      # features/steps/steps.py:49
    When a transfer is initiated on directory ~/archivematica-sampledata/SampleTransfers/Images/pictures                                                                             # features/steps/steps.py:381
    And the user waits for the "Assign UUIDs to directories?" decision point to appear and chooses "No" during transfer                                                              # features/steps/steps.py:221
    And the user waits for the "Select file format identification command" decision point to appear and chooses "Identify using Fido" during transfer                                # features/steps/steps.py:221
    And the user waits for the "Perform policy checks on originals?" decision point to appear and chooses "No" during transfer                                                       # features/steps/steps.py:221
      Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 225, in step_impl
          context, microservice_name, unit_type)
        File "/home/ross-spencer/git/artefactual-labs/am/src/archivematica-acceptance-tests/features/steps/utils.py", line 28, in wait_for_decision_point_to_appear
          microservice_name, uuid_val, unit_type=unit_type)
        File "/home/ross-spencer/git/artefactual-labs/am/src/archivematica-acceptance-tests/amuser/am_browser_transfer_ingest_ability.py", line 51, in await_decision_point
```
