### ISSUE TITLE
Problem: API incorrectly reports 'copy successful' for a non-existent transfer directory

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#196]
**Expected behaviour**

More feedback when initializing a transfer, so if a user accidentally attempts to start a transfer from a directory on the storage service that doesn't exist, they can react to that and work with it. Further, because a placeholder directory is placed inside the Archivematica active transfers watched directory then there is another action a user has to perform to manage the 'transfer' that Archivematica thinks is there.

**Current behaviour**

_Logs:_
```
archivematica-storage-service_1  | DEBUG     2018-09-22 08:33:20  locations.models.space:space:posix_move:281:  posix_move: source_path: home/archivematica/archivematica-sampledata/api-demo/doesnt-exist/.
archivematica-storage-service_1  | DEBUG     2018-09-22 08:33:20  locations.models.space:space:posix_move:282:  posix_move: destination_path: /var/archivematica/sharedDirectory/tmp/tmpvdYB7W/api-issue-1/.
archivematica-storage-service_1  | DEBUG     2018-09-22 08:33:20  locations.models.space:space:posix_move:283:  posix_move: destination_space.path: /
archivematica-storage-service_1  | INFO      2018-09-22 08:33:20  locations.models.space:space:move_rsync:469:  Moving from /home/archivematica/archivematica-sampledata/api-demo/doesnt-exist/. to /var/archivematica/sharedDirectory/tmp/tmpvdYB7W/api-issue-1/.
archivematica-storage-service_1  | DEBUG     2018-09-22 08:33:20  locations.models.space:space:move_rsync:483:  os.rename failed, trying with normalized paths
archivematica-storage-service_1  | DEBUG     2018-09-22 08:33:20  locations.models.space:space:move_rsync:492:  os.rename failed, falling back to rsync. Source: /home/archivematica/archivematica-sampledata/api-demo/doesnt-exist; Destination: /var/archivematica/sharedDirectory/tmp/tmpvdYB7W/api-issue-1
archivematica-storage-service_1  | INFO      2018-09-22 08:33:20  locations.models.space:space:move_rsync:499:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist/.', '/var/archivematica/sharedDirectory/tmp/tmpvdYB7W/api-issue-1/.']
archivematica-storage-service_1  | WARNING   2018-09-22 08:33:20  locations.models.space:space:move_rsync:507:  Rsync failed with status 23: sending incremental file list
archivematica-storage-service_1  | rsync: change_dir "/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist" failed: No such file or directory (2)
archivematica-storage-service_1  | delta-transmission disabled for local transfer or --whole-file
archivematica-storage-service_1  | total: matches=0  hash_hits=0  false_alarms=0 data=0
archivematica-storage-service_1  | 
archivematica-storage-service_1  | sent 20 bytes  received 79 bytes  198.00 bytes/sec
archivematica-storage-service_1  | total size is 0  speedup is 0.00
archivematica-storage-service_1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
archivematica-storage-service_1  | 
archivematica-storage-service_1  | ERROR     2018-09-22 08:33:20  locations.models.async_manager:async_manager:wrapper:122:  Task threw an error: Rsync failed with status 23: sending incremental file list
archivematica-storage-service_1  | rsync: change_dir "/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist" failed: No such file or directory (2)
archivematica-storage-service_1  | delta-transmission disabled for local transfer or --whole-file
archivematica-storage-service_1  | total: matches=0  hash_hits=0  false_alarms=0 data=0
archivematica-storage-service_1  | 
archivematica-storage-service_1  | sent 20 bytes  received 79 bytes  198.00 bytes/sec
archivematica-storage-service_1  | total size is 0  speedup is 0.00
archivematica-storage-service_1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/async_manager.py", line 119, in wrapper
archivematica-storage-service_1  |     value = task_fn(*args, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 471, in task
archivematica-storage-service_1  |     self._move_files_between_locations(files, origin_location, destination_location)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 379, in _move_files_between_locations
archivematica-storage-service_1  |     package=None
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/space.py", line 293, in posix_move
archivematica-storage-service_1  |     source_path, abs_destination_path, destination_space, package)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/local_filesystem.py", line 62, in posix_move
archivematica-storage-service_1  |     return self.space.move_rsync(source_path, destination_path, try_mv_local=True)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/space.py", line 508, in move_rsync
archivematica-storage-service_1  |     raise StorageException(s)
archivematica-storage-service_1  | StorageException: Rsync failed with status 23: sending incremental file list
archivematica-storage-service_1  | rsync: change_dir "/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist" failed: No such file or directory (2)
archivematica-storage-service_1  | delta-transmission disabled for local transfer or --whole-file
archivematica-storage-service_1  | total: matches=0  hash_hits=0  false_alarms=0 data=0
archivematica-storage-service_1  | 
archivematica-storage-service_1  | sent 20 bytes  received 79 bytes  198.00 bytes/sec
archivematica-storage-service_1  | total size is 0  speedup is 0.00
archivematica-storage-service_1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
archivematica-storage-service_1  | 
```
_API Call:_
```
http --pretty=format \
    -f \
    POST "http://127.0.0.1:62080/api/transfer/start_transfer/" \
    Authorization:"ApiKey test:test" \
    name="api-issue-1" \
    type="standard" \
    paths[]="\
    [$(echo -n '6b82c1f5-2b87-49ba-8e5f-947759201518:/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist' \
    | base64 -w 0)]"
```
_API Response:_
```
POST /api/transfer/start_transfer/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: ApiKey test:test
Connection: keep-alive
Content-Length: 197
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: 127.0.0.1:62080
User-Agent: HTTPie/0.9.8

name=api-issue-1&type=standard&paths%5B%5D=++++%5BNmI4MmMxZjUtMmI4Ny00OWJhLThlNWYtOTQ3NzU5MjAxNTE4Oi9ob21lL2FyY2hpdmVtYXRpY2EvYXJjaGl2ZW1hdGljYS1zYW1wbGVkYXRhL2FwaS1kZW1vL2RvZXNudC1leGlzdA%3D%3D%5D

HTTP/1.1 200 OK
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Sat, 22 Sep 2018 15:44:08 GMT
Server: nginx/1.14.0
Transfer-Encoding: chunked
Vary: Accept-Language, Cookie

{
    "message": "Copy successful.",
    "path": "/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/api-issue-1/"
}
```

_Appearance in Archivematica:_

![image](https://user-images.githubusercontent.com/1880412/45918927-94094a80-be53-11e8-9311-73a89689c4ea.png)

_Tree output:_
```
root@artefactual:/tmp/am-pipeline-data/watchedDirectories/activeTransfers/standardTransfer# tree
.
├── api-issue-1
```

**Steps to reproduce**

Make an API call to start transfer with all the fields correct except for a purposely misnamed directory.

This issue manifests itself differently with the V2 Beta endpoint, e.g.:
```
http -v --pretty=format \
>     POST 127.0.0.1:62080/api/v2beta/package \
>     "Authorization: ApiKey test:test" \
>     processing_config=automated \
>     path=$(echo -n '/home/archivematica/archivematica-sampledata/api-demo/doesnt-exist' | base64 -w 0) \
>     name=v2_beta_endpoint_issue
POST /api/v2beta/package HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: ApiKey test:test
Connection: keep-alive
Content-Length: 168
Content-Type: application/json
Host: 127.0.0.1:62080
User-Agent: HTTPie/0.9.8

{
    "name": "v2_beta_endpoint_issue",
    "path": "L2hvbWUvYXJjaGl2ZW1hdGljYS9hcmNoaXZlbWF0aWNhLXNhbXBsZWRhdGEvYXBpLWRlbW8vZG9lc250LWV4aXN0",
    "processing_config": "automated"
}

HTTP/1.1 202 ACCEPTED
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Sat, 22 Sep 2018 16:02:03 GMT
Server: nginx/1.14.0
Transfer-Encoding: chunked
Vary: Accept-Language, Cookie

{
    "id": "052a85de-098e-4728-a010-4dfa7b2bf3c8"
}
```
The UUID being written to the database:
```
mysql> use MCP;
Database changed
mysql> select * from Transfers where transferUUID='052a85de-098e-4728-a010-4dfa7b2bf3c8';
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
| transferUUID                         | currentLocation | type | accessionID | sourceOfAcquisition | typeOfTransfer | description | notes | hidden | transferMetadataSetRowUUID | dirUUIDs | access_system_id |
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
| 052a85de-098e-4728-a010-4dfa7b2bf3c8 |                 |      |             |                     |                |             |       |      0 | NULL                       |        0 |                  |
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
1 row in set (0.00 sec)
```

**Your environment (version of Archivematica, OS version, etc)**

Docker-compose. Archivematica `qa/0.x`. API calls made using HTTPie.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
