### ISSUE TITLE
Problem: A Dataverse transfer has the potential to describe a file that isn't there if Dataverse doesn't return all anticipated files

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#211]
**Expected behaviour**
When a Dataverse transfer includes a tabular data file, Archivematica requests the 'bundle' of related files from Dataverse. Dataverse returns a .zip package with all of the related files, including the original tabular data file as well as derivatives and metadata files created by Dataverse. 
Archivematica creates a Dataverse METS file that describes all the files provided as well as the type (original, metadata, derivative). 

Archivematica should only describe files that are actually present. (we have not actually specified exactly what to do when Dataverse doesn't return all the files it should, so that needs clarification... I would assume AM should remove any descriptions of files not physically present, and perhaps throw some kind of warning message that an expected file was not included). 

**Current behaviour**
When processing the "Canadian Relocations" test dataset, the Dataverse METs describes an RData file that is not actually present in the dataset. The following shows which files are in the Transfer: 

![screenshot from 2018-09-26 16-48-05](https://user-images.githubusercontent.com/17187309/46112082-4ecc7c00-c1b7-11e8-97f5-3847de7ffbba.png)

The transfer then fails at "Parse Dataverse METs" with the following error: 
```
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,852  archivematica.mcp.client.parse_dataverse_mets.init_parse_dataverse_mets:263  Parse Dataverse METS with dir: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/CadRelocations_beta1-94fc1ada-7414-4f9c-83da-2b069bad6204/' and transfer uuid: 94fc1ada-7414-4f9c-83da-2b069bad6204
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,888  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:61  Looking for file type: 'Item' using relative path: %transferDirectory%objects/relocation2011.dat
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,899  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:61  Looking for file type: 'Item' using relative path: %transferDirectory%objects/relocation2011.sps
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,901  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:61  Looking for file type: 'Item' using relative path: %transferDirectory%objects/relocation2011/relocation2011.RData
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,903  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:67  Could not find file type: 'Item' in the database: relocation2011/relocation2011.RData
parsedataverse_v0.0: INFO      2018-09-26 14:45:38,903  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:79  Looking for file type: 'Item' using base name: %transferDirectory%objects/relocation2011.RData
parsedataverse_v0.0: ERROR     2018-09-26 14:45:38,905  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:86  Could not find file type: 'Item' in the database: relocation2011.RData. Checksum: 'None'
parsedataverse_v0.0: ERROR     2018-09-26 14:45:38,905  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:247  Exiting. Returning the database objects for our Dataverse files has failed.
Exiting. Returning the database objects for our Dataverse files has failed.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 277, in call
    job.set_status(init_parse_dataverse_mets(job))
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 264, in init_parse_dataverse_mets
    return parse_dataverse_mets(job, transfer_dir, transfer_uuid)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 248, in parse_dataverse_mets
    raise ParseDataverseError(no_map)
ParseDataverseError: Exiting. Returning the database objects for our Dataverse files has failed.
```

**Steps to reproduce**
Need to retrieve the Canadian Relocations dataset in particular for now, until we identify exactly what is causing this. 

**Your environment (version of Archivematica, OS version, etc)**
Tested with latest version of qa/1.x on a local docker / am.git deployment, as well as the OCUL QA environment. (day of beta release candidate)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by joel-simpson** [comment]
A further comment on which files I expect to see or not. We should probably document this logic properly in the wiki (I'm not entirely clear what logic AM is actually using, this is just what I _think_ the logic should be). 

When the dataset is first downloaded, the dataset.json file lists all the files provided. For each file we see an entry like this: 
```
        "dataFile": {
          "UNF": "UNF:6:dLu0AaOeqoOlDbGTwUrWjA==",
          "checksum": {
            "type": "MD5",
            "value": "235c918a8eaff0f65a8044e81a5c1ca8"
          },
          "contentType": "text/tab-separated-values",
          "description": "CSV file",
          "filename": "RELOCATION_FINAL_CANADA_738TOTAL.tab",
          "filesize": 306311,
          "id": 1011,
          "md5": "235c918a8eaff0f65a8044e81a5c1ca8",
          "originalFileFormat": "text/csv",
          "originalFormatLabel": "Comma Separated Values",
          "rootDataFileId": -1,
          "storageIdentifier": "1636a128dff-7517f048c790"
        },
        "datasetVersionId": 268,
        "description": "CSV file",
        "label": "RELOCATION_FINAL_CANADA_738TOTAL.tab",
        "restricted": false,
        "version": 2
      },
```
I believe AM should be looking for an `originalFileFormat` field with a value. If that field doesn't existthen there is no tabular data bundle to download. If it exists then that file that file is tabular data and SS requests the bundle. (and/or `"contentType": "text/tab-separated-values"` should be used? or `"originalFormatLabel": "UNKNOWN"` could be used... it seems this is always "UNKNOWN" when no `originalFileFormat` is present)

In this particular case I'm not sure what is happening. The file entry above is for a tabular data file, and all of the derivatives you'd expect are there (e.g. a RELOCATION_FINAL_CANADA_738TOTAL.RData) exists.
In the error from Parse Dataverse METs shown above, AM is looking for `relocation2011.RData`
I would not expect this to exist, because all of the `relocation2011` files in the dataset.json have no "originalFileFormat": "text/csv" field (and they have `"originalFormatLabel": "UNKNOWN"`). 
BUT, we still see metadata files with relocation2011 that are not present in the UI of Dataverse. So it's like we managed to retrieve metadata files but not an entire bundle?

**Comment by joel-simpson** [comment]
Thanks @ross-spencer that is very helpful. So it seems dataverse is not returning all the files we would expect it to. Right now, the dataset fails during ingest in Archivematica, which is a better outcome than it completing but having incorrect entries in the METS file (which is what it did previously). 

I agree with your suggestion for renaming this ticket about providing a warning... although I might take it up a level and look at how we validate or verify a dataverse transfer generally (rather than just dealing with a bundle being 'incomplete'). That would need a bit more thought about requirements etc... but at least two scenarios we need to validate: 
- whenever the dataset.json does not describe the files actually retrieved from Dataverse (with some nuance for bundles given they are not fully described in dataset.json)
- whenever a bundle is retrieved but the actual files don't align with the rules / expectations for what a bundle should include (i.e. we currently expect .RData, .bib etc. etc.)
We might think of other scenarios (e.g. when checksums haven't been provided). 

I'm not as sure about the second suggestion... we could look to get more info from Dataverse for datesets with errors, but I think that's only important to consider if we can't define clear rules as suggested above. 

The next question is; should processing continue if there are warnings thrown?  We should see what the Scholar's Portal team think. My own view is that it would make sense to "preserve what you can" (i.e. complete processing with whatever files you get; but making sure that the METS only describes actual files received). Users could then decide whether to re-process or not based on the warnings. In many cases it may not be that important that a Dataverse derivative isn't there... as long as all of the original files are, then the dataset as originally created is preserved.

**Comment by mInnes-archives** [comment]
I think this is the right issue to bump. I believe I've identified the cause of this problem.

UVic has run into some issues with Dataverse integration (via Borealis), specifically with regards to Dataverse-generated RData files for tabular data in cases where the original format isn't RData. As described above, these files are listed as being part of the package in the metadata, but they aren't actually there, so the transfer fails.

It seems that Dataverse generates these RData deravitives only when they are _requested_ by a user rather than at the point of ingest like it does for the various metadata formats, for example. Therefore, if a user has never requested to download the RData file, it won't be included in the transfer package, dispite there being metadata that says otherwise.

This is easy enough to prove:

- Identify the missing RData file of a failed transfer
- Navigate to this problem dataset on Dataverse
- Download the tabular data file that causing the failure as RData
- Try the transfer again
- Transfer now works

Perhaps if Archivematica could request the RData file temporarily prior to accepting the package, triggering generation by Dataverse, that could address the issue. Admittedly, this seems a bit hacky. I feel that a more elegant solution would have to be Dataverse-based, such as Dataverse providing an option to generate all derivatives at the point of ingest or just not pre-generating the metadata for these by-request derivatives.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
