### ISSUE TITLE
Problem: Dataverse datasets including files with diacritics cannot be processed

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#256]
**Expected behaviour**

Datasets from Dataverse can be processed in Archivematica, irregardless of character encoding or diacritics.

**Current behaviour**

Verify transfer compliance > Convert Dataverse Structure fails when trying to process a file with an é in the filename.

Fuller error:
```
convertdataversestructure_v0.0: INFO      2018-10-09 22:48:23,707  archivematica.mcp.client.convert_dataverse_struct.init_convert_dataverse:532  Convert Dataverse Structure with dir: '/var/archivematica/sharedDirectory/currentlyProcessing/ab-bracket-test/'
convertdataversestructure_v0.0: INFO      2018-10-09 22:48:23,708  archivematica.mcp.client.convert_dataverse_struct.convert_dataverse_to_mets:459  Convert Dataverse structure called with '/var/archivematica/sharedDirectory/currentlyProcessing/ab-bracket-test/' unit directory
convertdataversestructure_v0.0: INFO      2018-10-09 22:48:23,708  archivematica.mcp.client.convert_dataverse_struct.load_md_and_return_json:444  Metadata directory exists True
'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 546, in call
    job.set_status(init_convert_dataverse(job))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 533, in init_convert_dataverse
    return convert_dataverse_to_mets(job, unit_path=transfer_dir)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 497, in convert_dataverse_to_mets
    job, sip, dataset_md_latest, contact_information)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 374, in add_dataset_files_to_md
    bundle = create_bundle(job, file_json)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 194, in create_bundle
    .format(tabfile_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
```
**Steps to reproduce**

Try adding a Dataverse dataset with an accent. [This one](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FSDXQG2) should do, and the accent on one of the files is an interesting Unicode character encoding. It should fail right away.

**Your environment (version of Archivematica, OS version, etc)**

qa/1.x (pre-1.8) Ubuntu 18.04

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
For context, I think this commit in [`metsrw`](https://github.com/artefactual-labs/mets-reader-writer/commit/1a6f91308d60221afbf16a13778c2d2362bcfeb7) will take care of most of the changes required here, and we'd only need some minor changes to the client script but I haven't tested this assumption yet.

**Comment by adornetejr** [comment]
Same error here, but is a ç character.

`convertdataversestructure_v0.0: INFO      2020-06-05 19:55:00,241  archivematica.mcp.client.convert_dataverse_struct.init_convert_dataverse:582  Convert Dataverse Structure with dir: '/var/archivematica/sharedDirectory/currentlyProcessing/1'
convertdataversestructure_v0.0: INFO      2020-06-05 19:55:00,241  archivematica.mcp.client.convert_dataverse_struct.convert_dataverse_to_mets:508  Convert Dataverse structure called with '/var/archivematica/sharedDirectory/currentlyProcessing/1' unit directory
convertdataversestructure_v0.0: INFO      2020-06-05 19:55:00,242  archivematica.mcp.client.convert_dataverse_struct.load_md_and_return_json:490  Metadata directory exists True
'ascii' codec can't encode character u'\xe7' in position 13: ordinal not in range(128)Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 596, in call
    job.set_status(init_convert_dataverse(job))
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 583, in init_convert_dataverse
    return convert_dataverse_to_mets(job, unit_path=transfer_dir)
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 540, in convert_dataverse_to_mets
    sip = add_ddi_xml(job, sip, json_metadata, dataset_md_latest)
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 348, in add_ddi_xml
    ddi_root = create_ddi(job, json_metadata, dataset_md_latest)
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 150, in create_ddi
    output_ddi_elems_info(job, ddi_elems)
  File "/src/MCPClient/lib/clientScripts/convert_dataverse_structure.py", line 78, in output_ddi_elems_info
    job.pyprint("{}: {}".format(ddi_k, ddi_v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 13: ordinal not in range(128)`

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
