### ISSUE TITLE
Problem: AIP store fails if PREMIS agent name has accented characters

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#260]
**Expected behaviour**
If the PREMIS agent name has accents or other special characters, it should be written to the METS and the AIP stored as expected.

**Current behaviour**
A PREMIS agent name with characters results in this failure in Store AIP:

```
500 Server Error: INTERNAL SERVER ERROR for url: http://am18centos.qa.archivematica.org:8000/api/v2/async/5/Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 212, in store_aip
    related_package_uuid)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 67, in _create_file
    agents=get_agents_from_db(uuid)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
    ret = wait_for_async(response)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 223, in wait_for_async
    poll_response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://am18centos.qa.archivematica.org:8000/api/v2/async/5/
```

**Steps to reproduce**
- Amend the PREMIS agent name to include accented characters
- Try to create/store an AIP

**Your environment (version of Archivematica, OS version, etc)**
qa/1.x (pre-1.8) on centos

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Hi @sevein I was contemplating this ticket today in the context of another issue, and didn't see your name assigned. I don;t want to crash the party, so here are a few notes I made just in case they're useful:

* Seems to affect pointer files specifically, so a workaround would be for users to avoid compressing AIPs
* `store_aip.py` uses `metsrw` and so it seems likely that it is related to: https://github.com/archivematica/Issues/issues/295 

Storage Service trace:
```
archivematica-storage-service_1_ac61b9c72e84 | INFO      2018-12-21 01:34:32  locations.models.space:space:move_rsync:555:  Moving from /var/archivematica/sharedDirectory/currentlyProcessing/1-8ea629be-6f9a-43b5-99d4-9fce7e51bbd0/1-8ea629be-6f9a-43b5-99d4-9fce7e51bbd0.7z to /var/archivematica/sharedDirectory/www/AIPsStore/8ea6/29be/6f9a/43b5/99d4/9fce/7e51/bbd0/1-8ea629be-6f9a-43b5-99d4-9fce7e51bbd0.7z
archivematica-storage-service_1_ac61b9c72e84 | ERROR     2018-12-21 01:34:32  locations.models.async_manager:async_manager:wrapper:137:  Task threw an error: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128)
archivematica-storage-service_1_ac61b9c72e84 | Traceback (most recent call last):
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
archivematica-storage-service_1_ac61b9c72e84 |     value = task_fn(*args, **kwargs)
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/api/resources.py", line 1042, in task
archivematica-storage-service_1_ac61b9c72e84 |     self._store_bundle(bundle)
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/api/resources.py", line 1005, in _store_bundle
archivematica-storage-service_1_ac61b9c72e84 |     aip_subtype=aip_subtype,
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/models/package.py", line 753, in store_aip
archivematica-storage-service_1_ac61b9c72e84 |     aip_subtype=aip_subtype,
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/models/package.py", line 975, in _store_aip_ensure_pointer_file
archivematica-storage-service_1_ac61b9c72e84 |     aip_subtype=aip_subtype,
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/models/package.py", line 1017, in _create_pointer_file_write_to_disk
archivematica-storage-service_1_ac61b9c72e84 |     package_subtype=aip_subtype,
archivematica-storage-service_1_ac61b9c72e84 |   File "/src/storage_service/locations/models/package.py", line 1501, in create_pointer_file
archivematica-storage-service_1_ac61b9c72e84 |     mets_fs_entry.add_premis_event(event.serialize())
archivematica-storage-service_1_ac61b9c72e84 |   File "/usr/local/lib/python2.7/site-packages/metsrw/plugins/premisrw/premis.py", line 132, in serialize
archivematica-storage-service_1_ac61b9c72e84 |     return data_to_premis(self._data, self.premis_version)
archivematica-storage-service_1_ac61b9c72e84 |   File "/usr/local/lib/python2.7/site-packages/metsrw/plugins/premisrw/premis.py", line 594, in data_to_premis
archivematica-storage-service_1_ac61b9c72e84 |     return _data_to_lxml_el(data, 'premis', nsmap)
archivematica-storage-service_1_ac61b9c72e84 |   File "/usr/local/lib/python2.7/site-packages/metsrw/plugins/premisrw/premis.py", line 489, in _data_to_lxml_el
archivematica-storage-service_1_ac61b9c72e84 |     element, ns, nsmap, element_maker=element_maker, snake=snake))
archivematica-storage-service_1_ac61b9c72e84 |   File "/usr/local/lib/python2.7/site-packages/metsrw/plugins/premisrw/premis.py", line 489, in _data_to_lxml_el
archivematica-storage-service_1_ac61b9c72e84 |     element, ns, nsmap, element_maker=element_maker, snake=snake))
archivematica-storage-service_1_ac61b9c72e84 |   File "/usr/local/lib/python2.7/site-packages/metsrw/plugins/premisrw/premis.py", line 491, in _data_to_lxml_el
archivematica-storage-service_1_ac61b9c72e84 |     args.append(str(element))
archivematica-storage-service_1_ac61b9c72e84 | UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128)
```

`store_aip.py` trace:
```
storeaip_v0.0: WARNING   2018-12-21 09:34:38,854  archivematica.mcp.client.storeAIP.store_aip:215  SIP creation failed: Failure storing file: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128).
SIP creation failed: Failure storing file: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128). See logs for more details.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 216, in store_aip
    raise Exception(errmsg + " See logs for more details.")
Exception: SIP creation failed: Failure storing file: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe1' in position 4: ordinal not in range(128). See logs for more details.
```

**Comment by sevein** [comment]
No problem at all! Thank you.
