### ISSUE TITLE
urllib3 1.24 breaks Vagrant provisioning

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#282]
**Expected behaviour**

Successful provisioning of a development environment following [the installation procedure in the wiki](https://wiki.archivematica.org/Getting_started#Installation).

**Current behaviour**

Provisioning fails in the `archivematica-xenial` playbook, specifically at the **Create Dashboard user and register pipeline on SS** task of the `artefactual.archivematica-src` role. Here's the traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/src/archivematica/src/dashboard/src/installer/management/commands/install.py", line 24, in <module>
    from components import helpers
  File "/vagrant/src/archivematica/src/dashboard/src/components/helpers.py", line 22, in <module>
    import requests
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```
Looking at the `requests` versions included in the repository and its dependencies I found that `urllib3 1.24` was released yesterday and this [relevant issue](https://github.com/urllib3/urllib3/issues/1456) has been recently filed which is probably the cause of this problem.

Unfortunately, I don't understand the playbook setup well enough to pin the `urllib3` package to version `1.23` properly to retry the provisioning, but I wanted to put this on your radar. 

**Steps to reproduce**

Follow [the installation procedure in the wiki](https://wiki.archivematica.org/Getting_started#Installation).

**Your environment (version of Archivematica, OS version, etc)**
- Ubuntu 16.04 host
- Ansible 2.7
- Vagrant 2.1.4
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Hi there! We noticed the same issue a couple of days ago and squeezed a fix in our `qa/1.x` branch as part of the following pull request: https://github.com/artefactual/archivematica/pull/1292.

I've just made the same commit available in `stable/1.7.x` (see https://github.com/artefactual/archivematica/commit/9b8d051acf0b4a7e476146e4f9084a48a9d91bb1), I'm assuming that's the branch you're using?

**Comment by replaceafill** [comment]
Hello @sevein.

I used the master branch of `deploy-pub` and didn't adjust any variables, and yes it seems that [it uses the stable/1.7.x branch](https://github.com/artefactual/deploy-pub/blob/master/playbooks/archivematica-xenial/vars-singlenode-1.7.yml#L6) by default.

I'm running `vagrant up` again which I think will pick up your fix this time, correct?

**Comment by replaceafill** [comment]
@sevein Just wanted to confirm the Vagrant provisioning worked this time:
```
PLAY RECAP *********************************************************************
am-local                   : ok=201  changed=126  unreachable=0    failed=0   
```
I'm trying to get familiar with Archivematica so I can apply for a developer position available in the Artefactual site, so your tip on using the docker compose repository instead is highly appreciated and I'll try it. Closing this issue now.

**Comment by sevein** [comment]
Greeeeeeat news! :clap:
