### ISSUE TITLE
Problem: rebuilding the backlog index resets ingest dates

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#367]
**Expected behaviour**
Rebuilding the backlog index maintains the original transfer dates for the files in backlog. 

**Current behaviour**
The ingest date on the Backlog tab is reset to the re-index date rather than maintaining the original ingest date. 

**Steps to reproduce**

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@mamedin to test this, can you rebuild the backlog index on am110xenial? I've got some items sitting in there from July 10/11.

**Comment by scollazo** [comment]
The command can't be run due to a dependency problem addressed in https://github.com/artefactual/archivematica/pull/1458 : 

<pre>
archivematica@am110xenial:/usr/share/archivematica/dashboard$ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_transfer_backlog
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 29, in <module>
    from pathlib2 import Path
ImportError: No module named pathlib2

</pre>
