### ISSUE TITLE
Problem: AIP Reingest Fails

### ISSUE THREAD

**Issue by joel-simpson** [archivematica/Issues#42]
**Expected behaviour**
When I view an AIP in Archival Storage and select "Metadata Only Reingest", I expect the AIP to be reingested and processed through the Ingest steps successfully. 

**Current behaviour**
The AIP starts the reingest process with the Microservice `Reingest AIP', but the job ` Populate database with reingested AIP data` fails with the following error: 
```
Standard error (stderr)
(1062, "Duplicate entry '028982ed-bac2-48d1-b137-c59774e43478' for key 'PRIMARY'")Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 463, in call
    job.set_status(main(job, args.sip_uuid, args.sip_path))
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 445, in main
    update_files(sip_uuid, files)
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 135, in update_files
    use=file_info['use'],
  File "/src/archivematicaCommon/lib/fileOperations.py", line 88, in addFileToSIP
    insertIntoFiles(fileUUID, filePathRelativeToSIP, date, sipUUID=sipUUID, use=use)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 100, in insertIntoFiles
    File.objects.create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
IntegrityError: (1062, "Duplicate entry '028982ed-bac2-48d1-b137-c59774e43478' for key 'PRIMARY'")
```
**Steps to reproduce**
Select any AIP in Archival storage and then Metadata Only reingest. (I will try testing other types of reingest next)

**Your environment (version of Archivematica, OS version, etc)**
Testing with qa/1.x built on 24 July 2018. Ubuntu with docker. (prometheus qa env)

**Comment by joel-simpson** [comment]
@marktriggs or @payten @jambun would one of you be able to have a look at this today? 
I'm guessing this may be related to the MCP Batching work?

**Comment by joel-simpson** [comment]
I was able to complete a full reingest without errors. 
A partial reingest fails with the same type of error.

**Comment by ross-spencer** [comment]
I don't believe any of these to be related (quick scan) but partial and metadata reingest do seem to be a little less stable in Archivematica than full-reingest: https://github.com/artefactual/archivematica/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+reingest

**Comment by marktriggs** [comment]
Hi @joel-simpson,

So far I haven't had any luck getting my reingest to fail the same way (for a funny sort of definition of "luck".)  Both the metadata reingest and partial reingest are running successfully.

I've been testing this by creating a new transfer/ingest and letting that run through, and then reingesting it from Archival Storage.  Does that match what you've been doing too?

**Comment by marktriggs** [comment]
One additional comment after further reviewing the code: although the `parse_mets_to_db` client script was the one to ultimately fail, it's actually the job of the dashboard to clear out the records associated with the previous SIP ingest prior to running a reingest.  The "Duplicate entry" error above suggests that those rows were still in the DB.

So, it might be worth checking whether the dashboard logged anything incriminating further up in the logs.  It does the delete as soon as you click the "Re-ingest" button in the Archival Storage tab, so if it's going to log anything that's when it would happen.

**Comment by currmie** [comment]
Hi @joel-simpson , AIP reingest (metadata, partial, full) run successfully on my local setup as well.

**Comment by ross-spencer** [comment]
@joel-simpson following the steps in this issue here: https://github.com/archivematica/Issues/issues/43

I can recreate the issue you have with metadata re-ingest. 
```
(1062, "Duplicate entry '2ba045ac-6923-46f3-bc0e-eca525cb8d03' for key 'PRIMARY'")Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 463, in call
    job.set_status(main(job, args.sip_uuid, args.sip_path))
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 445, in main
    update_files(sip_uuid, files)
  File "/src/MCPClient/lib/clientScripts/parse_mets_to_db.py", line 135, in update_files
    use=file_info['use'],
  File "/src/archivematicaCommon/lib/fileOperations.py", line 88, in addFileToSIP
    insertIntoFiles(fileUUID, filePathRelativeToSIP, date, sipUUID=sipUUID, use=use)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 100, in insertIntoFiles
    File.objects.create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
IntegrityError: (1062, "Duplicate entry '2ba045ac-6923-46f3-bc0e-eca525cb8d03' for key 'PRIMARY'")
```
The UUID: `2ba045ac-6923-46f3-bc0e-eca525cb8d03` relates to a file that was transferred in transfer_1 in that scenario. I am trying metadata reingest on transfer_3.

**Comment by joel-simpson** [comment]
This is connected to https://github.com/artefactual/archivematica/pull/1225
(trying to get this link to show in waffle)

**Comment by peterVG** [comment]
If I understand the related threads correctly, this issue is related to https://github.com/archivematica/Issues/issues/43 and both this issue and #43 are fixed as per the commit for https://github.com/artefactual/archivematica/pull/1225 ? I should be able to test this by completing AIP reingests for metadata only without error as well as NOT seeing repeating metadata from separate transfers?
