### ISSUE TITLE
Problem: Index AIP async 404 error

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#425]
**Expected behaviour**

Index the AIP

**Current behaviour**

The `AIP Index` task fails for a big AIP (20GB, 179  tiff files, No normalization). This is the dashboard GUI error:

```404 Client Error: NOT FOUND for url: https://utsa.archivesdirect.archivematica.org:8000/api/v2/async/32/Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 212, in store_aip
    related_package_uuid)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 67, in _create_file
    agents=get_agents_from_db(uuid)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
    ret = wait_for_async(response)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 223, in wait_for_async
    poll_response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: https://utsa.archivesdirect.archivematica.org:8000/api/v2/async/32/```
```

storage_service_debug.log:

```
INFO      2019-01-10 09:35:26  locations.models.space:space:move_rsync:470:  Moving from /var/archivematica/sharedDirectory/currentlyProcessing/Box1a_a-localAIPStore-4-92ee163b-8e91-4227-8d78-d7cc061f7427/Box1a_a-localAIPStore-4-92ee163b-8e91-4227-8d78-d7cc061f7427.7z to /mnt/aipstore/92ee/163b/8e91/4227/8d78/d7cc/061f/7427/Box1a_a-localAIPStore-4-92ee163b-8e91-4227-8d78-d7cc061f7427.7z
INFO      2019-01-10 09:37:34  locations.models.package:package:create_pointer_file:1265:  Returning pointer file for: 92ee163b-8e91-4227-8d78-d7cc061f7427
DEBUG     2019-01-10 09:37:34  locations.models.async_manager:async_manager:_watchdog_loop:108:  Watchdog attempted to update Async object 32 but couldn't find it!
DEBUG     2019-01-10 09:37:35  locations.api.resources:resources:hydrate_current_location:644:  `current_location` was not matched by `default_location_regex`
```

**Steps to reproduce**

No special steps required to reproduce the issue, just use a similar transfer (20GB, 179  tiff files, No normalization). It was tested getting the same error for local and duracloud AIP Store.

**Your environment (version of Archivematica, OS version, etc)**

AM 1.8.0 and AM 1.8.1
SS 0.13.0
VM with 8 vCPU
Ubuntu 18.04

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
issue and PR possibly related:

https://github.com/archivematica/Issues/issues/114
https://github.com/artefactual/archivematica/pull/1248

**Comment by mamedin** [comment]
The AIP was indexed changing `TASK_TIMEOUT_SECONDS` from 120s (default) to 1200s:

https://github.com/artefactual/archivematica-storage-service/pull/327/files#diff-b344c970aa8d181c3515742cda42fa1eR27

**Comment by sevein** [comment]
Like @mamedin said, #114 is possibly related. SS is doing some CPU intensive work (pointer file creation?) and the watchdog loop isn't being given an opportunity to run often enough and when it does the task is deleted because it exceeds the timeout. That strikes me as surprising because 120s is a lot, but this is the only lead we have at the moment. We should investigate further.

Potential solutions if the above is confirmed:
1) Make `TASK_TIMEOUT_SECONDS` default higher - what would be the implications?
2) Make `TASK_TIMEOUT_SECONDS` configurable - pushing complexity to users which is undesirable.
3) Investigate whether this is a case of non-cooperative greenlets. E.g. is the libxml extension non-cooperative? Our own code? One potential solution is to have a `gevent.hub.Hub.threadpool` in `AsyncManager` to run our tasks, that would ensure that non-cooperative code doesn't halt the main loop. Additionally, I would probably try to run the watchdog into its own system thread to protect it from non-cooperative code in the main gevent loop used by Gunicorn.

**Comment by ross-spencer** [comment]
We believe IIISH cc. @lwo are also seeing this as well.

**Comment by lwo** [comment]
Yes, this one looks quite like it. See 257

**Comment by ross-spencer** [comment]
Thanks @lwo :+1:

**Comment by cole** [comment]
From my initial investigation, I think @sevein is correct and what is happening here is that something is blocking the gevent event loop for more than 120 seconds (!!). 120 seconds is a long time in gevent land, 0.1 seconds would be considered a long block, since the storage service will be completely unresponsive while it's blocked.

We should be able to debug this with a couple env variables:
1. `GEVENT_MONITOR_THREAD_ENABLE=1` ([docs](http://www.gevent.org/configuration.html#gevent._config.Config.monitor_thread))
2. `GEVENT_MAX_BLOCKING_TIME=10` (or any value under 120) ([docs](http://www.gevent.org/configuration.html#gevent._config.Config.max_blocking_time))

Those should cause logging to stderr of anything that's taking over 10 seconds at a time, although it may be very noisy.

**Comment by sevein** [comment]
I've submitted a couple of branches suggesting two solutions.

- [dev/issue-420-watchdog-thread](https://github.com/artefactual/archivematica-storage-service/compare/qa/0.x...dev/issue-420-watchdog-thread?expand=1) moves the watchdog (async manager) into its own native thread so it's protected from non-cooperative code blocking the gevent hub (for more, see [this blog post](https://dev.nextthought.com/blog/2018/06/gevent-blocking-greenlets.html)). Observations:
    1. When using SQLite, users may experience the following error: "Database is locked". Try MySQL instead or experiment with the timeout setting, [as suggested in the Django docs](https://docs.djangoproject.com/en/dev/ref/databases/#database-is-locked-errors).
    2. This is not the best long-term solution, i.e. we should identify non-cooperative code (see @cole's suggestions [above](https://github.com/archivematica/Issues/issues/425#issuecomment-494539745) and use the async manager as much as possible. At that point, we may also want to look into Celery.
- [dev/issue-420-storage-service-back-to-sync](https://github.com/artefactual/archivematica/compare/qa/1.x...dev/issue-420-storage-service-back-to-sync) updates the SS client in Archivematica to avoid the async endpoints that rely on the SS async manager (we used to do this in AM17). The synchronous endpoints are not as reliable, e.g. load balancers may close long-running connections (see for example AWS ALB's 1h cap) and recovery after failures wouldn't be possible.

**Comment by sevein** [comment]
@mamedin has started testing dev/issue-420-watchdog-thread - he identified the issue with SQLite.

**Comment by mamedin** [comment]
I could reproduce the issue (AM stable/1.9.x and SS stable/0.14.x) with a 108 GB transfer with 201 copies of the file:

* http://lroc.sese.asu.edu/data/pr/tiff/wac_nearside.tif 

I got the following error in "Store the AIP" task (after 13 hours):

```
May 29 02:35:59 issue-425 python[9222]: *** Completed job: #<storeaip_v0.0; exit=1; code=success uuid=4ab9a8cb-c067-40fa-87ae-ccd0add320f3
May 29 02:35:59 issue-425 python[9222]: =============== STDOUT ===============
May 29 02:35:59 issue-425 python[9222]: =============== END STDOUT ===============
May 29 02:35:59 issue-425 python[9222]: =============== STDERR ===============
May 29 02:35:59 issue-425 python[9222]: HTTPConnectionPool(host='158.69.67.30', port=8000): Read timed out. (read timeout=600)Traceback (most recent call last):
May 29 02:35:59 issue-425 python[9222]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
May 29 02:35:59 issue-425 python[9222]:     yield
May 29 02:35:59 issue-425 python[9222]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
May 29 02:35:59 issue-425 python[9222]:     args.sip_uuid, args.sip_name, args.sip_type))
May 29 02:35:59 issue-425 python[9222]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 212, in store_aip
May 29 02:35:59 issue-425 python[9222]:     related_package_uuid)
May 29 02:35:59 issue-425 python[9222]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 67, in _create_file
May 29 02:35:59 issue-425 python[9222]:     agents=get_agents_from_db(uuid)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
May 29 02:35:59 issue-425 python[9222]:     ret = wait_for_async(response)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 222, in wait_for_async
May 29 02:35:59 issue-425 python[9222]:     timeout=poll_timeout_seconds).get(poll_url)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
May 29 02:35:59 issue-425 python[9222]:     return self.request('GET', url, **kwargs)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
May 29 02:35:59 issue-425 python[9222]:     resp = self.send(prep, **send_kwargs)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
May 29 02:35:59 issue-425 python[9222]:     r = adapter.send(request, **kwargs)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 69, in send
May 29 02:35:59 issue-425 python[9222]:     return super(HTTPAdapterWithTimeout, self).send(*args, **kwargs)
May 29 02:35:59 issue-425 python[9222]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
May 29 02:35:59 issue-425 python[9222]:     raise ReadTimeout(e, request=request)
May 29 02:35:59 issue-425 python[9222]: ReadTimeout: HTTPConnectionPool(host='158.69.67.30', port=8000): Read timed out. (read timeout=600)
May 29 02:35:59 issue-425 python[9222]: =============== END STDERR ===============
```

Sevein has prepared two possible fixes:

**Alternative 1**

I'm testing with AM stable/1.9.x and the SS branch: https://github.com/artefactual/archivematica-storage-service/tree/dev/issue-420-watchdog-thread

**Alternative 2**

The next test: SS stable/0.14.x and AM branch: https://github.com/artefactual/archivematica/tree/dev/issue-420-storage-service-back-to-sync


I'll update in the next hours once the tests have been finished.

**Comment by mamedin** [comment]
Tested with AM stable/1.9.x and the SS branch: https://github.com/artefactual/archivematica-storage-service/tree/dev/issue-420-watchdog-thread

First try I got the SQLite3 block error when copying files from TS to SS staging location.

Second try it failed when Storing the AIP, same error than AM stable/1.9x and SS stable/0.14.x:

```
ay 29 21:16:13 issue-425 python[25613]: archivematicaClient.py: INFO      2019-05-29 21:16:13,095  archivematica.mcp.client:write_task_results_callback:200:
May 29 21:16:13 issue-425 python[25613]: *** Completed job: #<storeaip_v0.0; exit=1; code=success uuid=5ab088b2-85f5-4811-8254-4c6255c1d346
May 29 21:16:13 issue-425 python[25613]: =============== STDOUT ===============
May 29 21:16:13 issue-425 python[25613]: =============== END STDOUT ===============
May 29 21:16:13 issue-425 python[25613]: =============== STDERR ===============
May 29 21:16:13 issue-425 python[25613]: HTTPConnectionPool(host='158.69.67.30', port=8000): Read timed out. (read timeout=600)Traceback (most recent call last):
May 29 21:16:13 issue-425 python[25613]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
May 29 21:16:13 issue-425 python[25613]:     yield
May 29 21:16:13 issue-425 python[25613]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
May 29 21:16:13 issue-425 python[25613]:     args.sip_uuid, args.sip_name, args.sip_type))
May 29 21:16:13 issue-425 python[25613]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 212, in store_aip
May 29 21:16:13 issue-425 python[25613]:     related_package_uuid)
May 29 21:16:13 issue-425 python[25613]:   File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 67, in _create_file
May 29 21:16:13 issue-425 python[25613]:     agents=get_agents_from_db(uuid)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
May 29 21:16:13 issue-425 python[25613]:     ret = wait_for_async(response)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 222, in wait_for_async
May 29 21:16:13 issue-425 python[25613]:     timeout=poll_timeout_seconds).get(poll_url)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
May 29 21:16:13 issue-425 python[25613]:     return self.request('GET', url, **kwargs)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
May 29 21:16:13 issue-425 python[25613]:     resp = self.send(prep, **send_kwargs)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
May 29 21:16:13 issue-425 python[25613]:     r = adapter.send(request, **kwargs)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 69, in send
May 29 21:16:13 issue-425 python[25613]:     return super(HTTPAdapterWithTimeout, self).send(*args, **kwargs)
May 29 21:16:13 issue-425 python[25613]:   File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
May 29 21:16:13 issue-425 python[25613]:     raise ReadTimeout(e, request=request)
May 29 21:16:13 issue-425 python[25613]: ReadTimeout: HTTPConnectionPool(host='158.69.67.30', port=8000): Read timed out. (read timeout=600)
May 29 21:16:13 issue-425 python[25613]: =============== END STDERR ===============
```

I'm going to start the test with SS stable/0.14.x and AM branch: https://github.com/artefactual/archivematica/tree/dev/issue-420-storage-service-back-to-sync

**Comment by mamedin** [comment]
For the last test (Alternative 1), SS log says:

```
INFO      2019-05-29 09:33:23  locations.models.space:space:browse:270:  path: /home
INFO      2019-05-29 14:06:12  locations.models.package:package:store_aip:762:  store_aip called in Package class of SS
INFO      2019-05-29 14:06:12  locations.models.package:package:store_aip:763:  store_aip got origin_path currentlyProcessing/109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7/109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7.7z
INFO      2019-05-29 14:06:12  locations.models.space:space:move_rsync:546:  Moving from /var/archivematica/sharedDirectory/currentlyProcessing/109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7/109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7.7z to /var/archivematica/sharedDirectory/www/AIPsStore/99f1/56cf/ab0b/49c6/8080/16c6/5ab7/3ee7/109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7.7z
ERROR     2019-05-29 14:37:53  locations.models.package:package:create_pointer_file:1549:  Pointer file constructed for 99f156cf-ab0b-49c6-8080-16c65ab73ee7 is not valid.
Schematron Error(s):


XMLSchema (xsd) Error(s):
ERROR ON LINE 0: Element '{http://www.loc.gov/METS/}file', attribute 'ID': '109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7' is not a valid value of the atomic type 'xs:ID'.
ERROR ON LINE 0: Element '{http://www.loc.gov/METS/}fptr', attribute 'FILEID': '109_GB_tif_files-SS-branch2-99f156cf-ab0b-49c6-8080-16c65ab73ee7' is not a valid value of the atomic type 'xs:IDREF'.
INFO      2019-05-29 14:37:53  locations.models.package:package:create_pointer_file:1551:  Returning pointer file for: 99f156cf-ab0b-49c6-8080-16c65ab73ee7
```

**Comment by sevein** [comment]
Trying `dev/issue-420-watchdog-thread` (alternative 1) and gevent monitoring enabled with:

    GEVENT_MONITOR_THREAD_ENABLE: "1"
    GEVENT_MAX_BLOCKING_TIME: "1"

I've seen gevent print two blocking reports shared below. This makes me realize that `AsyncManager.run_task` is still running async tasks inside the event loop which I think I can fix by pushing them to the `gevent.threadpool.ThreadPoolExecutor` instead (native threads). This may explain the results seen by @mamedin in https://github.com/archivematica/Issues/issues/425#issuecomment-497123236.

#### Report 1

```
2019-05-30T11:54:56Z : Greenlet <Greenlet "Greenlet-0" at 0x7fb64205baa0: <bound method Thread.__bootstrap of <Thread(Thread-139, started daemon 140420768447136)>>> appears to be blocked
    Reported by <gevent.__tracer.GreenletTracer object at 0x7fb64e0a5788>
Blocked Stack (for thread id 0x7fb655b6c340):
  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
    value = task_fn(*args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1016, in task
    self._store_bundle(bundle)
  File "/src/storage_service/locations/api/resources.py", line 981, in _store_bundle
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 765, in store_aip
    storage_effects, checksum = self._store_aip_to_uploaded(v, related_package_uuid)
  File "/src/storage_service/locations/models/package.py", line 888, in _store_aip_to_uploaded
    self.get_local_path(), Package.DEFAULT_CHECKSUM_ALGORITHM
  File "/src/storage_service/common/utils.py", line 306, in generate_checksum
    checksum.update(chunk)

Info:
********************************************************************************
* Threads
********************************************************************************
Thread 0x7fb642987700 (None)

  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 186, in __call__
    thread_sleep(sleep_time)

********************************************************************************
Thread 0x7fb643188700 (None)

  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 565, in run
    loop.run()

********************************************************************************
Thread 0x7fb655b6c340 (None)

  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
    value = task_fn(*args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1016, in task
    self._store_bundle(bundle)
  File "/src/storage_service/locations/api/resources.py", line 981, in _store_bundle
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 765, in store_aip
    storage_effects, checksum = self._store_aip_to_uploaded(v, related_package_uuid)
  File "/src/storage_service/locations/models/package.py", line 888, in _store_aip_to_uploaded
    self.get_local_path(), Package.DEFAULT_CHECKSUM_ALGORITHM
  File "/src/storage_service/common/utils.py", line 306, in generate_checksum
    checksum.update(chunk)

********************************************************************************
Thread 0x7fb64dbff700 (None) (CURRENT)

  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 202, in __call__
    f(hub)
  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 235, in monitor_blocking
    dict(greenlet_stacks=False, current_thread_ident=self.monitor_thread_ident))
  File "/usr/local/lib/python2.7/site-packages/gevent/util.py", line 153, in format_run_info
    _format_thread_info(lines, thread_stacks, limit, current_thread_ident)
  File "/usr/local/lib/python2.7/site-packages/gevent/util.py", line 178, in _format_thread_info
    lines.append(''.join(traceback.format_stack(frame, limit)))

********************************************************************************
* Greenlets
********************************************************************************
<greenlet.greenlet object at 0x7fb65083c910>
 :    Parent: None
 :    Greenlet Locals:
 :      Local <type 'gevent._local.local'> at 0x7fb647ecc830
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb646aa1fa0
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c05b1a0
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c05b130
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64cf2a750
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c8c0980
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c9716e0
 :        {'default': <django.db.backends.mysql.base.DatabaseWrapper object at 0x7fb647bd28d0>}
<greenlet.greenlet object at 0x7fb64e0bd910>
 :    Parent: None
 :    Monitoring Thread:<PeriodicMonitoringThread at 0x7fb64e0a1810 in thread 0x7fb64dbff700 greenlet <greenlet.greenlet object at 0x7fb64e0bd910> for <Hub '' at 0x7fb64e3a25d0 epoll default pending=0 ref=6 fileno=9 thread_ident=0x7fb655b6c340>>
<greenlet.greenlet object at 0x7fb64318fcd0>
 :    Parent: None
 :    Monitoring Thread:<PeriodicMonitoringThread at 0x7fb64319d510 in thread 0x7fb642987700 greenlet <greenlet.greenlet object at 0x7fb64e0bd910> for <Hub '' at 0x7fb643428e10 epoll pending=0 ref=1 fileno=16 thread_ident=0x7fb643188700>>
<ThreadPoolWorker at 0x7fb64318f870 thread_ident=0x7fb643188700 <ThreadPool at 0x7fb64318c410 1/1/1 hub=<Hub at 0x7fb64e3a25d0 thread_ident=0x140421098816320>>>
 :    Parent: <greenlet.greenlet object at 0x7fb64318f050>
 :    Greenlet Locals:
 :      Local <type 'gevent._local.local'> at 0x7fb64c9716e0
 :        {'default': <django.db.backends.mysql.base.DatabaseWrapper object at 0x7fb64319d750>}
 +--- <Hub '' at 0x7fb643428e10 epoll pending=0 ref=1 fileno=16 thread_ident=0x7fb643188700>
            Parent: <ThreadPoolWorker at 0x7fb64318f870 thread_ident=0x7fb643188700 <ThreadPool at 0x7fb64318c410 1/1/1 hub=<Hub at 0x7fb64e3a25d0 thread_ident=0x140421098816320>>>
================================================================================
```

#### Report 2

```
2019-05-30T11:54:57Z : Greenlet <Greenlet "Greenlet-0" at 0x7fb64205baa0: <bound method Thread.__bootstrap of <Thread(Thread-139, started daemon 140420768447136)>>> appears to be blocked
    Reported by <gevent.__tracer.GreenletTracer object at 0x7fb64e0a5788>
Blocked Stack (for thread id 0x7fb655b6c340):
  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
    value = task_fn(*args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1016, in task
    self._store_bundle(bundle)
  File "/src/storage_service/locations/api/resources.py", line 981, in _store_bundle
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 771, in store_aip
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 983, in _store_aip_ensure_pointer_file
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 1020, in _create_pointer_file_write_to_disk
    package_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 1534, in create_pointer_file
    pointer_file.serialize(), schematron=metsrw.AM_PNTR_SCT_PATH
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 44, in validate
    is_xsd_valid, xsd_error_log = xsd_validate(mets_doc, xmlschema=xmlschema)
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 92, in xsd_validate
    xmlschema = get_xmlschema(xmlschema, mets_doc)
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 88, in get_xmlschema
    return etree.XMLSchema(xmlschema)

Info:
********************************************************************************
* Threads
********************************************************************************
Thread 0x7fb642987700 (None)

  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 186, in __call__
    thread_sleep(sleep_time)

********************************************************************************
Thread 0x7fb643188700 (None)

  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 565, in run
    loop.run()

********************************************************************************
Thread 0x7fb655b6c340 (None)

  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
    value = task_fn(*args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1016, in task
    self._store_bundle(bundle)
  File "/src/storage_service/locations/api/resources.py", line 981, in _store_bundle
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 771, in store_aip
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 983, in _store_aip_ensure_pointer_file
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 1020, in _create_pointer_file_write_to_disk
    package_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 1534, in create_pointer_file
    pointer_file.serialize(), schematron=metsrw.AM_PNTR_SCT_PATH
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 44, in validate
    is_xsd_valid, xsd_error_log = xsd_validate(mets_doc, xmlschema=xmlschema)
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 92, in xsd_validate
    xmlschema = get_xmlschema(xmlschema, mets_doc)
  File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 88, in get_xmlschema
    return etree.XMLSchema(xmlschema)

********************************************************************************
Thread 0x7fb64dbff700 (None) (CURRENT)

  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 202, in __call__
    f(hub)
  File "/usr/local/lib/python2.7/site-packages/gevent/_monitor.py", line 235, in monitor_blocking
    dict(greenlet_stacks=False, current_thread_ident=self.monitor_thread_ident))
  File "/usr/local/lib/python2.7/site-packages/gevent/util.py", line 153, in format_run_info
    _format_thread_info(lines, thread_stacks, limit, current_thread_ident)
  File "/usr/local/lib/python2.7/site-packages/gevent/util.py", line 178, in _format_thread_info
    lines.append(''.join(traceback.format_stack(frame, limit)))

********************************************************************************
* Greenlets
********************************************************************************
<greenlet.greenlet object at 0x7fb65083c910>
 :    Parent: None
 :    Greenlet Locals:
 :      Local <type 'gevent._local.local'> at 0x7fb647ecc830
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb646aa1fa0
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c05b1a0
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c05b130
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64cf2a750
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c8c0980
 :        {}
 :      Local <type 'gevent._local.local'> at 0x7fb64c9716e0
 :        {'default': <django.db.backends.mysql.base.DatabaseWrapper object at 0x7fb647bd28d0>}
<greenlet.greenlet object at 0x7fb64e0bd910>
 :    Parent: None
 :    Monitoring Thread:<PeriodicMonitoringThread at 0x7fb64e0a1810 in thread 0x7fb64dbff700 greenlet <greenlet.greenlet object at 0x7fb64e0bd910> for <Hub '' at 0x7fb64e3a25d0 epoll default pending=0 ref=6 fileno=9 thread_ident=0x7fb655b6c340>>
<greenlet.greenlet object at 0x7fb64318fcd0>
 :    Parent: None
 :    Monitoring Thread:<PeriodicMonitoringThread at 0x7fb64319d510 in thread 0x7fb642987700 greenlet <greenlet.greenlet object at 0x7fb64e0bd910> for <Hub '' at 0x7fb643428e10 epoll pending=0 ref=1 fileno=16 thread_ident=0x7fb643188700>>
<ThreadPoolWorker at 0x7fb64318f870 thread_ident=0x7fb643188700 <ThreadPool at 0x7fb64318c410 1/1/1 hub=<Hub at 0x7fb64e3a25d0 thread_ident=0x140421098816320>>>
 :    Parent: <greenlet.greenlet object at 0x7fb64318f050>
 :    Greenlet Locals:
 :      Local <type 'gevent._local.local'> at 0x7fb64c9716e0
 :        {'default': <django.db.backends.mysql.base.DatabaseWrapper object at 0x7fb64319d750>}
 +--- <Hub '' at 0x7fb643428e10 epoll pending=0 ref=1 fileno=16 thread_ident=0x7fb643188700>
            Parent: <ThreadPoolWorker at 0x7fb64318f870 thread_ident=0x7fb643188700 <ThreadPool at 0x7fb64318c410 1/1/1 hub=<Hub at 0x7fb64e3a25d0 thread_ident=0x140421098816320>>>
```

**Comment by mamedin** [comment]
Test done for SS stable/0.14.x and AM branch: https://github.com/artefactual/archivematica/tree/dev/issue-420-storage-service-back-to-sync.

Tested with QUICK timeouts=1s

The AIP was successfuly stored and indexed.

**Comment by sevein** [comment]
Here's a new alternative where the SS client configures the poll request with retries and a backoff factor to give Storage Service some extra time to attend it.

https://github.com/artefactual/archivematica/pull/new/dev/issue-425-ssclient-poll-backoff

CC @mamedin

**Comment by hakamine** [comment]
For AM/SS 1.9/0.14, what do you think about adding a commit with @mamedin's workaround increasing the [hardcoded timeout in the SS](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.14.x/storage_service/locations/models/async_manager.py#L27) (TASK_TIMEOUT_SECONDS from 120s to 1200s). Don't know if there are any side effects but it seems to be helpful to avoid the error in production clients upgraded to 1.9/0.14.  Would it be ok if I create a PR for SS stable/0.14.x)?

**Comment by mamedin** [comment]
@hakamine the TASK_TIMEOUT_SECONDS workaround is not working in all AM servers.

**Comment by sevein** [comment]
@mamedin @sromkey here's the PR against stable/1.9.x:
https://github.com/artefactual/archivematica/pull/1438.

**Comment by sromkey** [comment]
Tested with a 21 GB AIP, indexed and stored without issue.
