### ISSUE TITLE
Problem: Cannot store AIPS when there is an AIP Storage Location with an encrypted replicator

### ISSUE THREAD

**Issue by replaceafill** [archivematica/Issues#463]
**Expected behaviour**

Storing an AIP in the Ingest tab works with a encrypted replication set up.

**Current behaviour**

When the storage location has a GPG replicator set the `Store AIP` job fails with:

```
storeaip_v0.0: WARNING   2019-02-01 00:04:24,772  archivematica.mcp.client.storeAIP.store_aip:215  SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'append'.
SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'append'. See logs for more details.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 216, in store_aip
    raise Exception(errmsg + " See logs for more details.")
Exception: SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'append'. See logs for more details.
```

The storage service logs this:

```
archivematica-storage-service_1  | INFO      2019-01-31 16:04:22  locations.models.package:package:create_pointer_file:1311:  Returning pointer file for: dec3ee7d-f982-4736-8bdc-68eda3a9d8d8
archivematica-storage-service_1  | ERROR     2019-01-31 16:04:22  locations.models.async_manager:async_manager:wrapper:122:  Task threw an error: 'tuple' object has no attribute 'append'
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/async_manager.py", line 119, in wrapper
archivematica-storage-service_1  |     value = task_fn(*args, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 708, in task
archivematica-storage-service_1  |     self._store_bundle(bundle)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 682, in _store_bundle
archivematica-storage-service_1  |     premis_agents=agents, aip_subtype=aip_subtype)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 666, in store_aip
archivematica-storage-service_1  |     self.create_replicas()
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1379, in create_replicas
archivematica-storage-service_1  |     self.replicate(replicator_loc.uuid)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 593, in replicate
archivematica-storage-service_1  |     master_ptr, replica_package, replication_event_uuid)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1027, in create_new_pointer_file_with_replication
archivematica-storage-service_1  |     new_relationships.append(replication_relationship)
archivematica-storage-service_1  | AttributeError: 'tuple' object has no attribute 'append'
```

Currently this also makes the `@aip-encrypt-mirror` AMAUAT to fail.

**Steps to reproduce**

1. Create a new Space in the Storage Service like this:

```
Access protocol: GPG encryption on Local Filesystem
Path: /
Staging path: /var/archivematica/storage_service/storage_service_encrypted
Key: Archivematica Storage Service GPG Key
```

2. In the new space create a Location like this:

```
Purpose: Replicator
Relative Path: var/archivematica/sharedDirectory/www/EncryptedReplicas
Description: Encrypted Replicas
```

3. In the Locations tab, look for the default AIP Storage and click its Edit link. At the bottom, under *Replicators* set the new replicator location.

4. Reset (or use) the default processing configuration.

5. Start a transfer using the `SampleTransfers/BagTransfer`

6. In the `Microservice: Store AIP` under `Job: Store AIP location` select `Store AIP in standard Archivematica Directory`

7. The ` Job: Store the AIP ` should have failed, but two packages should have been created in the Storage Service (the AIP and its replica). 

**Your environment (version of Archivematica, OS version, etc)**
AM: https://github.com/artefactual-labs/am/commit/e860b311cbea2cce95c05620109a763b3929642b

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
I just tested this with @cole's branch for https://github.com/artefactual/archivematica-storage-service/pull/453 and replication worked:

```
│       ├── EncryptedReplicas
│       │   └── f861
│       │       └── 8287
│       │           └── ce92
│       │               └── 4c05
│       │                   └── b604
│       │                       └── 5cd9
│       │                           └── 6b07
│       │                               └── d75b
│       │                                   └── DemoTransfer-f8618287-ce92-4c05-b604-5cd96b07d75b.7z
```

Maybe we just need to add a new unit test for this issue.

**Comment by sallain** [comment]
This is now working beeeeeeautifully.
