### ISSUE TITLE
Problem: v2beta/package endpoint doesn't provide enough feedback to the user in its own right

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#491]
**Expected behaviour**

As a consumer of the `v2beta/package/` endpoint I would like to receive some indication that there has been an error starting a transfer.

Relaying @sevein's concerns about the original ticket, (i believe) as a asynchronous non-blocking endpoint there isn't a lot that it can necessarily do.

As such, desired behavior might be one or a number of the below options (or alternatives):

1. More documentation for the user,
2. An additional endpoint that will confirm the status of a transfer when that status is available.
3. Provide more feedback where it is possible in the `v2beta/package` endpoint. Looking at the code below at what the endpoint can do - the user can only retrieve a 400 error if a path isn't decoded properly. A log entry in the dashboard isn't written, nor additional info is sent to the user, so, we could add b64decode's failure status here as an example? Are there other parameters here that could be measured against what a consumer of the endpoint needs to anticipate? 
```python
    try:
        payload = json.loads(request.body)
        path = base64.b64decode(payload.get('path'))
    except (TypeError, ValueError):
        return helpers.json_response({
            'error': True,
            'message': 'Parameter "path" cannot be decoded.'}, 400)
    args = (
        payload.get('name'),
        payload.get('type'),
        payload.get('accession'),
        payload.get('access_system_id'),
        path,
        payload.get('metadata_set_id'),
    )
    kwargs = {
        'auto_approve': payload.get('auto_approve', True),
        'wait_until_complete': False,
    }
```
3. Possibly more clean-up, e.g. in the original example below we show just one method of failing, we can react to the directory move error, and if that happens should we persist a UUID in the database even though it won't be used again? Does it provide enough evidential value for us to want to persist it? Is it easier to just not remove it? Would changing the behavior here impact the workflow elsewhere or existing API endpoints? 

The details from the original design mentioned below would be useful here. 

**Current behaviour**

If I try starting this non-existing transfer with the mojibake string in its path:
```
http --pretty=format \
> POST 127.0.0.1:62080/api/v2beta/package \
> "Authorization: ApiKey test:test" \
> processing_config=automated path=$(echo -n '/home/archivematica/archivematica-sampledata/api-demo/ﾊｸｻ�ｽ､ｱ' | base64 -w 0) \
> name=v2_beta_endpoint_example
HTTP/1.1 202 ACCEPTED
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Thu, 07 Feb 2019 18:03:16 GMT
Server: nginx/1.14.2
Transfer-Encoding: chunked
Vary: Accept-Language, Cookie

{
    "id": "3dbf09e3-4993-405c-a4d0-08464d650ff5"
}
```

You can see I receive a transfer ID as a response. (A row is also written to the database):
```
mysql> select * from Transfers where transferUUID = '3dbf09e3-4993-405c-a4d0-08464d650ff5';
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
| transferUUID                         | currentLocation | type | accessionID | sourceOfAcquisition | typeOfTransfer | description | notes | hidden | transferMetadataSetRowUUID | dirUUIDs | access_system_id |
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
| 3dbf09e3-4993-405c-a4d0-08464d650ff5 |                 |      |             |                     |                |             |       |      0 | NULL                       |        0 |                  |
+--------------------------------------+-----------------+------+-------------+---------------------+----------------+-------------+-------+--------+----------------------------+----------+------------------+
1 row in set (0.00 sec)
```
The particular error in the MCP Server is:
```
archivematica-mcp-server_1       | ERROR     2019-02-07 18:03:20  archivematica.mcp.server:package:wrap:348:  Exception: 'ascii' codec can't encode characters in position 177-183: ordinal not in range(128)
archivematica-mcp-server_1       | Traceback (most recent call last):
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/package.py", line 327, in wrap
archivematica-mcp-server_1       |     fn(*args, **kwargs)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/package.py", line 386, in _start_package_transfer_with_auto_approval
archivematica-mcp-server_1       |     _copy_from_transfer_sources([path], transfer_rel)
archivematica-mcp-server_1       |   File "/src/MCPServer/lib/package.py", line 219, in _copy_from_transfer_sources
archivematica-mcp-server_1       |     item['location'], processing_location, item['files'])
archivematica-mcp-server_1       |   File "/src/archivematicaCommon/lib/storageService.py", line 280, in copy_files
archivematica-mcp-server_1       |     return (wait_for_async(response), None)
archivematica-mcp-server_1       |   File "/src/archivematicaCommon/lib/storageService.py", line 240, in wait_for_async
archivematica-mcp-server_1       |     errmsg = 'Failure storing file: {}'.format(payload['error'])
archivematica-mcp-server_1       | UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-183: ordinal not in range(128)
```
So it leaves open the opportunity for a user to do something unexpected without knowing much about it. 

**Steps to reproduce**

As above.

**Your environment (version of Archivematica, OS version, etc)**

Archivematica `qa/1.x` 6689b64bd7323fafde64594afc9bfbd50fcff1ff in the docker-compose environment using the httpie client. 

**Additional context**

As a developer, I have to have the AM dashboard logs open to begin to understand where failures with this endpoint are happening. As a user accessing the API this is a much more challenging proposition. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
I think that you need a new endpoint to query the status of a transfer, the create endpoint can't tell you that by design unless the UUID couldn't be returned. In other words, this may not be a bug in this endpoint but the lack of an additional space for users to look up the status. That's something that was contemplated during the JiscRDSS project in 2018 but we never got do it. CC @joel-simpson wrote some design docs about that idea.

**Comment by bruth** [comment]
Cross-posting here from the mailing list [Starting a transfer fails with an API key error against /api/v2beta/package/](https://groups.google.com/forum/#!topic/archivematica/k-GCD7WUhnE) because I found this issue afterwards and appears to be related. Here is the copied text:

> I stood up a fresh install and was able to successfully connect the service and storage components. I can browse files in the transfer area, select it and prepare a transfer. However once I click "Start transfer" I am getting and API key error response {"message": "API key not valid.", "error": true} from the path /api/v2beta/package/ in the Web browser console.

> I don't see any client-side reference of an API key in the request (in the console) so I presume this is in reference to the API key to the storage service? If so, then it should be valid since the credentials were validated in the Administration tab.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
