### ISSUE TITLE
Problem: Job "extractContents_v0.0" fails on Ubuntu 16.04/Ansible

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#506]
**Expected behaviour**
The ```extractContents_v0.0``` is able to finish without problems

**Current behaviour**
The ```extractContents_v0.0``` seems to work, but it exists with 1 and the following error is thrown to stderr:

```
Deleting?: True
extractcontents_v0.0: INFO      2019-02-18 15:36:25,830  archivematica.mcp.client.extractContents.main:173  Command to execute is: 7z x -bd -o"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Unicode_1550504146-9e2c0742-41a9-47a1-8966-261bc26b1401/objects/shabrov2.zip-2019-02-18T15:36:25.812399+00:00" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Unicode_1550504146-9e2c0742-41a9-47a1-8966-261bc26b1401/objects/shabrov2.zip"
'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/extract_contents.py", line 245, in call
    job.set_status(main(job, transfer_uuid, sip_directory, date, task_uuid, delete=delete))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/extract_contents.py", line 193, in main
    for extracted_file in tree(extraction_target):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/extract_contents.py", line 39, in tree
    for dirpath, __, files in os.walk(root):
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)
```

**Steps to reproduce**
Run the @package tag from AMAUAT against an Ubuntu 16.04 system installed with ansible.

**Your environment (version of Archivematica, OS version, etc)**
Ubuntu 16.04, Archivematica qa/1.x installed using ansible playbooks

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@scollazo I tested this manually on am19xenial and while there is still a stderr output, it looks okay to me - it refers to un-extractable files, which is expected.

```
Deleting?: True
extractcontents_v0.0: INFO      2019-02-27 22:45:40,835  archivematica.mcp.client.extractContents.main:173  Command to execute is: 7z x -bd -o"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/extract-bad58139-ef6f-41bf-9927-bb7b96e55d5d/objects/MS-OfficeOpenXML-samples.zip-2019-02-27T22:45:40.810827+00:00" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/extract-bad58139-ef6f-41bf-9927-bb7b96e55d5d/objects/MS-OfficeOpenXML-samples.zip"
extractcontents_v0.0: INFO      2019-02-27 22:45:40,952  archivematica.mcp.client.extractContents.main:173  Command to execute is: 7z x -bd -o"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/extract-bad58139-ef6f-41bf-9927-bb7b96e55d5d/objects/Project.zip-2019-02-27T22:45:40.810827+00:00" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/extract-bad58139-ef6f-41bf-9927-bb7b96e55d5d/objects/Project.zip"
Not extracting contents from article.pdf  - No rule found to extract
Not extracting contents from _datavibe-l__FW__job_vacancy.rtf  - No rule found to extract
Not extracting contents from FRPEnForm.pdf  - No rule found to extract
Not extracting contents from Club-Report.doc  - No rule found to extract
```

**Comment by currmie** [comment]
Re-tested on am19xenial after @scollazo rebuilt it; extraction OK but still getting stderr output during validation as others have reported.

**Comment by sallain** [comment]
@currmie @scollazo I think that some stderr output is okay; it has to do with what the tool calls a stderr, rather than it being an actual error, right? Michelle, was your output similar to the one I got?

**Comment by currmie** [comment]
@sallain Yep, similar output as yours
