### ISSUE TITLE
Problem: dashboard showing failed AIP storage but AIP is actually stored

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#513]
**Expected behaviour**
AIP is placed in archival storage and there is no error output in the ingest tab.

**Current behaviour**
Job: Index AIP shows the following error:
```
AttributeError("'NoneType' object has no attribute 'getiterator'",)
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 124, in call
    status_code = index_aip(job)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 98, in index_aip
    printfn=job.pyprint,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 454, in index_aip_and_files
    printfn=printfn,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 561, in _index_aip_files
    xml = ElementTree.tostring(dmd_section_info)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'
```

The ingest tab shows the SIP as having failed. However, the AIP appears in the archival storage tab and is searchable.

**Steps to reproduce**
Ingest SampleTransfers/Dataverse/NDSAStaffingReport and process it all the way through to archival storage.

**Your environment (version of Archivematica, OS version, etc)**
am19centos.qa 
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Currently I cannot recreate this on Xenial, Bionic, but it is happening on RPM:

ES version on CentOS is:
```bash
[artefactual@am19centos clientScripts]$ http http://localhost:9200
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 293
content-type: application/json; charset=UTF-8

{
    "cluster_name": "elasticsearch", 
    "cluster_uuid": "Lf0ORMl3Seu21e2ez5-SBw", 
    "name": "YeMiVvD", 
    "tagline": "You Know, for Search", 
    "version": {
        "build_date": "2018-12-17T21:17:40.758843Z", 
        "build_flavor": "default", 
        "build_hash": "d2ef93d", 
        "build_snapshot": false, 
        "build_type": "rpm", 
        "lucene_version": "7.5.0", 
        "minimum_index_compatibility_version": "5.0.0", 
        "minimum_wire_compatibility_version": "5.6.0", 
        "number": "6.5.4"
    }
}
```

on RPM:
```bash
[artefactual@am19rpm ~]$  http http://localhost:9200
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 293
content-type: application/json; charset=UTF-8

{
    "cluster_name": "elasticsearch", 
    "cluster_uuid": "3h-0pW3uSRiCmUESqJ015w", 
    "name": "97_Gy47", 
    "tagline": "You Know, for Search", 
    "version": {
        "build_date": "2019-01-24T11:27:09.439740Z", 
        "build_flavor": "default", 
        "build_hash": "a9861f4", 
        "build_snapshot": false, 
        "build_type": "rpm", 
        "lucene_version": "7.6.0", 
        "minimum_index_compatibility_version": "5.0.0", 
        "minimum_wire_compatibility_version": "5.6.0", 
        "number": "6.6.0"
    }
}
```

Bionic:
```bash
artefactual@am19xbionic:/opt/archivematica/archivematica$ http http://localhost:9200
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 297
content-type: application/json; charset=UTF-8

{
    "cluster_name": "elasticsearch",
    "cluster_uuid": "TgvIu6h8QHqMygBJw8l1HQ",
    "name": "J2ce8EJ",
    "tagline": "You Know, for Search",
    "version": {
        "build_date": "2018-12-17T21:17:40.758843Z",
        "build_flavor": "default",
        "build_hash": "d2ef93d",
        "build_snapshot": false,
        "build_type": "deb",
        "lucene_version": "7.5.0",
        "minimum_index_compatibility_version": "5.0.0",
        "minimum_wire_compatibility_version": "5.6.0",
        "number": "6.5.4"
    }
}
```

Xenial:
```bash
artefactual@am19xenial:~$ curl http://localhost:9200
{
  "name" : "cV1Loqi",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "97bSaOuVTnqSZ-ykGPq3rQ",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "d2ef93d",
    "build_date" : "2018-12-17T21:17:40.758843Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by ross-spencer** [comment]
**Etree Versions**

Xenial:
```python
artefactual@am19xenial:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> etree.LXML_VERSION
(3, 5, 0, 0)
```

Bionic:
```python
artefactual@am19xbionic:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> etree.LXML_VERSION
(4, 2, 1, 0)
```

RPM:
```python
[artefactual@am19rpm ~]$ python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> etree.LXML_VERSION
(3, 2, 1, 0)
```

CentOS:
```python
[artefactual@am19centos ~]$ python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> etree.LXML_VERSION
(3, 2, 1, 0)
```

**Comment by ross-spencer** [comment]
Python versions:

**CentOS**
```python
[artefactual@am19centos ~]$ python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Xenial:**
```python
artefactual@am19xenial:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by ross-spencer** [comment]
Okay, I thought this might be due to a difference in Python versions, with the CentOS Python dating back to 2013. I managed to upgrade CentOS to 2.7.15 and there is no difference, so perhaps there is something happening, or not happening before indexing that is causing this problem:

```python
indexaip_v0.0: ERROR     2019-02-23 21:35:48,240  archivematica.mcp.client.indexAIP.index_aip:47  TESTING TESTING: 2.7.15 (default, Feb 23 2019, 21:11:40) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
# ------
AttributeError("'NoneType' object has no attribute 'getiterator'",)
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 126, in call
    status_code = index_aip(job)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 100, in index_aip
    printfn=job.pyprint,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 454, in index_aip_and_files
    printfn=printfn,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 561, in _index_aip_files
    xml = ElementTree.tostring(dmd_section_info)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'
```

**Comment by ross-spencer** [comment]
Okay, going back to basics, I can see a big difference here, which we will need to identify the cause of.

Here are the two broken servers:

**CentOS:**

![image](https://user-images.githubusercontent.com/1880412/53292241-fa5a1680-37bf-11e9-998f-0733ddb92637.png)

**RPM:**

![image](https://user-images.githubusercontent.com/1880412/53292255-11990400-37c0-11e9-98ff-eed2345f8f1e.png)

And here are two that are working:

**Bionic:**

![image](https://user-images.githubusercontent.com/1880412/53292277-45742980-37c0-11e9-93a5-0e950c9a8805.png)

**Xenial:**

![image](https://user-images.githubusercontent.com/1880412/53292287-63da2500-37c0-11e9-8350-e77506dc5b5a.png)

**Differences:**

In the correctly working servers the unit variables for the Dataverse transfers are all set as expected (well, the microservices run) and also this is the same on the broken servers. 

What isn't happening in the broken ones are the Parse External Files Microservices:
```
Microservice: Parse external files
   Job Parse Dataverse METS XML Completed successfully 
   Job Determine if Dataverse METS XML needs to be parsed
````

It is not clear why this is the case so I will need to pick this up again tomorrow.

**Comment by ross-spencer** [comment]
Noticing also, that validate formats is different on CentOS than another deployment, say, Xenial:

**CentOS:**

![image](https://user-images.githubusercontent.com/1880412/53292443-e1069980-37c2-11e9-9ef6-0f21db92b796.png)

**Xenial:**

![image](https://user-images.githubusercontent.com/1880412/53292450-f54a9680-37c2-11e9-9c5c-78c49e7f32f3.png)

**Comment by ross-spencer** [comment]
Okay, I think I got it, the microservice isn't configured correctly, so that if Validate Format fails it moves directly to `Examine contents`, it should move to the Variable Link Pull for `Parse external files`. 

This snippet:
```json
        "a536828c-be65-4088-80bd-eb511a0a063d": {
            "config": {
                "@manager": "linkTaskManagerFiles",
                "@model": "StandardTaskConfig",
                "arguments": "\"%relativeLocation%\" \"%fileUUID%\" \"%SIPUUID%\"",
                "execute": "validateFile_v1.0",
                "filter_file_end": null,
                "filter_file_start": null,
                "filter_subdir": "objects",
                "stderr_file": null,
                "stdout_file": null
            },
            "description": {
                "en": "Validate formats",
                "fr": "Valider les formats",
                "ja": "フォーマットの妥当性確認",
                "pt_BR": "Validar formatos",
                "sv": "Godkänn format"
            },
            "exit_codes": {
                "0": {
                    "job_status": "Completed successfully",
                    "link_id": "ec3c965c-c056-47e3-a551-ad1966e00824"
                }
            },
            "fallback_job_status": "Failed",
            "fallback_link_id": "dae3c416-a8c2-4515-9081-6dbd7b265388",  <---- Examine contents
            "group": {
                "en": "Validation",
                "es": "Validación",
                "ja": "妥当性確認",
                "pt_BR": "Validação",
                "sv": "Godkännande"
            }
        },
```

Needs to become:
```json
        "a536828c-be65-4088-80bd-eb511a0a063d": {
            "config": {
                "@manager": "linkTaskManagerFiles",
                "@model": "StandardTaskConfig",
                "arguments": "\"%relativeLocation%\" \"%fileUUID%\" \"%SIPUUID%\"",
                "execute": "validateFile_v1.0",
                "filter_file_end": null,
                "filter_file_start": null,
                "filter_subdir": "objects",
                "stderr_file": null,
                "stdout_file": null
            },
            "description": {
                "en": "Validate formats",
                "fr": "Valider les formats",
                "ja": "フォーマットの妥当性確認",
                "pt_BR": "Validar formatos",
                "sv": "Godkänn format"
            },
            "exit_codes": {
                "0": {
                    "job_status": "Completed successfully",
                    "link_id": "ec3c965c-c056-47e3-a551-ad1966e00824"
                }
            },
            "fallback_job_status": "Failed",
            "fallback_link_id": "ec3c965c-c056-47e3-a551-ad1966e00824", <---- Parse external files
            "group": {
                "en": "Validation",
                "es": "Validación",
                "ja": "妥当性確認",
                "pt_BR": "Validação",
                "sv": "Godkännande"
            }
        },
```

After restarting the mcp-server everything will work as expected. 

And I will also take a look at why JHOVE reports differently.

**Comment by ross-spencer** [comment]
Cool, and it's a simple answer as to why the JHOVE results are different: 

**Xenial**
```bash
artefactual@am19xenial:~$ jhove
Jhove (Rel. 1.16.0, 2017-12-06)
 Date: 2019-02-23 22:51:24 UTC
 App:
  API: 1.16.0, 2017-12-06
  Configuration: /etc/jhove/jhove.conf
  JhoveHome: $INSTALL_PATH
  Encoding: utf-8
  TempDirectory: /tmp
  BufferSize: 131072
  Module: AIFF-hul 1.3
  Module: ASCII-hul 1.3
  Module: BYTESTREAM 1.3
  Module: GIF-hul 1.3
  Module: GZIP-kb 0.1
  Module: HTML-hul 1.3
  Module: JPEG-hul 1.2
  Module: JPEG2000-hul 1.3
  Module: PDF-hul 1.9
  Module: PNG-gdm 1.0
  Module: TIFF-hul 1.7
  Module: UTF8-hul 1.6
  Module: WARC-kb 1.0
  Module: WAVE-hul 1.4
  Module: XML-hul 1.4
  OutputHandler: Audit 1.1
  OutputHandler: TEXT 1.5
  OutputHandler: XML 1.7
  Usage: java JHOVE [-c config] [-m module] [-h handler] [-e encoding] [-H handler] [-o output] [-x saxclass] [-t tempdir] [-b bufsize] [-l loglevel] [[-krs] dir-file-or-uri [...]]
  Rights: Derived from software Copyright 2004-2011 by the President and Fellows of Harvard College. Version 1.7 to 1.11 independently released. Version 1.12 onwards released by Open Preservation Foundation. Released under the GNU Lesser General Public License.
```

**CentOS:**
```bash
[root@am19centos assets]# jhove
Feb 23, 2019 11:50:20 PM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Jhove (Rel. 1.12.0-SNAPSHOT, 2016-07-28)
 Date: 2019-02-23 23:50:20 CET
 App:
  API: 1.12.0-SNAPSHOT, 2016-07-28
  Configuration: /usr/share/jhove//conf/jhove.conf
  JhoveHome: $INSTALL_PATH
  Encoding: utf-8
  TempDirectory: /tmp
  BufferSize: 131072
  Module: AIFF-hul 1.3
  Module: ASCII-hul 1.3
  Module: BYTESTREAM 1.3
  Module: GIF-hul 1.3
  Module: GZIP-kb 0.1
  Module: HTML-hul 1.3
  Module: JPEG-hul 1.2
  Module: JPEG2000-hul 1.3
  Module: PDF-hul 1.7
  Module: TIFF-hul 1.7
  Module: UTF8-hul 1.6
  Module: WARC-kb 1.0
  Module: WAVE-hul 1.3
  Module: XML-hul 1.4
  OutputHandler: Audit 1.1
  OutputHandler: TEXT 1.5
  OutputHandler: XML 1.7
  Usage: java JHOVE [-c config] [-m module] [-h handler] [-e encoding] [-H handler] [-o output] [-x saxclass] [-t tempdir] [-b bufsize] [-l loglevel] [[-krs] dir-file-or-uri [...]]
  Rights: Derived from software Copyright 2004-2011 by the President and Fellows of Harvard College. Version 1.7 to 1.11 independently released. Version 1.12 onwards released by Open Preservation Foundation. Released under the GNU Lesser General Public License.
```

PDF module `1.7` vs `1.9`. Ideally we would upgrade, but will have to find out if that's possible for the CentOS/RHEL based systems.

**Comment by ross-spencer** [comment]
For the reader, there are three follow-up fixes for this issue:

1. Make the indexing script more robust, to identify i.e. detect the `AttributeError` and manage it. 
2. Fix `workflow.json`.
3. Upgrade JHOVE on our CentOS distributions if possible.

**Comment by currmie** [comment]
Still OK on am19xenial for what it's worth.
