### ISSUE TITLE
Problem: Not enough logging in rights_from_csv client script

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#557]
**Expected behaviour**

When the rights information cannot be generated for a file because the file cannot be found in the `MCP` database, then more logging could be output to help the user understand the issue. 

**Current behaviour**

A `models.File.DoesNotExist` exception is raised but not caught by the client script. 

**Steps to reproduce**

Take the `DemoTransfer` and put the payload into a `contents` folder, and run the transfer. It will fail as follows:

**Standard output (stdout)**
```
Attempting to import rights data...
```

**Standard error (stderr)**
```
File matching query does not exist.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/rights_from_csv.py", line 374, in call
    rows_processed = parser.parse()
  File "/src/MCPClient/lib/clientScripts/rights_from_csv.py", line 90, in parse
    self.parse_row(row)
  File "/src/MCPClient/lib/clientScripts/rights_from_csv.py", line 128, in parse_row
    self.store_row()
  File "/src/MCPClient/lib/clientScripts/rights_from_csv.py", line 137, in store_row
    rights_statement = self.generate_rights_statement()
  File "/src/MCPClient/lib/clientScripts/rights_from_csv.py", line 162, in generate_rights_statement
    transfer_file = models.File.objects.get(originallocation='%transferDirectory%' + filepath, transfer_id=self.transfer_uuid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: File matching query does not exist.
```

The `generate_rights_statement(...)` function could do something as follows:
```
    def generate_rights_statement(self):
        """Generate rights statement."""
        basis = self.column_value('basis').lower().capitalize()
        if basis not in dict(models.RightsStatement.RIGHTS_BASIS_CHOICES):
            raise RightsRowException('Invalid basis: {}'.format(basis), self)
        # Get file data
        filepath = self.column_value('file')
        try:
            path = "%transferDirectory%{}".format(filepath)
            transfer_file = models.File.objects\
                .get(originallocation=path,
                     transfer_id=self.transfer_uuid)
        except models.File.DoesNotExist:
            exc = "File {} not found in database, package uuid: {}"\
                .format(path, self.transfer_uuid)
            raise RightsException(exc)
        # Create rights statement
        rights_statement = models.RightsStatement()
        rights_statement.metadataappliestotype = self.metadata_applies_to_type
        rights_statement.metadataappliestoidentifier = transfer_file.uuid
        rights_statement.rightsbasis = basis
        rights_statement.status = 'ORIGINAL'
        rights_statement.save()
        return rights_statement
```

We might identify other areas in the script we can increase the logging output as well. 

**Your environment (version of Archivematica, OS version, etc)**

Archivematica `1.9`. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
