### ISSUE TITLE
Problem: metsrw returns IndexError using its own helper function (mets-reader-writer)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#597]
**Please describe the problem you'd like to be solved**

As a developer, it makes work easier if the return from a library has a clear description about what might be wrong. 

Trying the following:
```python
        print("Entry type (calling get_premis_objects:", mets_entry.type)
        objs = mets_entry.get_premis_objects()
```

The following error occurs:
```python
Entry type: Directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ross-spencer/git/mainline-archivematica/automation-tools/reports/duplicates/duplicates.py", line 253, in <module>
    sys.exit(main())
  File "/home/ross-spencer/git/mainline-archivematica/automation-tools/reports/duplicates/duplicates.py", line 245, in main
    retrieve_mets(am, duplicate_report, temp_dir)
  File "/home/ross-spencer/git/mainline-archivematica/automation-tools/reports/duplicates/duplicates.py", line 165, in retrieve_mets
    data = read_mets(save_as_loc)
  File "/home/ross-spencer/git/mainline-archivematica/automation-tools/reports/duplicates/duplicates.py", line 149, in read_mets
    return read_premis_data(mets_loc)
  File "duplicates/parsemets.py", line 37, in read_premis_data
    objs = mets_entry.get_premis_objects()
  File "/usr/local/lib/python2.7/dist-packages/metsrw/fsentry.py", line 408, in get_premis_objects
    self.PREMIS_OBJECT, self.premis_object_class)
  File "/usr/local/lib/python2.7/dist-packages/metsrw/fsentry.py", line 403, in get_subsections_of_type
    for ss in self.amdsecs[0].subsections
IndexError: list index out of range
```

**Describe the solution you'd like to see implemented.**

Return an exception, or other indication when this information cannot be accessed. 

**Additional context**

Version `0.2.0` of the library, this issue might not happen in the latest version. Script and METS for context below.
```python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals
import lxml
import logging
import metsrw
import sys


def _load_mets(mets_file):
    """Read the METS file at the path provided."""
    try:
        mets = metsrw.METSDocument.fromfile(mets_file)  # Reads a file
        return mets
    except lxml.etree.XMLSyntaxError as e:
        logging.error("METS %s", e)
        sys.exit(1)
    except IOError as e:
        logging.error("File does not exist %s", e)
        sys.exit(1)


def read_premis_data(mets_file):
    """Read PREMIS information and retrieve information of some utility."""
    mets = _load_mets(mets_file)
    info = []
    for mets_entry in mets.all_files():
        filepath = mets_entry.path
        if mets_entry.type != "Item":
            continue
        objs = mets_entry.get_premis_objects()
        for obj in objs:
            entry = {}
            entry["date_modified"] = obj.date_created_by_application
            entry["filepath"] = filepath
            info.append(entry)
    return info
```

[METS.ca163c07-c4e2-4ee1-ac86-2b40f79ee95d.zip](https://github.com/archivematica/Issues/files/2996949/METS.ca163c07-c4e2-4ee1-ac86-2b40f79ee95d.zip)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
Closing this as the root cause that prompted this issue is now fixed (`metsrw: 0.3.15` at least) and the proposed solution might not be the best approach, but we might find one with other issues outstanding.

Issues which exhibit similar traits where it is difficult for the caller to trace the root cause:

* https://github.com/archivematica/Issues/issues/1129
* https://github.com/archivematica/Issues/issues/1277
