### ISSUE TITLE
Problem: Cannot store AIP in S3 AIP Store (us-west-2 region)

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#639]
**Expected behaviour**

The AIP is stored in S3 AIP Store

**Current behaviour**

The "AIP Store" microservice fails at "Store the AIP" Job:

<pre>
ERROR     2019-04-03 14:30:24  locations.models.async_manager:async_manager:wrapper:122:  Task threw an error: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/locations/models/async_manager.py", line 119, in wrapper
    value = task_fn(*args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 705, in task
    self._store_bundle(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 679, in _store_bundle
    premis_agents=agents, aip_subtype=aip_subtype)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 608, in store_aip
    storage_effects, checksum = self._store_aip_to_uploaded(v, related_package_uuid)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 753, in _store_aip_to_uploaded
    package=self,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 384, in move_from_storage_service
    source_path, destination_path, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/models/s3.py", line 145, in move_from_storage_service
    self._ensure_bucket_exists()
  File "/usr/lib/archivematica/storage-service/locations/models/s3.py", line 72, in _ensure_bucket_exists
    self.client.create_bucket(Bucket=self._bucket_name())
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it
</pre>

**Steps to reproduce**

* Create a S3 Space and AIP storage and set AWS Region as "us-west-2". ( See https://github.com/archivematica/Issues/issues/638#issuecomment-481193686)

* Start a transfer and store the AIP in s3 AIP Store.

**Your environment (version of Archivematica, OS version, etc)**

I could reproduce the issue on:

* CentOS AM 1.8.1, SS 0.13.0 from rpm.
* Bionic AM 1.9.1-rc.4, SS 0.14.1-rc.1

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
The `create_bucket()` is theoretically idempotent, and it is on `us-east-2` region, but apparently on other regions we can get `botocore.errorfactory.BucketAlreadyOwnedByYou` exceptions, for example on us-west-2 region.

This is the exception:
<pre>
An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
</pre>

The `head_bucket` boto3 method could be used to check whether the bucket exists, instead of `create_bucket` method:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_bucket

I could fix the issue using:

<pre>
root@mamedin-am191:/opt/archivematica/archivematica-storage-service/storage_service/locations/models# git diff s3.py
diff --git a/storage_service/locations/models/s3.py b/storage_service/locations/models/s3.py
index b11ac14..9c6aba8 100644
--- a/storage_service/locations/models/s3.py
+++ b/storage_service/locations/models/s3.py
@@ -69,7 +69,12 @@ class S3(models.Model):
         return self._resource
 
     def _ensure_bucket_exists(self):
-        self.client.create_bucket(Bucket=self._bucket_name())
+        try:
+            self.client.head_bucket(Bucket=self._bucket_name())
+        except:
+            self.client.create_bucket(
+                    Bucket=self._bucket_name(),
+                    CreateBucketConfiguration={ 'LocationConstraint': self.region })
 
     def _bucket_name(self):
         return self.space_id/pre>
