### ISSUE TITLE
Problem: Cannot rebuild AM1.8 AIPs indices from files in AM1.9.1

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#674]
**Expected behaviour**

AM 1.9.1 should rebuild AM1.8 AIPs indices from files.

**Current behaviour**

After upgrading from AM1.8 to AM1.9.1, I tried to rebuild AIP index running:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_elasticsearch_aip_index_from_files \
         /var/archivematica/sharedDirectory/www/AIPsStore   --delete-all
";
```

Then I got error:

```
Deleting all AIPs in the AIP index
Rebuilding AIPS index from AIPS in /var/archivematica/sharedDirectory/www/AIPsStore
Processing AIP 7575cdaa-5997-4e5f-8a99-b726bc5708d3
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpfjJoA2', '/var/archivematica/sharedDirectory/www/AIPsStore/7575/cdaa/5997/4e5f/8a99/b726/bc57/08d3/mamedin-test-without-strange-chars-7575cdaa-5997-4e5f-8a99-b726bc5708d3.7z', 'mamedin-test-without-strange-chars-7575cdaa-5997-4e5f-8a99-b726bc5708d3/data/METS.7575cdaa-5997-4e5f-8a99-b726bc5708d3.xml']
/var/archivematica/sharedDirectory/www/AIPsStore/7575/cdaa/5997/4e5f/8a99/b726/bc57/08d3/mamedin-test-without-strange-chars-7575cdaa-5997-4e5f-8a99-b726bc5708d3.7z: 7-Zip
  mamedin-test-without-strange-chars-7575cdaa-5997-4e5f-8a99-b726bc5708d3/data/METS.7575cdaa-5997-4e5f-8a99-b726bc5708d3.xml  (69609 B)... OK.
Successfully extracted to "/tmp/tmpfjJoA2/mamedin-test-without-strange-chars-7575cdaa-5997-4e5f-8a99-b726bc5708d3".
AIP UUID: 7575cdaa-5997-4e5f-8a99-b726bc5708d3
Indexing AIP ...
Removed FITS output from METS.
Done.
Indexing AIP files ...
Removed FITS output from METS.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 301, in handle
    delete_existing_data=options['delete'],
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 172, in processAIPThenDeleteMETSFile
    identifiers=[],  # TODO get these
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 455, in index_aip_and_files
    printfn=printfn,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 561, in _index_aip_files
    xml = ElementTree.tostring(dmd_section_info)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'
```

**Steps to reproduce**

Create a transfer directory with files:

```
artefactual@mamedin-xenial-reindex-test-am18:~/test-transfer-jpg-with-metadata$ find
.
./test.jpg
./metadata
./metadata/metadata.csv
```

Using as `metadata.csv`file:

```
artefactual@mamedin-xenial-reindex-test-am18:~/test-transfer-jpg-with-metadata$ cat metadata/metadata.csv 
filename,dc.title,fonds_collection,dc.date,dc.description,source_of_title,dc.language,inventory_remarks,reformatting_remarks,reformatting_dates
objects/test.jpg,This is a fond collection name,This is a title example,2019,"This is a description example.",This is a source tittle example,English,This is an inventory remarks example.,Reformatted by some user that belongs to some group.,preservation copy 2019-05-01
```
Ingest the transfer in AM1.8 and upgrade AM to v1.9.1. then try to rebuild the index with:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_elasticsearch_aip_index_from_files \
         /var/archivematica/sharedDirectory/www/AIPsStore   --delete-all
";
```

**Your environment (version of Archivematica, OS version, etc)**

AM1.9.1 and Ubuntu Xenial (ansible deploy).

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
The transfer described in description fails when indexing, reindexing or reingesting in AM1.9.1. But I can index, reindex and reingest the transfer in AM1.8

**Comment by mamedin** [comment]
Using other metadata file works, for example:

```
filename,dc.title,dc.creator,dc.subject,dc.subject,dc.subject,dc.subject,dc.subject,dc.description,dc.publisher,dc.contributor,dc.date,dc.type,dc.format,dc.identifier,dc.source,dc.language,dc.language,dc.relation,dc.coverage,dc.rights
objects/test.jpg,OCR image,Tesseract,,,,,,This image was retrieved from the Tesseract wiki (https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage) to test optical character recognition in Archivematica.,,,,,,,Tesseract project,en,de,,,

**Comment by mamedin** [comment]
Can be related to #619

**Comment by hakamine** [comment]
The problem seems to be that AIP file indexing in 1.9 breaks when the `metadata.csv` in the transfer source contains both Dublin Core and non-Dublin Core metadata. As explained in the [docs](https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/transfer/import-metadata), the METS file will contain separate `<dmdSec>` for the Dublin Core (DC) and non-DC metadata. For example, for the following `metadata.csv` file:

```
filename,dc.title,fonds_collection,dc.date,dc.description,source_of_title,dc.language,inventory_remarks,reformatting_remarks,reformatting_dates
objects/lion.svg,Test Tile,Test fonds,2019-05-03,"Test description",Title taken from the document label and accompanying material,English,Some inventory remarks.,Some reformatting remarks.,preservation copy 2019-02-27
```
the resulting METS has these:
```
  <mets:dmdSec ID="dmdSec_2">
    <mets:mdWrap MDTYPE="DC">
      <mets:xmlData>
        <dcterms:dublincore xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xsi:schemaLocation="http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd">
          <dc:title>Test Tile</dc:title>
          <dc:date>2019-05-03</dc:date>
          <dc:description>Test description</dc:description>
          <dc:language>English</dc:language>
        </dcterms:dublincore>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:dmdSec ID="dmdSec_3">
    <mets:mdWrap MDTYPE="OTHER" OTHERMDTYPE="CUSTOM">
      <mets:xmlData>
        <fonds_collection>Test fonds</fonds_collection>
        <source_of_title>Title taken from the document label and accompanying material</source_of_title>
        <inventory_remarks>Some inventory remarks.</inventory_remarks>
        <reformatting_remarks>Some reformatting remarks.</reformatting_remarks>
        <reformatting_dates>preservation copy 2019-02-27</reformatting_dates>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
```
Also the METS has the following corresponding `DMDID` in the `<structMap>`:
```
  <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
    <mets:div LABEL="test-metadata-mixed-917acb24-763d-4c97-a4ab-40b45ea556af" TYPE="Directory" DMDID="dmdSec_1">
      <mets:div LABEL="objects" TYPE="Directory">
        <mets:div LABEL="lion.svg" TYPE="Item" DMDID="dmdSec_2 dmdSec_3">
          <mets:fptr FILEID="file-923e2e11-1497-4f93-995b-d932b7d580cd"/>
        </mets:div>
```
After doing some debugging (with pdb), it looks like the error occurs because DMDID is a list of dmdSec IDs (and not a single one). The structMap and dmdSec are parsed in [this code block](https://github.com/artefactual/archivematica/blob/84661775836cf8037ad3b48feb8e02bb80335f0f/src/archivematicaCommon/lib/elasticSearchFunctions.py#L541-L567) of ElasticSearchFunctions:_index_aip_files().  After assigning `dmd_section_id` to 'dmdSec_2 dmdSec_3' (parsed from the DMDID), the code tries to find a dmdSec with ID="dmdSec_2 dmdSec_3" but it returns `None` (presumably because there is not a dmdSec with ID="dmdSec_2 dmdSec_3", only a dmdSec with ID="dmdSec_2" and another with ID="dmdSec_3")

**Comment by jraddaoui** [comment]
I think @hakamine was already working on a fix. Please, reassign to me otherwise.

**Comment by hakamine** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/1414 (qa/1.x) and https://github.com/artefactual/archivematica/pull/1416 (stable/1.9.x)

**Comment by mamedin** [comment]
The fix works fine in AM stable/1.9.x

**Comment by sallain** [comment]
@mamedin Can you test this when running upgrade tests? Move to done when complete.

**Comment by sallain** [comment]
@mamedin @scollazo @jraddaoui does #619 being resolved mean that this issue can be closed as well?
