### ISSUE TITLE
Please stop injecting configuration via environment SS_ variables

### ISSUE THREAD

**Issue by goetzk** [archivematica/Issues#683]
**Expected behaviour**

* Running Django management commands works in virtualenv; eg
sudo -u archivematica /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python /usr/lib/archivematica/storage-service/manage.py shell

* Configuration is stored in single Django config file used by the service, not spread and duplicated.
Examples of duplication: embedded in (eg) gunicorn configuration; /var/archivematica/.storage-service

A fix similar to that used by logging would seem appropriate.
```
ubuntu@utas-archivematica:/etc/archivematica$ sudo egrep -C1 -r 'storageService.logging.json' /usr/share/archivematica/
/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/base.py-# `logging.config.fileConfig` unless it doesn't exist.
/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/base.py:LOGGING_CONFIG_FILE = '/etc/archivematica/storageService.logging.json'
/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/base.py-
```

**Current behaviour**

management command example:
```
ubuntu@utas-archivematica:/etc/archivematica$ sudo -u archivematica /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python /usr/lib/archivematica/storage-service/manage.py shell
Traceback (most recent call last):
  File "/usr/lib/archivematica/storage-service/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/core/management/base.py", line 406, in run_from_argv
    connections.close_all()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/db/utils.py", line 259, in close_all
    for alias in self:
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/db/utils.py", line 253, in __iter__
    return iter(self.databases)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/db/utils.py", line 152, in databases
    self._databases = settings.DATABASES
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/local.py", line 21, in <module>
    'NAME': get_env_variable('SS_DB_NAME'),
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/base.py", line 22, in get_env_variable
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the SS_DB_NAME environment variable
```

**Steps to reproduce**

Attempt to access management command without setting over a dozen environment variables

**Your environment (version of Archivematica, OS version, etc)**
AM 1.7.1 though the same issue appears to persist in 1.9.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
Hi @goetzk. Should we move this discussion to https://github.com/archivematica/Issues/issues/185? I think we were trying to describe the same problem.
I suggested a different solution thought but a final decision has not been made yet so feel to comment on your idea further. I proposed a new executable because that gives us the opportunity to replace the existing interfaces iteratively and untied us from specifics of the underlying web framework.

**Comment by goetzk** [comment]
Hi @sevein ,
We certainly appear to have a lot of overlap in our tickets. I'm familiar with django so once I'd figured out where the environment was only the configuration became an annoyance. 
I'm not sure about your proposed solution as I'm concerned it will simply mask the problem I'm reporting - though I'm open to being convinced its a non issue in your proposal :)

Karl.

**Comment by sevein** [comment]
I hear what you are saying. Updating our project setting module so it can load config from a file (e.g. see [envparse](https://github.com/rconradharris/envparse)) could be an alternative.
With a change like this, a lot of the effort is usually spent in updating our packages and the Ansible role, documenting the changes, testing software upgrades, fresh installs, etc... the trickiest part is usually to find the resources.

**Comment by goetzk** [comment]
I can certainly appreciate that it will have implications in many areas. It will lead to easier to understand and use tooling and configuration processes at the cost of that initial investment - testing time would be the largest issue by far.
Unfortunately I can't offer to help with the changes so will leave it to Archivematica/Artefactual to decide on the course of action - such as closing this in favour of #185. I remain convinced this would be the correct fix but your work in #185 shows that will be far quicker to implement.
