### ISSUE TITLE
Problem: Cannot get replication working on qa/1.x (1.10 dev branch)

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#684]
**Expected behaviour**

I can create a replicator and storing an AIP doesn't fail.

**Current behaviour**

We're seeing an Attribute error when trying to store the AIP:

```
storeaip_v0.0: WARNING   2019-05-09 09:54:04,507  archivematica.mcp.client.storeAIP.store_aip:245  SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'Package' object has no attribute 'origin_location'.
SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'Package' object has no attribute 'origin_location'. See logs for more details.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 353, in call
    args.sip_type,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 246, in store_aip
    raise Exception(errmsg + " See logs for more details.")
Exception: SIP creation failed: Failure storing file: <type 'exceptions.AttributeError'>: 'Package' object has no attribute 'origin_location'. See logs for more details.
```

**Steps to reproduce**

* Create a replicator location (in this case, I'm just trying to create one on the same disk parallel to my other storage locations (for convenience as the storage service can see it).
* Associate the AIP store with the replicator.
* Attempt a transfer, it will fail at Store AIP. 

**Your environment (version of Archivematica, OS version, etc)**

Docker-compose:
* AM Commit: 84ba815eedc0b102d22723637f7576291890c0ae
* Storage Service Commit: ca9ef05df95fe793752a0ee7f082eae3e3d4db8b 

Verified on the commits on: http://am191bionic.qa.archivematica.org as well.

**Additional context**

Related to: https://github.com/archivematica/Issues/issues/463

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
This failed on xenial and RPM with the following error:

```
500 Server Error: INTERNAL SERVER ERROR for url: http://54.39.191.197:8000/api/v2/file/Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 356, in call
    args.sip_type,
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 241, in store_aip
    related_package_uuid,
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 77, in _create_file
    agents=get_agents_from_db(uuid),
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 347, in create_file
    response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://54.39.191.197:8000/api/v2/file/
```

**Comment by ross-spencer** [comment]
We investigated on Xenial, and we were able to drill down into the specifics of the issue a little more, and it looks like during replication we end up with a null object pointer causing this error when in the storage service we try and access one of its attributes:
```
INFO      2019-07-09 11:20:24  locations.models.package:package:create_pointer_file:1404:  Returning pointer file for: 747b9203-908e-4e13-a293-da9ce5c644ad
INFO      2019-07-09 11:20:24  locations.models.package:package:replicate:554:  Replicating package 747b9203-908e-4e13-a293-da9ce5c644ad to replicator location c7f75617-b
c8e-4da0-8c2f-0bdf80755c00
INFO      2019-07-09 11:20:24  locations.models.space:space:move_rsync:546:  Moving from /var/archivematica/sharedDirectory/www/AIPsStore/747b/9203/908e/4e13/a293/da9c/e5
c6/44ad/684-replicator-747b9203-908e-4e13-a293-da9ce5c644ad.tar.bz2 to /var/archivematica/storage_service/d706/cf23/038c/4a07/95fd/1bd5/bf4d/b82f/684-replicator-d706cf23-
038c-4a07-95fd-1bd5bf4db82f.tar.bz2
INFO      2019-07-09 11:20:24  locations.models.space:space:move_rsync:588:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o
-rwx', '-r', '/var/archivematica/sharedDirectory/www/AIPsStore/747b/9203/908e/4e13/a293/da9c/e5c6/44ad/684-replicator-747b9203-908e-4e13-a293-da9ce5c644ad.tar.bz2', '/var
/archivematica/storage_service/d706/cf23/038c/4a07/95fd/1bd5/bf4d/b82f/684-replicator-d706cf23-038c-4a07-95fd-1bd5bf4db82f.tar.bz2']
ERROR     2019-07-09 11:20:24  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/file/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1047, in obj_create
    self._store_bundle(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 982, in _store_bundle
    aip_subtype=aip_subtype,
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 778, in store_aip
    self.create_replicas()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1427, in create_replicas
    self.replicate(replicator_loc)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 600, in replicate
    master_premis_object = master_ptr_aip_fsentry.get_premis_objects()[0]
AttributeError: 'NoneType' object has no attribute 'get_premis_objects'
```
`metsrw` us up-to-date:
```
root@am110xenial:/# /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import metsrw
>>> print metsrw.__version__
0.3.10
```
And the error is appearing here, https://github.com/artefactual/archivematica-storage-service/blob/fbdf31dcc5794065cf31b2d8701a97e280b40883/storage_service/locations/models/package.py#L598-L602 in the code. 

As Sara noted, we can also see a similar failure on RPM. 

Testing on Docker, however, and it looks like this works as expected. It isn't clear what the difference here might be that causes the problem. 

**Additional info**

The packages are listed in the storage service. The original can be accessed.

![image](https://user-images.githubusercontent.com/1880412/60922799-da724d80-a29d-11e9-9564-c8f6cf71cf09.png)

The replicated one cannot be accessed. 

![image](https://user-images.githubusercontent.com/1880412/60923000-45238900-a29e-11e9-87ce-90be88339fb3.png)

**Comment by cole** [comment]
I was able to replicate this issue in the docker environment; the problem was the new `file-` prefix was being included in the AIP uuid, breaking a lookup of the master PREMIS object during replication.

**Comment by sallain** [comment]
This is now working!
