### ISSUE TITLE
AIP Store Failure in AM19 RPM upgrades

### ISSUE THREAD

**Issue by jlong2git** [archivematica/Issues#686]
**Expected Result**
Store AIP

**Current behaviour**
Some jobs work  but some Store fails with 404
`404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/async/16/Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/job.py", line 102, in JobContext
    yield
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 212, in store_aip
    related_package_uuid)
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 67, in _create_file
    agents=get_agents_from_db(uuid)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
    ret = wait_for_async(response)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 223, in wait_for_async
    poll_response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/async/16`

**Steps to reproduce**
This started after upgrade from 1.8 to 1.9.1
Not sure what causing some jobs fail the job that failed was a large set of aiff files
213 Files 48GB

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.9.1 ,Storage Service 1.4.1, Redhat 7

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment]
Hi @jlong2git - could you please post to the Archivematica user forum: https://groups.google.com/forum/#!forum/archivematica . This looks to be a deployment problem rather than a code problem and either ourselves or other users will be better able to help you there. Thanks!
