### ISSUE TITLE
Problem: Store AIP fails syncing a big 7z file

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#697]
**Expected behaviour**

Store the AIP 

**Current behaviour**

The "Store the AIP" job fails:

<pre>
May 20 22:30:01 archivematica-qa python: *** Completed job: #<storeaip_v0.0; exit=1; code=success uuid=9e7affc1-2d01-4ef9-a80c-fd957ec22134
May 20 22:30:01 archivematica-qa python: =============== STDOUT ===============
May 20 22:30:01 archivematica-qa python: =============== END STDOUT ===============
May 20 22:30:01 archivematica-qa python: =============== STDERR ===============
May 20 22:30:01 archivematica-qa python: HTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=600)Traceback (most recent call last):
May 20 22:30:01 archivematica-qa python: File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 102, in JobContext
May 20 22:30:01 archivematica-qa python: yield
May 20 22:30:01 archivematica-qa python: File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
May 20 22:30:01 archivematica-qa python: args.sip_uuid, args.sip_name, args.sip_type))
May 20 22:30:01 archivematica-qa python: File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 212, in store_aip
May 20 22:30:01 archivematica-qa python: related_package_uuid)
May 20 22:30:01 archivematica-qa python: File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/store_aip.py", line 67, in _create_file
May 20 22:30:01 archivematica-qa python: agents=get_agents_from_db(uuid)
May 20 22:30:01 archivematica-qa python: File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
May 20 22:30:01 archivematica-qa python: ret = wait_for_async(response)
May 20 22:30:01 archivematica-qa python: File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 222, in wait_for_async
May 20 22:30:01 archivematica-qa python: timeout=poll_timeout_seconds).get(poll_url)
May 20 22:30:01 archivematica-qa python: File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
May 20 22:30:01 archivematica-qa python: return self.request('GET', url, **kwargs)
May 20 22:30:01 archivematica-qa python: File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
May 20 22:30:01 archivematica-qa python: resp = self.send(prep, **send_kwargs)
May 20 22:30:01 archivematica-qa python: File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
May 20 22:30:01 archivematica-qa python: r = adapter.send(request, **kwargs)
May 20 22:30:01 archivematica-qa python: File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 69, in send
May 20 22:30:01 archivematica-qa python: return super(HTTPAdapterWithTimeout, self).send(*args, **kwargs)
May 20 22:30:01 archivematica-qa python: File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
May 20 22:30:01 archivematica-qa python: raise ReadTimeout(e, request=request)
May 20 22:30:01 archivematica-qa python: ReadTimeout: HTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=600)
</pre>

**Steps to reproduce**

Ingest a 481Gb hard drive image. It fails when the whole 91Gb compressed 7-zip is syncing from  
currentlyProcessing to the accessions storage.

**Your environment (version of Archivematica, OS version, etc)**

RHEL and AM v1.9.1

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
The 600s timeout seems related to the hardcoded  `poll_timeout_seconds`:

https://github.com/artefactual/archivematica/blob/stable/1.9.x/src/archivematicaCommon/lib/storageService.py#L203

Testing again with a higher `poll_timeout_seconds`

**Comment by scollazo** [comment]
I'm seeing this in user reports
