### ISSUE TITLE
Silent failure of "Extract contents from compressed archives" job

### ISSUE THREAD

**Issue by jorikvankemenade** [archivematica/Issues#775]
**Expected behaviour**
When a transfer fails due to the failure of a job this task should be marked as "Failed". 

**Current behaviour**
The "Extract contents from compressed archives" has failed, but is reported as completed successfully. 

![Failed transfer in overview](https://user-images.githubusercontent.com/7934339/60425685-5829bf80-9bf3-11e9-966a-723fba8c222c.png)

In the job details, you can see that the job has failed. 

![Job details](https://user-images.githubusercontent.com/7934339/60425786-93c48980-9bf3-11e9-883e-1cf47a04bd01.png)

Although an earlier screenshot is created for [this mailing list post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/archivematica/0NxIbYq60qA/v0DtaDCYAgAJ) showed a completely silent failure:

![Silent job details](https://user-images.githubusercontent.com/7934339/60426008-09305a00-9bf4-11e9-80cd-21c034d470b9.png)

So it seems that the log parsing has some delay that adds some extra information.

**Steps to reproduce**
This particular error is caused by a MySQL crash that happens during the transfer of a compressed archive with many files. In this case, I used a transfer that contains a zip with more than 71 000 files. This causes the following error:

```
2019-06-28T07:44:22.089337067Z archivematicaClient.py: ERROR     2019-06-28 07:44:22,089  archivematica.common:retryOnFailure:340:  Failed to complete transaction "Write task results" after 10 retries
2019-06-28T07:44:22.091372272Z archivematicaClient.py: ERROR     2019-06-28 07:44:22,091  archivematica.mcp.client:execute_command:245:  Exception while processing task extractcontents_v0.0: (2006, 'MySQL server has gone away')
2019-06-28T07:44:22.091425283Z Traceback (most recent call last):
2019-06-28T07:44:22.091428125Z   File "/src/MCPClient/lib/archivematicaClient.py", line 235, in execute_command
2019-06-28T07:44:22.091430457Z     retryOnFailure("Write task results", write_task_results_callback)
2019-06-28T07:44:22.091432665Z   File "/src/archivematicaCommon/lib/databaseFunctions.py", line 342, in retryOnFailure
2019-06-28T07:44:22.091435143Z     raise e
2019-06-28T07:44:22.091437235Z OperationalError: (2006, 'MySQL server has gone away')
2019-06-28T07:44:22.324663919Z archivematicaClient.py: INFO      2019-06-28 07:44:22,324  archivematica.mcp.client:execute_command:206:
```

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.9.1 deployed using Docker Compose on Ubuntu 18.04 LTS.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment]
@jorikvankemenade could this be a duplicate of https://github.com/archivematica/Issues/issues/568?

**Comment by jorikvankemenade** [comment]
@ross-spencer although the underlying error is different the symptoms are similar. There is a small difference though, #568 does not fail based on an error that is buried in the `INFO` channel. In the cases of this job is the `ERROR` channel. I leave it up to you to judge if this is a different case or not.

**Comment by sromkey** [comment]
I'd add further to this that it might be desirable for processing to continue even if extraction fails. The user can choose to reject the transfer at some further stage, but in some use cases it would be better for the processing to continue if even the contents cannot be extracted.

**Comment by ross-spencer** [comment]
> but in some use cases it would be better for the processing to continue if even the contents cannot be extracted. 

Though this service is not the right way to manage this, depending on the failure, this may be our only indication there is an issue with the compressed file that affects preservation. This could potentially be mitigated by creating a zip validation rule for a tool such as `zipinfo`:
```bash
zipinfo $(find . -type f | ack zip$)
Archive:  ./zip/broken-cp437.zip
Zip file size: 333 bytes, number of entries: 3
error [./zip/broken-cp437.zip]:  missing 274 bytes in zipfile
  (attempting to process anyway)
error [./zip/broken-cp437.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
I'm not sure what other more generic utilities might exist for other package types.

**Comment by sromkey** [comment]
Zip validation is a great idea! In the meantime, I think the error should be visible, but not completely fail the transfer though.

**Comment by sromkey** [comment]
As reported on the user forum, a possible variant to this is the extract packages microservice failing because a job within it has failed, even if that job would not normally result in a failed transfer, e.g. file identification. See: https://groups.google.com/g/archivematica/c/wNylRaG4DgM/m/1UahtwMeAgAJ
