### ISSUE TITLE
Problem: AMAUAT has test failures prior to the release of 1.10

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#795]
**Expected behaviour**

AMAUAT tests pass.

**Current behaviour**

I will come back to summarize thee, but the detailed failures, running AMAUAT via docker-compose locally, with `qa/1.x-rc-1`. The majority of these seem to be user-interface changes introduced in `stable/1.9`. A proposed fix for the PID binding tests can be found [here](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/144) and this should help with the features here relying on METS download.

* `sudo make test-at-behave TAGS=uuids-dirs BROWSER=Firefox`
```
Feature: UUIDs for Directories # features/core/uuids-for-directories.feature:48
      Sometimes Archivematica users want to be able to treat the directories in a
      transfer as intellectual entities. They want to be able to assign identifiers
      (UUIDs) to them and, ultimately, be able to assign persistent identifiers
      (PIDs) to them, such as handles or DOIs.
      Scenario Outline: Lucien wants to create an AIP where each subdirectory of the original transfer is assigned a UUID and this is recorded in the AIP's METS file. -- @1.1 transfer sources  # features/core/uuids-for-directories.feature:64
        Given a processing configuration that assigns UUIDs to directories                                                                                                                       # features/steps/uuids_for_directories_steps.py:108 5.507s
          Assertion Failed: FAILED SUB-STEP: And the processing config decision "Select file format identification command (Transfer)" is set to "Identify using Fido"
          Substep info: Traceback (most recent call last):
            File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
              match.run(runner.context)
            File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
              self.func(context, *args, **kwargs)
            File "features/steps/steps.py", line 71, in step_impl
              decision_label=decision_label, choice_value=choice_value
            File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
              decision_select.select_by_visible_text(choice_value)
            File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
              raise NoSuchElementException("Could not locate element with visible text: %s" % text)
          selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Identify using Fido
```

* `sudo make test-at-behave TAGS=mo-aip-reingest BROWSER=Firefox`
* **nb.** times out because this decision point no longer adopts this format.
```
Feature: Metadata-only AIP re-ingest # features/core/metadata-only-aip-reingest.feature:19
  Users want to be able to take an existing AIP and perform a metadata-only
  re-ingest on it so that they can add metadata to it and confirm that those
  metadata are in the re-ingested AIP's METS file.
  Scenario: Isla creates an AIP, and then performs a metadata-only re-ingest on it, adds metadata to it, and confirms that her newly added metadata are in the modified METS file.   # features/core/metadata-only-aip-reingest.feature:24
    Given that the user has ensured that the default processing config is in its default state                                                                                       # features/steps/steps.py:50 3.036s
    And the reminder to add metadata is enabled                                                                                                                                      # features/steps/steps.py:58 0.845s
    When a transfer is initiated on directory ~/archivematica-sampledata/SampleTransfers/Images/pictures                                                                             # features/steps/steps.py:417 55.667s
    And the user waits for the "Assign UUIDs to directories?" decision point to appear and chooses "No" during transfer                                                              # features/steps/steps.py:243 2.449s
    And the user waits for the "Select file format identification command" decision point to appear and chooses "Identify using Fido" during transfer                                # features/steps/steps.py:243
```

* `sudo make test-at-behave TAGS=tpc BROWSER=Firefox`

```
Feature: Transfer policy check # features/core/transfer-policy-check.feature:2
  Archivists want to check that the original files they transfer conform to a
  pre-defined policy/policies before proceeding with further digital
  preservation actions.
  Scenario Outline: Isla has started a transfer of files and needs to know if they conform to her policy for original files. -- @1.1 Policy Check Outcomes                    # features/core/transfer-policy-check.feature:26
    Given a processing configuration for policy checks on originals                                                                                                           # features/steps/mediaconch_steps.py:174 6.189s
      Assertion Failed: FAILED SUB-STEP: Given a base processing configuration for MediaConch tests
      Substep info: Assertion Failed: FAILED SUB-STEP: And the processing config decision "Select file format identification command (Transfer)" is set to "Identify using Fido"
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 71, in step_impl
          decision_label=decision_label, choice_value=choice_value
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Identify using Fido
      
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 71, in step_impl
          decision_label=decision_label, choice_value=choice_value
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/mediaconch_steps.py", line 72, in step_impl
          "Given that the user has ensured that the default processing config is"
        File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
          assert False, message
```

* `sudo make test-at-behave TAGS=ipc BROWSER=Firefox`

```
Feature: Ingest policy check # features/core/ingest-policy-check.feature:2
  Archivists want to check that the files that are defined for access or
  preservation conform to a pre-defined policy (or policies). The access and
  preservation derivatives may have been created by Archivematica through
  normalization or may have been predefined by the user prior to
  transfer.
  @access @nonmanual
  Scenario Outline: Isla has access derivatives and she needs to know whether they conform to her access policy -- @1.1 Policy Check Outcomes                           # features/core/ingest-policy-check.feature:28
    Given a processing configuration for policy checks on access derivatives                                                                                            # features/steps/mediaconch_steps.py:162 1.859s
      Assertion Failed: FAILED SUB-STEP: Given a base processing configuration for MediaConch tests
      Substep info: Assertion Failed: FAILED SUB-STEP: Given that the user has ensured that the default processing config is in its default state
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Use existing data
      
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/mediaconch_steps.py", line 72, in step_impl
          "Given that the user has ensured that the default processing config is"
        File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
          assert False, message
```

* `sudo make test-at-behave TAGS=picc BROWSER=Firefox`

```
Feature: Transfer (i.e., pre-ingest) Conformance Check # features/core/transfer-mkv-conformance.feature:2
  Archivists need to know whether or not mkv files which they are
  preserving are valid before they process them, because if they are
  invalid it might impact further preservation decisions.
  Scenario Outline: Isla wants to confirm that her file is a valid .mkv -- @1.1 File Validity Possibilities  # features/core/transfer-mkv-conformance.feature:18
    Given a processing configuration for conformance checks on originals                                     # features/steps/mediaconch_steps.py:186 2.097s
      Assertion Failed: FAILED SUB-STEP: Given a base processing configuration for MediaConch tests
      Substep info: Assertion Failed: FAILED SUB-STEP: Given that the user has ensured that the default processing config is in its default state
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Use existing data
      
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/mediaconch_steps.py", line 72, in step_impl
          "Given that the user has ensured that the default processing config is"
        File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
          assert False, message
```

* `sudo make test-at-behave TAGS=aip-encrypt-mirror BROWSER=Firefox`

```
Feature: AIP Encryption via Mirror Locations # features/core/aip-encryption-mirror.feature:32
  Archivematica users want to be able to store AIPs unencrypted with encrypted
  replicas in mirror locations. This allows easy access to unencrypted AIPs
  as well as the ability to make redundant copies of encrypted replicas
  off-site.
  @compressed
  Scenario: Richard wants to create an AIP with an encrypted replica.                                                                                    # features/core/aip-encryption-mirror.feature:39
    Given there is a standard GPG-encrypted space in the storage service                                                                                 # features/steps/aip_encryption_steps.py:30 2.226s
    And there is a standard GPG-encrypted Replicator location in the storage service                                                                     # features/steps/aip_encryption_steps.py:70 0.946s
    And the default AIP Storage location has the GPG-encrypted Replicator location as its replicator                                                     # features/steps/aip_encryption_steps.py:83 0.948s
    And the default processing config is in its default state                                                                                            # features/steps/steps.py:42 1.680s
      Assertion Failed: FAILED SUB-STEP: Given that the user has ensured that the default processing config is in its default state
      Substep info: Traceback (most recent call last):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Use existing data  
      
      Traceback (of failed substep):
        File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 55, in step_impl
          context.am_user.browser.ensure_default_processing_config_in_default_state()
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 454, in ensure_default_processing_config_in_default_state
          choice_value="Use existing data",
        File "/home/artefactual/acceptance-tests/amuser/am_browser_ability.py", line 400, in set_processing_config_decision
          decision_select.select_by_visible_text(choice_value)
        File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
          raise NoSuchElementException("Could not locate element with visible text: %s" % text)
      
      Captured logging:
      INFO:amuser.ss:Local Filesystem
      does NOT match
      GPG encryption on Local Filesystem
      INFO:amuser.ss:No SS space matching attributes {'Access protocol': 'GPG encryption on Local Filesystem',
       'GnuPG Private Key': 'Archivematica Storage Service GPG Key',
       'Path': '/',
       'Staging path': '/var/archivematica/storage_service/storage_service_encrypted'}
      INFO:amuser.ss:space with attributes {'Access protocol': 'GPG encryption on Local Filesystem', 'Path': '/', 'Staging path': '/var/archivematica/storage_service/storage_service_encrypted', 'GnuPG Private Key': 'Archivematica Storage Service GPG Key'} does NOT exist
      INFO:amuser.ss:location with attributes {'Purpose': 'Replicator', 'Relative path': 'var/archivematica/sharedDirectory/www/EncryptedReplicas', 'Description': 'Encrypted Replicas'} does NOT exist
```

**Steps to reproduce**

Run the AMAUAT suite with the current release-candidate and observe the results for the six tests here. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment]
@ross-spencer to review and add t-shirt sizing to tests

**Comment by ross-spencer** [comment]
Related to: https://github.com/archivematica/Issues/issues/438
Related to: https://github.com/archivematica/Issues/issues/542
Related to: https://github.com/archivematica/Issues/issues/737

**Comment by sallain** [comment]
Removed milestone because this isn't a release blocker, but still very important!
