### ISSUE TITLE
Problem: coreutils is too far behind on some distributions and so blake2 checksums will not work

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#796]
Having a bit of maintainers remorse over this one...

Spotted by @currmie and @sallain in testing, Blake2 (b2) was introduced as a potential checksum in this PR [here](https://github.com/artefactual/archivematica/pull/1333).

But in Xenial, and RPM testing we see this error:
```
Comparing transfer checksums with the supplied b2 file
[Errno 13] Permission deniedTraceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/job.py", line 111, in JobContext
    yield
  File "/usr/lib/archivematica/MCPClient/clientScripts/verify_checksum.py", line 310, in call
    job.set_status(run_hashsum_commands(job))
  File "/usr/lib/archivematica/MCPClient/clientScripts/verify_checksum.py", line 292, in run_hashsum_commands
    result = hashsum.compare_hashes(transfer_dir=transfer_dir)
  File "/usr/lib/archivematica/MCPClient/clientScripts/verify_checksum.py", line 133, in compare_hashes
    self._call("-c", "--strict", self.hashfile, transfer_dir=transfer_dir)
  File "/usr/lib/archivematica/MCPClient/clientScripts/verify_checksum.py", line 108, in _call
    subprocess.check_output(self.command_called, cwd=kwargs.get("transfer_dir"))
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Diagnosis**

The hashsum utilities are part of [GNU's Coreutils](https://www.gnu.org/software/coreutils/manual/html_node/Summarizing-files.html#Summarizing-files).

We install this on the different distributions as part of the PR. 

Unfortunately, the versions on Xenial and RPM are behind that needed for the Blake2 function, and cannot easily be upgraded using the package manager.

Minimum requirement for Blake2: `8.26`
Available on Xenial: `8.25` (I haven't looked at RPM) 

From the coreutils [changelog](https://fossies.org/linux/coreutils/ChangeLog) (and [b2 pr](https://github.com/coreutils/coreutils/commit/ea94589e9ef02624a3837f97f80efd7d3dcf56bf#diff-48092b14d580e065b83d6a323a59aad4)):
```
 5196 2016-01-20  Pádraig Brady  <P@draigBrady.com>
 5197 
 5198 	maint: post-release administrivia
 5199 	* NEWS: Add header line for next release.
 5200 	* .prev-version: Record previous version.
 5201 	* cfg.mk (old_NEWS_hash): Auto-update.
 5202 
 5203 	version 8.25
 5204 	* NEWS: Record release date.
 5205 

 4081 2016-11-22  Pádraig Brady  <P@draigBrady.com>
 4082 
 4083 	b2sum: a new checksum utility with md5sum like interface
 4084 	Note we don't support the --algorithm option of the
 4085 	b2sum command in the external BLAKE2 project, as that
 4086 	was deemed too confusing for users.
 4087 	"BLAKE2b" was chosen as the default algorithm to use,
 4088 	which is single threaded but performs well on 64 bit.
 
 3730 2016-11-30  Pádraig Brady  <P@draigBrady.com>
 3731 
 3732 	maint: post-release administrivia
 3733 	* NEWS: Add header line for next release.
 3734 	* .prev-version: Record previous version.
 3735 	* cfg.mk (old_NEWS_hash): Auto-update.
 3736 
 3737 	version 8.26
 3738 	* NEWS: Record release date.
 3739 
```
 
If I understand the `apt-cache show` function correctly then we can't go higher than `8.25` on Xenial. 
```
artefactual@am110xenial:~$ apt-cache show coreutils | grep Version
Version: 8.25-2ubuntu3~16.04
Version: 8.25-2ubuntu2
```
vs. Docker:
```
apt-cache show coreutils | grep Version
Version: 8.28-1ubuntu1
```

**Possible fixes**

1. We catch and manage the `OSError` above, and output a warning that the `Blake2` checksum utility isn't supported if it is invoked. 

_Pros:_ It will still work in newer distributions.
_Cons:_ Lack of a visual or codified warning in the result of microservice jobs means that folks trying to run `b2` comparison only will not see their checksums verified and it will be difficult to identify that this is happening. 

2. Remove Blake2 support again. 

_Pros:_ Equivalent functionality across all deployments. 
_Cons:_ We just have to remove Blake2 again from the sampledata and references from the docs. 

3. Something else? 

(Am I missing anything from a package management perspective?)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by jhsimpson** [comment]
Looking at the details in https://github.com/artefactual/archivematica/pull/1333, I see how that PR (which introduces b2) is connected to #346 and https://github.com/artefactual/archivematica/issues/1061.  I can't tell myself, from the description on PR1333, how introducing b2 resolves those two issues.

The preferred mechanism for introducing new preservation tools in Archivematica should probably be through the Preservation Planning module, i.e as new FPR tools, with new FPR commands and rules to use those tools.  The microservice that performs checksum verification is not currently configurable through the FPR, so it is understandable that b2 was not introduced that way, but perhaps this suggests a path forward for resolving this issue (#796).  Here is my suggestion:

1) revert PR1333
2) create a new PR that resolves issues 346 and 1061 using the existing tool (md5sum)
3) create a new PR that makes the checksum validation microservice use the FPR to determine which tools to use.  md5sum and b2 can be set up as options.  md5sum can be the default, since it works on all supported distributions, but for systems that have a recent enough version of b2 avaiable, users can opt to switch to that tool.

**Comment by ross-spencer** [comment]
Hi @jhsimpson https://github.com/artefactual/archivematica/pull/1333 introduced the entire `hashsum` suite and the inclusion of `Blake2` is just this one-line [here](https://github.com/artefactual/archivematica/blob/bc993369dadfc9607b8db85bb63e8906492b8555/src/MCPClient/lib/clientScripts/verify_checksum.py#L78 ). The PR itself is a direct replacement for the existing microservice which runs this [shell script](https://github.com/artefactual/archivematica/blob/stable/1.9.x/src/MCPClient/lib/clientScripts/verifyMD5.sh). We replace the hashdeep suite with hashsum and introduce testing, and checks in aid of resolving both of the connected issues #348 is already marked as resolved via testing and artefactual/archivematica#1061 I expect to be resolved too where `hashsum` as noted in the original ticket does perform a 1:1 comparison where `hashdeep` wasn't. 

We can connect more in Slack if I can walk you though anything, otherwise, this implementation has been a widely communicated pathway for this feature since the Christmas break. I am not aware of any of the checksum tools being configured via the FPR in the way you describe, and so that would be a fairly radical change in our approach here which is a much bigger conversation. 

I will add a clarification to the issue description above.

**Comment by ross-spencer** [comment]
With the change, users will see this in `stderr`:
```
Comparing transfer checksums with the supplied sha512 file
Comparing transfer checksums with the supplied sha1 file
Comparing transfer checksums with the supplied sha256 file
Comparing transfer checksums with the supplied md5 file
```
**NB.** For transparency `SHA512` was also added in the same PR. The `SHA512` algorithm was added to `coreutils` circa 2008 as far as I can tell. We should not experience the same problem. I also tested `sha512sum --version` on Xenial and the command is happily in place there.

**Comment by ross-spencer** [comment]
@sromkey @sallain I wonder if this was tagged incorrectly, yesterday? Following our chat in Slack I've attached three PRs to toggle `blake2` off for merging into the `qa/1.x` branch prior to the next `rc` and that will ensure the checksum validation situation is back to normal :)

**Comment by sromkey** [comment]
@ross-spencer we could leave this issue open for future potential inclusion of blake2?

**Comment by ross-spencer** [comment]
Ah, true! Now I recall I think that's what Sara was looking for. I see. Shall I merge the fixes that removes it from this against this ticket anyway do you think?

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
