### ISSUE TITLE
Problem: Insufficient error reporting around AWS S3/Glacier errors

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#800]
**Please describe the problem you'd like to be solved.**

Error reporting for users trying to downloading stored AIPs that are in S3 but unavailable could be better. Right now, it fails to download but the reason is not clear.

Here is an example traceback for a file that has been stored in S3 but moved to Glacier:

```
ERROR     2019-07-12 13:42:54  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/file/2ce61982-be64-44c7-83ba-bf2c335f1bde/download/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 99, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 944, in download_request
    full_path = package.get_download_path(lockss_au_number)
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 212, in get_download_path
    full_path = self.fetch_local_path()
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 268, in fetch_local_path
    destination_space=ss_internal.space,
  File "/usr/lib/archivematica/storage-service/locations/models/space.py", line 324, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/models/s3.py", line 148, in move_to_storage_service
    bucket.download_file(objectSummary.key, dest_file)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/boto3/s3/inject.py", line 168, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/boto3/s3/inject.py", line 130, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ClientError: An error occurred (InvalidObjectState) when calling the GetObject operation: The operation is not valid for the object's storage class
```

**Describe the solution you'd like to see implemented.**

This error could be handled and relayed to the user instead of an ambiguous message left in the storage service logs.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
