### ISSUE TITLE
Problem: DIP upload to ArchivesSpace fails after reingest

### ISSUE THREAD

**Issue by sromkey** [archivematica/Issues#82]
**Expected behaviour**

Users should be able to reingest an AIP, normalize for access and upload the resulting DIP to ArchivesSpace.

**Current behaviour**

A failure occurs in the Upload DIP to ArchivesSpace job:

`Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/upload-archivesspace.py", line 230, in <module>
    upload_to_archivesspace(files, client, args.xlink_show, args.xlink_actuate, args.object_type, args.use_statement, args.uri_prefix, args.dip_uuid, args.access_conditions, args.use_conditions, args.restrictions, args.dip_location, args.inherit_notes)
  File "/usr/lib/archivematica/MCPClient/clientScripts/upload-archivesspace.py", line 71, in upload_to_archivesspace
    mets = mets_file(mets_source)
  File "/usr/lib/archivematica/archivematicaCommon/xml2obj.py", line 24, in mets_file
    file_uuid = amd.mets_techMD.mets_mdWrap.mets_xmlData.premis_object.premis_objectIdentifier.premis_objectIdentifierValue
AttributeError: 'list' object has no attribute 'mets_mdWrap'`

**Steps to reproduce**

- store an AIP
- do a full reingest
- ensure that your normalization path makes a DIP
- choose Upload DIP to ArchivesSpace at DIP upload, match at least one object to an ArchivesSpace resource and finalize the matches
- back in the ingest screen, Archivematica will throw the error in Upload DIP.

**Your environment (version of Archivematica, OS version, etc)**

Archivematica 1.7.2-rc.1

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
