### ISSUE TITLE
Problem: "Edit rights metadata" button in ArchivesSpace pane of Appraisal tab leads to error message

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#827]
**Expected behaviour**
When I select an ArchivesSpace resource and click on "Edit rights metadata" in the ArchivesSpace pane of the Appraisal tab, I should be able to enter rights metadata into a form in the Archivematica GUI. See documentation [here](https://www.archivematica.org/en/docs/archivematica-1.9/user-manual/appraisal/appraisal/#creating-archival-description).

**Current behaviour**
The button opens a new tab with an internal server error message.

![image](https://user-images.githubusercontent.com/4612276/61981899-e6edea00-afaf-11e9-97f1-12dc8a9e0eb0.png)

**Steps to reproduce**
1. In the ArchivesSpace pane of the Appraisal tab, select a resource
2. Click on "Edit rights metadata"

**Your environment (version of Archivematica, OS version, etc)**
1.9.x, 1.10 RC

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sarah-mason** [comment]
We discussed this today when I came across this problem again in testing. @sromkey noted there is a workaround for this at the moment where a user can start a SIP and then enter the rights metadata in the Ingest tab. 

There may be an argument for having the metadata recorded before a SIP is created in from the Appraisal tab, but there is probably also an argument for getting rid of the button if fixing it will be too complicated.

**Comment by replaceafill** [comment]
We bumped into this during QA today and this is the traceback when this happens:

```
ERROR     2020-06-11 19:56:13  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /access/archivesspace/-repositories-2-archival_objects-126/rights/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/access/views.py", line 97, in wrapper
    return func(request, mapping)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/access/views.py", line 106, in wrapper
    arrange_path=os.path.join(mapping.arrange_path, "")
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: SIPArrange matching query does not exist.
ERROR     2020-06-11 19:56:18  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /ingest/199c3f29-918b-4921-920e-0070d98c823f/rights/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archivematica/archivematica/src/dashboard/src/components/rights/views.py", line 72, in ingest_rights_list
    return rights_list(request, uuid, "ingest")
  File "/opt/archivematica/archivematica/src/dashboard/src/components/rights/views.py", line 776, in rights_list
    name = jobs.get_directory_name()
  File "/opt/archivematica/archivematica/src/dashboard/src/main/models.py", line 759, in get_directory_name
    return job.get_directory_name()
AttributeError: 'NoneType' object has no attribute 'get_directory_name'
```

**Comment by sallain** [comment]
Just realized that this is a duplicate of #556. Closing that issue since this one has the workaround and traceback.

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
