### ISSUE TITLE
Problem: Ldap auth fails on dashboard

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#841]
**Expected behaviour**

The dashboard ldap auth should work with the sample config: https://github.com/artefactual/archivematica/pull/710#issue-135307158

**Current behaviour**

Testing with the sample config:

https://github.com/artefactual/archivematica/pull/710#issue-135307158

And adding `ARCHIVEMATICA_DASHBOARD_DASHBOARD_LDAP_AUTHENTICATION=true` to `/etc/default/archivematica-dashboard`:

```
ARCHIVEMATICA_DASHBOARD_DASHBOARD_LDAP_AUTHENTICATION=true

AUTH_LDAP_SERVER_URI = 'ldap://ldap.forumsys.com'
AUTH_LDAP_BIND_DN = 'cn=read-only-admin,dc=example,dc=com'
AUTH_LDAP_BIND_PASSWORD = 'password'
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'dc=example,dc=com',
    ldap.SCOPE_SUBTREE,
    '(uid=%(user)s)'
)
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "cn",
    "last_name": "sn",
    'email': 'mail',
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {}
```

 I got the error:

```
WARNING   2019-07-31 11:16:32  django_auth_ldap:backend:authenticate:396:  'str' object has no attribute 'execute' while authenticating mamedin
ERROR     2019-07-31 11:16:32  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /administration/accounts/login/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 44, in login
    if form.is_valid():
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/forms/forms.py", line 393, in full_clean
    self._clean_form()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/forms/forms.py", line 417, in _clean_form
    cleaned_data = self.clean()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 157, in clean
    password=password)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 148, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 208, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 377, in authenticate
    self._authenticate_user_dn(password)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 500, in _authenticate_user_dn
    if self.dn is None:
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 465, in dn
    self._load_user_dn()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 533, in _load_user_dn
    self.settings.GROUP_CACHE_TIMEOUT
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 1035, in cache_get_or_set
    value = default() if callable(default) else default
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 556, in _search_for_user_dn
    results = search.execute(self.connection, {'user': 
```

I got the same error when using the Artefactual ldap server.

**Steps to reproduce**

Described above

**Your environment (version of Archivematica, OS version, etc)**

Ubuntu Bionic.
AM 1.10

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by cole** [comment]
Related: https://github.com/archivematica/Issues/issues/798

**Comment by cole** [comment]
Just to clarify a bit, the sample config linked to is a series of Django settings, to be placed in a settings.py file, not something that could work as environment variables (set in `/etc/default/archivematica-dashboard`).

I think the expected outcome of this issue should be that LDAP is configurable via env variables, and the configuration options are documented in the settings README.

**Comment by mamedin** [comment]
Hi Cole,

We just need to make configurable the following variables, as done for SS :

* `AUTH_LDAP_START_TLS`
* `AUTH_LDAP_USER_SEARCH_BASE_DN`
* `AUTH_LDAP_USER_SEARCH_BASE_FILTERSTR`

`AUTH_LDAP_GROUP_CACHE_TIMEOUT` is another interesting variable that could be set as configurable. Its default value is big (3600s) so it can become a problem when testing. `AUTH_LDAP_GROUP_CACHE_TIMEOUT=0` means no authentication cache.

**Comment by cole** [comment]
Those have all been exposed, and the changes merged into the qa/1.x branch: https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/install/README.md#ldap-variables. Is there a way you're able to test against that branch?

For `AUTH_LDAP_GROUP_CACHE_TIMEOUT`, note that it should only have an effect if you set `AUTH_LDAP_CACHE_GROUPS` to true.

**Comment by mamedin** [comment]
Tested with TLS on am110ldap QA server. :+1:

**Comment by ablwr** [comment]
(@mamedin tested)
