### ISSUE TITLE
Problem: Index AIP failure can look more serious than it is

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#868]
**Expected behaviour**
When `Job: Index AIP` fails, Archivematica should indicate to the user if this is a simple indexing problem or if the AIP has a whole has failed.

**Current behaviour**
When `Job: Index AIP` fails, Archivematica always proceeds to `Microservice: Failed SIP`. This happens even if the AIP itself has been successfully stored. For users, this can read as a complete failure. Trying to ingest the same material again can result in duplicate AIPs being created, which can only be seen by viewing the Packages tab in the Storage Service. The AIP not being indexed properly is inconvenient and undesirable, but it's not a complete failure.

Where this gets complicated is that sometimes a failure at `Job: Index AIP` is indicative that the AIP was not stored properly, but I'm not sure how to reproduce this other situation. This would be a much more serious issue.

**Steps to reproduce**
I'm not really sure - the common error that is seen is that the ElasticSearch index is set to read-only (ES does this itself when it runs out of disk). Setting the ES index to read-only and then processing a transfer to storage should do the trick, is that's possible.

**Your environment (version of Archivematica, OS version, etc)**
1.9.x

**Logs/output**
```
Standard output (stdout)
AIP info: [{u'status': u'UPLOADED', u'package_type': u'AIP', u'origin_pipeline': u'/api/v2/pipeline/66b0d99c-d425-40f6-a8c2-ef97d19008c6/', u'uuid': u'83fbf4d8-c90c-4ba4-a9d0-0b09d649822e', u'replicas': [], u'encrypted': True, u'current_path': u'83fb/f4d8/c90c/4ba4/a9d0/0b09/d649/822e/test-sja-83fbf4d8-c90c-4ba4-a9d0-0b09d649822e.7z', u'replicated_package': None, u'misc_attributes': {}, u'current_full_path': u'/mnt/storage/encrypted_aipstore/83fb/f4d8/c90c/4ba4/a9d0/0b09/d649/822e/test-sja-83fbf4d8-c90c-4ba4-a9d0-0b09d649822e.7z', u'current_location': u'/api/v2/location/4d9ae263-34e7-485a-b7b8-7b2b05f9786a/', u'related_packages': [], u'size': 23483063, u'resource_uri': u'/api/v2/file/83fbf4d8-c90c-4ba4-a9d0-0b09d649822e/'}]
Indexing additional identifiers %s []
Indexing AIP and AIP files
AIP UUID: 83fbf4d8-c90c-4ba4-a9d0-0b09d649822e
Indexing AIP ...
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
ERROR: error trying to index.
AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
```
```
Standard error (stderr)
AuthorizationException(403, u'cluster_block_exception', {u'status': 403, u'error': {u'root_cause': [{u'reason': u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];', u'type': u'cluster_block_exception'}], u'type': u'cluster_block_exception', u'reason': u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];'}})
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 114, in call
    status_code = index_aip(job)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/index_aip.py", line 90, in index_aip
    printfn=job.pyprint,
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 446, in index_aip_and_files
    _try_to_index(client, aip_data, 'aips', printfn=printfn)
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 756, in _try_to_index
    raise exception
AuthorizationException: AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
```

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment]
This issue is being closed as part of a bulk closure process. Please click [here](https://groups.google.com/u/1/g/archivematica/c/Sq7uw1zloTA) for further information.
