### ISSUE TITLE
Problem: Implementation details are shown in the UI in Job: Parse External METS

### ISSUE THREAD

**Issue by ross-spencer** [archivematica/Issues#886]
**Please describe the problem you'd like to be solved.**

The user interface is clear and unambiguous to its various users. The purpose of a micrsoservice should be clear. 

Parse External METS currently replays an stack trace to the user even though execution of the script is normal. 
```
parseexternalmets: INFO      2019-08-16 23:19:08,204  archivematica.mcp.client.parse_external_mets.parse_reingest_mets:24  Error parsing reingest mets None - skipping
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/parse_external_mets.py", line 20, in parse_reingest_mets
    root = etree.parse(mets_path)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124318)
TypeError: cannot parse from 'NoneType'
```

This makes it unclear whether this is anticipated, or what is expected by this task. 

1. [parse external mets](https://github.com/artefactual/archivematica/blob/862c4cdd780f1a235f20716d8472d34d9b56094f/src/MCPClient/lib/clientScripts/parse_external_mets.py#L18) calls: 2. [assign-file-uuids](https://github.com/artefactual/archivematica/blob/862c4cdd780f1a235f20716d8472d34d9b56094f/src/MCPClient/lib/clientScripts/assign_file_uuids.py#L57-L66)

`stdout` shows the following: `Error parsing reingest METS None  - skipping`.

In this instance, if we're not performing a reingest, then the UI shouldn't suggest there is an error as there is none. 

For the developer, the code shows that we were expecting to handle an exception but we have wrapped a catch-all around this exception without commentary, so the question for the user might be whether `TypeError: cannot parse from 'NoneType"` is expected? (in-short, yes). 

**Describe the solution you'd like to see implemented.**

I think right now, the only solution to this is to clean-up the code to manage exceptions explicitly, and to not replay the stack-trace to the user. I.e. if all we anticipate is a `TypeError` and the error is specifically around the path string being `None` we can test that explicitly, and should. We can clear up the output for the user so that this is only an error if it happens on reingest. 

We can also clear up the micro-service name to let folks know that the intended purpose of this job is to parse, and extract metadata from a METS XML in a reingest workflow. It extracts a SIP UUID, Dublin Core, and Rights metadata. 

**Describe alternatives you've considered.**

In a long-term solution, annotation of microservices could be considered and replayed back to the user through various approaches. Tool-tip, extension to the UI template, etc. 

A approach taken in Archivematica previously has been to set a unit variable and have an equivalent unit variable link pull which ensures tasks like this only execute in the appropriate workflows but this brings about its own complexities. 

**Additional context**

This isn't anticipated to be a bug. The issue can be seen in a standard workflow, or other workflows such as disk processing. It was tested on `1.10-rc` and `1.9`. The output does not manifest when reingest happens proper on either platform. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by amayita** [comment]
We are seeing this issue again and again on 1.13 now, making transfer fail when they didn't use to fail before 1.13:

raise Exception("No METS file found in %s" % src)
@sevein 
`parse_external_mets` also **marks the job as failed** when the user did not provide an external METS, I think that was just an oversight probably. 

@tw4l 
`find_mets_file` used to return None if no METS was found, now it raises an OSError exception that we should probably handle explicitly in the parse_external_mets client script if we're gonna fix it

find_mets_file used to return None if no METS was found, now it raises an OSError exception that we should probably handle explicitly in the parse_external_mets client script
