### ISSUE TITLE
Problem: Dashboard doesn't start when installed from packages (Ubuntu AM1.10.0) 

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#903]
**Expected behaviour**

archivematica-dashboard service should start on deb installations ( AM1.10.0)

**Current behaviour**

Running ` journalctl -u archivematica-dashboard -x` :

```
Sep 10 11:14:12 archivematica gunicorn[17388]: [2019-09-10 11:14:12 +0000] [17388] [INFO] Starting gunicorn 19.9.0
Sep 10 11:14:12 archivematica gunicorn[17388]: [2019-09-10 11:14:12 +0000] [17388] [INFO] Listening at: http://127.0.0.1:8002 (17388)
Sep 10 11:14:12 archivematica gunicorn[17388]: [2019-09-10 11:14:12 +0000] [17388] [INFO] Using worker: gevent
Sep 10 11:14:12 archivematica gunicorn[17388]: [2019-09-10 11:14:12 +0000] [17434] [INFO] Booting worker with pid: 17434
Sep 10 11:14:13 archivematica gunicorn[17388]: [2019-09-10 11:14:13 +0000] [17434] [ERROR] Exception in worker process
Sep 10 11:14:13 archivematica gunicorn[17388]: Traceback (most recent call last):
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Sep 10 11:14:13 archivematica gunicorn[17388]:     worker.init_process()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init
Sep 10 11:14:13 archivematica gunicorn[17388]:     super(GeventWorker, self).init_process()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_pr
Sep 10 11:14:13 archivematica gunicorn[17388]:     self.load_wsgi()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_ws
Sep 10 11:14:13 archivematica gunicorn[17388]:     self.wsgi = self.app.wsgi()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Sep 10 11:14:13 archivematica gunicorn[17388]:     self.callable = self.load()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
Sep 10 11:14:13 archivematica gunicorn[17388]:     return self.load_wsgiapp()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgi
Sep 10 11:14:13 archivematica gunicorn[17388]:     return util.import_app(self.app_uri)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
Sep 10 11:14:13 archivematica gunicorn[17388]:     __import__(module)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
Sep 10 11:14:13 archivematica gunicorn[17388]:     result = _import(*args, **kwargs)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/dashboard/wsgi.py", line 7, in <module>
Sep 10 11:14:13 archivematica gunicorn[17388]:     application = get_wsgi_application()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_appl
Sep 10 11:14:13 archivematica gunicorn[17388]:     django.setup()
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
Sep 10 11:14:13 archivematica gunicorn[17388]:     apps.populate(settings.INSTALLED_APPS)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
Sep 10 11:14:13 archivematica gunicorn[17388]:     app_config = AppConfig.create(entry)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
Sep 10 11:14:13 archivematica gunicorn[17388]:     module = import_module(entry)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Sep 10 11:14:13 archivematica gunicorn[17388]:     __import__(name)
Sep 10 11:14:13 archivematica gunicorn[17388]:   File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
Sep 10 11:14:13 archivematica gunicorn[17388]:     result = _import(*args, **kwargs)
Sep 10 11:14:13 archivematica gunicorn[17388]: ImportError: No module named longerusername
Sep 10 11:14:13 archivematica gunicorn[17388]: [2019-09-10 11:14:13 +0000] [17434] [INFO] Worker exiting (pid: 17434)
Sep 10 11:14:13 archivematica gunicorn[17388]: [2019-09-10 11:14:13 +0000] [17388] [INFO] Shutting down: Master
Sep 10 11:14:13 archivematica gunicorn[17388]: [2019-09-10 11:14:13 +0000] [17388] [INFO] Reason: Worker failed to boot.
Sep 10 11:14:13 archi
Sep 10 11:14:13 archivematica systemd[1]: archivematica-dashboard.service: Failed with result 'exit-code'.vematica systemd[1]: archivematica-dashboard.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
``` 

**Steps to reproduce**

Following: https://www.archivematica.org/pt-br/docs/archivematica-1.10/admin-manual/installation-setup/installation/install-ubuntu/#install-pkg-ubuntu

**Your environment (version of Archivematica, OS version, etc)**

Ubuntu Xenial and Bionic, AM v1.10.0 from deb packages.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment]
The issue is located in the dashboard virtualenv, so the following workaround works (recreate virtualenv):

```
sudo su -
apt install virtualenv
cd /usr/share/archivematica/virtualenvs
rm -rf archivematica-dashboard
virtualenv archivematica-dashboard
source archivematica-dashboard/bin/activate
cd archivematica-dashboard
pip install --upgrade -r /usr/share/archivematica/dashboard/requirements.txt
sudo service archivematica-dashboard restart
```

**Comment by mamedin** [comment]
Issue comes from https://groups.google.com/forum/#!msg/archivematica/V022TagPn24/6qo4zHomBAAJ

**Comment by sevein** [comment]
Fixed.
