### ISSUE TITLE
Separate Storage Server

### ISSUE THREAD

**Issue by jmcgranahan** [archivematica/Issues#927]
**Expected behaviour**
Archivematica-storage should be able to send files to Archivematica for processing, no matter if it is on the same server or not.

**Current behaviour**
http://archivematica.library.vanderbilt.edu/ is unable to process files from our storage server, located at http://archivematica-storage.library.vanderbilt.edu/

Error log file (/var/log/archivematica/MCPServer/MCPServer.debug.log):
```
DEBUG     2019-10-01 20:34:17  archivematica.mcp.server:package:_start:325:  Package ec959313-a3a0-47c5-9a6f-4a8506b9bc53: starting transfer (('test', u'standard', 'e4f7d748-f676-4e1c-92e3-adab814520f4:/apps/Images', '/var/archivematica/sharedDirectory/tmp/tmp2qbiwA'))
DEBUG     2019-10-01 20:34:17  archivematica.mcp.server:package:_start_package_transfer_with_auto_approval:409:  Package ec959313-a3a0-47c5-9a6f-4a8506b9bc53: determined vars transfer_rel=tmp/tmp2qbiwA/test, filepath=/var/archivematica/sharedDirectory/tmp/tmp2qbiwA/test, path=e4f7d748-f676-4e1c-92e3-adab814520f4:/apps/Images/.
DEBUG     2019-10-01 20:34:17  archivematica.mcp.server:package:_start_package_transfer_with_auto_approval:416:  Package ec959313-a3a0-47c5-9a6f-4a8506b9bc53: copying chosen contents from transfer sources (from=e4f7d748-f676-4e1c-92e3-adab814520f4:/apps/Images/., to=tmp/tmp2qbiwA/test)
DEBUG     2019-10-01 20:34:17  archivematica.common:storageService:get_location:192:  Storage locations returned: [{u'uuid': u'194600f8-0cd4-4f0c-89c3-534723a89b49', u'pipeline': [u'/api/v2/pipeline/42991a9e-30d8-4ded-b556-85168fb0e1ea/'], u'used': u'0', u'description': None, u'space': u'/api/v2/space/72376017-c0ab-41b3-a5bc-84927cb3e515/', u'enabled': True, u'quota': None, u'relative_path': u'var/archivematica/sharedDirectory/', u'purpose': u'CP', u'path': u'/var/archivematica/sharedDirectory', u'resource_uri': u'/api/v2/location/194600f8-0cd4-4f0c-89c3-534723a89b49/'}]
DEBUG     2019-10-01 20:34:17  archivematica.common:storageService:get_location:192:  Storage locations returned: [{u'uuid': u'e4f7d748-f676-4e1c-92e3-adab814520f4', u'pipeline': [u'/api/v2/pipeline/42991a9e-30d8-4ded-b556-85168fb0e1ea/'], u'used': u'0', u'description': u'Apps', u'space': u'/api/v2/space/72376017-c0ab-41b3-a5bc-84927cb3e515/', u'enabled': True, u'quota': None, u'relative_path': u'apps', u'purpose': u'TS', u'path': u'/apps', u'resource_uri': u'/api/v2/location/e4f7d748-f676-4e1c-92e3-adab814520f4/'}]
DEBUG     2019-10-01 20:34:17  archivematica.mcp.server:package:_copy_from_transfer_sources:220:  source: Images/., destination: /var/archivematica/sharedDirectory/tmp/tmp2qbiwA/test/.
WARNING   2019-10-01 20:34:17  archivematica.common:storageService:copy_files:257:  Unable to move files with {'files': [{'source': u'Images/.', 'destination': '/var/archivematica/sharedDirectory/tmp/tmp2qbiwA/test/.'}], 'pipeline': u'/api/v2/pipeline/42991a9e-30d8-4ded-b556-85168fb0e1ea/', 'origin_location': u'/api/v2/location/e4f7d748-f676-4e1c-92e3-adab814520f4/'} because 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage.library.vanderbilt.edu/api/v2/location/194600f8-0cd4-4f0c-89c3-534723a89b49/
ERROR     2019-10-01 20:34:17  archivematica.mcp.server:package:wrap:371:  Exception: The following errors occured: 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage.library.vanderbilt.edu/api/v2/location/194600f8-0cd4-4f0c-89c3-534723a89b49/
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPServer/package.py", line 350, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/archivematica/MCPServer/package.py", line 418, in _start_package_transfer_with_auto_approval
    _copy_from_transfer_sources([path], transfer_rel)
  File "/usr/lib/archivematica/MCPServer/package.py", line 232, in _copy_from_transfer_sources
    % {"message": ", ".join(message)}
Exception: The following errors occured: 500 Server Error: INTERNAL SERVER ERROR for url: http://archivematica-storage.library.vanderbilt.edu/api/v2/location/194600f8-0cd4-4f0c-89c3-534723a89b49/

```

**Steps to reproduce**
Followed https://www.archivematica.org/en/docs/archivematica-1.10/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos
--> Step 4 Install Archivematica Storage Service - this was done on a different server

**Your environment (version of Archivematica, operating system, other relevant details)**

Archivematica = Version | 1.10.0
-> CentOS 7.7.1908

Archivematica Storage Service = Version | 0.15.0
--> CentOS 7.7.1908
---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment]
We have done installs of 1.10 with the SS on another server so I'm thinking something might have gone wrong in your configuration or installation. Could you please post to the user forum? https://groups.google.com/forum/#!forum/archivematica We can re-open this issue if it turns out it is caused by a bug.
